ispc/ispc

alloy.py, builtins/util.m4, cbackend.cpp, ispc.h, main.cpp, opt.cpp, run_tests.py
3.6 still not in /tags, using 3.6 from /branches.
=> Added LLVM 3.7 support

fail_db.txt
- Update 'fail_db.txt' after the fix made in commit https://github.com/ispc/ispc/commit/d5cd049d8f9f40db645e9e128643e6df95b6da7d
=> Update 'fail_db.txt' 

cbackend.cpp, fail_db.txt
Some changes in code generator.
=> Knc header fix

opt.cpp
Link to github mirror: https://github.com/llvm-mirror/llvm/commit/1937233a222144826216aad1eb18ccbbd2ea3ecd
=> ISPC build fix on LLVM 3.7 (failed after rev.227685)

ispc.cpp
=> Fix build fail after commit c377d8465ebaab2f84c331d61a7813f0ce67ecd7

ispc.cpp
=> Fix for ispc trunk.

cbackend.cpp
cbackend.cpp was changed to support generic targets
=> Codegenerator fix for compability with generic

ispc.cpp
Link: https://llvm.org/svn/llvm-project/llvm/trunk@228961
=> Repair ispc build fail after LLVM commit 228961

module.cpp, run_tests.py, test_static.cpp, tests/align1.ispc, tests/align2.ispc
Now it can perform alignment tests; see 'align1.ispc' and 'align2.ispc' in /tests subdir.
=> Added structure alignment in headers; extended the test system

cbackend.cpp, func.cpp, module.cpp, opt.cpp
Git mirror link: https://github.com/llvm-mirror/llvm/commit/417c5c172ce0d56105112481b1bcf0bc2fc011c2
(Used instructions in LLVM commit message to update our code)
=> Fix buildfail after LLVM trunk commit 229094

examples/intrinsics/knc.h
- now stable with icc 13 as with icc 15
=> Update knc.h to work with icpc v13

ispc.cpp, ispc.h, main.cpp, module.cpp
Change the dll export feature to be controlled by a switch rather than the export keyword.
=> Change dll export feature to a switch.

main.cpp
Make it clear that opts are either off or on (no different levels)
=> Change opt help message to be more clear.

cbackend.cpp
Header ConstantsScanner.h was removed from LLVM, so we need to have our own for cbackend.cpp (llvm-mirror/llvm@bf71e29)
=> Fix for trunk revision #232397

Makefile
The issue pops up on some machines under some circumstances only.
=> Addressing build issue coming from LLVM bug 16902

docs/ispc.rst
Originally mistakenly pull-requested here https://github.com/ispc/ispc.github.com/pull/28
=> Fixed some typos

ctx.cpp, ctx.h, module.cpp
Addressing debug info creation issues.
=> Fix for LLVM trunk

builtins/dispatch.ll, check_isa.cpp, ispc.cpp, ispc.h
New isa for KNL and SKX was added. It converts to AVX2 and it should be changed in the future.
=> Check for new isa for KNL and SKX was added.

examples/intrinsics/knl.h
knl has new accuracy for reciprocal instructions.
=> New accuracy for knl.h

func.cpp, ispc.cpp, ispc.h, module.cpp
*-generic-16 target for multitarget compilation was added. It produces .cpp file.
=> Support of *-generic-16 target

builtins/dispatch.ll, check_isa.cpp, ispc.cpp
=> Adding check for OSXSAVE before checking xgetbv in cpu detection code.

examples/intrinsics/knc.h, examples/intrinsics/knl.h, tests/test-149.ispc, tests/test-150.ispc, tests/test-151.ispc, tests/test-152.ispc, tests/test-153.ispc
=> Add roundings for varying double in knc.h and knl.h

module.cpp
Removed other modules` name comparison, since the adder is only executed once.
=> Fixed global variable handling

builtins.cpp
A git mirror link: https://github.com/llvm-mirror/llvm/commit/20a6785cd235990cc8cb3e2e402b7f8caca609ec
=> Fix trunk buildfail after LLVM revision 239858

Makefile, ast.cpp, ast.h, ctx.cpp, decl.cpp, expr.cpp, expr.h, func.cpp, module.cpp, parse.yy, stmt.cpp, stmt.h, test_class_of.cpp, type.cpp
Now builds with -fno-rtti with all supported LLVM versions
=> Make ISPC way better

alloy.py
- Changed LLVM 3.7 download path
- Fixed a small issue which might provoke alloy to icc when not necessary
=> Changed LLVM 3.7 download path

builtins/target-avx512-common.ll
- TODO: log() and pow()
- Double functions have low accuracy (10^-7), (icc has 10^-15)
=> [AVX-512]: transcendentals: add exp() implementation, no functional change

builtins.cpp, cbackend.cpp, ctx.cpp, func.cpp, llvmutil.cpp, module.cpp
Check out links:
https://github.com/llvm-mirror/llvm/commit/5f220beefcb655de6aae7c80b456fd4e5cb76ac0
https://github.com/llvm-mirror/llvm/commit/45d3f0d253091e1cda26614864b9df3d86608a56
=> ISPC trunk fix after LLVM commits 252219 and 252380

builtins.cpp
Fixes ISPC build, still problems with stdlib 'undeclared symbols'
=> Fix ISPC after LLVM r255842

opt.cpp
Rearange IntrinsicsOpt pass to eliminate assert crash.
=> Rearrange IntrinsicsOpt pass

examples/intrinsics/knl.h
Adding __gather_base_offsets64_double() , __gather_base_offsets64_i64() for knl-generic.
=> Impl. for knl-generic target (fix compfails)

Makefile
=> Updating Makefile warning message to use LLVM 3.8.

cbackend.cpp
=> Revert "Fix for Revision 269218"

examples/tasksys.cpp
Added HPX[1] as additional task system option in examples/tasksys.cpp.
[1] http://stellar.cct.lsu.edu/projects/hpx/
=> Added HPX task system option

alloy.py, builtins/dispatch.ll, builtins/target-knl.ll, builtins/target-skx.ll, builtins/util-nvptx.m4, builtins/util.m4, ispc.h, ispc_version.h, module.cpp
-Adding support for LLVM 4.0
-Switching 3.9 support to branch/release_39
-Switching 3.8 support to tags/release_381
=> Adding support for LLVM 4.0 (trunk)

alloy.py
This is experimental for now, but going forward this will become
primary way of working with LLVM, as they are going to switch to
git in not too distant future.
=> Adding support for git repository instead of svn.

alloy.py, builtins.cpp, builtins/dispatch.ll, builtins/target-knl.ll, builtins/target-skx.ll, builtins/util-nvptx.m4, builtins/util.m4, cbackend.cpp, ispc.h, ispc_version.h, llvmutil.h, module.cpp
The changes are tested with LLVM 3.9, 4.0 and trunk on MacOS (sse4, avx2, skx).
=> Enabling LLVM 5.0 and making fixes to track changes in LLVM for the past couple months.

cbackend.cpp
Relevant svn commit: 300367
Github: https://github.com/llvm-mirror/llvm/commit/1f8f0490690b06270ff949d7da3d10a6921606f4
=> Fix for trunk change

cbackend.cpp
I think this was the commit with the initial fix: https://github.com/ispc/ispc/commit/6d649e1dff2985f728c8fa8d88b437f5d1eaef39
Unfortunately, I think the fix did not preserve the semantics of the old code with the new llvm api.
When exported with the current version of ispc's c backend, the following IR's C representation will be illegal: 
```llvm
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"
; Original C Code:
;int func() {
;  int *ip;
;  int a[2];
;  a[0] = 1;
;  a[1] = 6;
;  ip = &a[1];
;
;  return *ip;
;}
; Function Attrs: noinline nounwind uwtable
define i32 @func() {
entry:
%retval = alloca i32, align 4
%ip = alloca i32*, align 8
%a = alloca [2 x i32], align 4
store i32 0, i32* %retval, align 4
%arrayidx = getelementptr …
```
=> Better patch for printGEPExpression in cbackend

ctx.cpp, func.cpp, ispc.cpp, ispc.h, module.cpp
Changes in Attribute handling and clang::IK_None deprication.
=> Tracking LLVM changes.

builtins.cpp, ctx.cpp, examples/aobench/aobench.vcxproj, examples/common.props, examples/deferred/deferred_shading.vcxproj, examples/mandelbrot/mandelbrot.vcxproj, examples/mandelbrot_tasks/mandelbrot_tasks.vcxproj, examples/noise/noise.vcxproj, examples/options/options.vcxproj, examples/perfbench/perfbench.vcxproj, examples/rt/rt.vcxproj, examples/sort/sort.vcxproj, examples/stencil/stencil.vcxproj, examples/volume_rendering/volume.vcxproj, expr.cpp, ispc.cpp, module.cpp, opt.cpp, tests/struct-test-129.ispc, type.cpp
Fix for #1271, #1273, #1274.
Enabling debug info on Windows via CodeView debug info format.
Minor fixes in Windows example build scripts.
=> Bunch of stability and debug info fixes

ctx.cpp, ispc.cpp, opt.cpp, type.cpp
Relevant svn commit: 304864
Github: https://github.com/llvm-mirror/llvm/commit/19ca2b0f9daed883c21730285d7f04424e5f5f88
=> Fix for llvm upstream change

alloy.py
This turns out to be more stable.
=> Switching to https for svn checkouts.

tests/short-vec-5-unsigned.ispc, type.cpp, type.h
VectorType was missing handling for unsigned int types.
=> Fix support for short vectors of unsigned ints.

alloy.py, docs/perfguide.rst, module.cpp, run_tests.py, stmt.cpp, type.cpp
- Fixes for #1292, #1294, #1284, #1285, #1290.
- Moving to LLVM 5.0 release tag (for building through alloy.py)
=> Bunch of bug fixes

docker/Dockerfile-fedora, docker/Dockerfile-ubuntu
Adding examples of Docker files that build ISPC on top of Ubuntu and Fedora images.
=> Dockerfiles

docs/build.sh, docs/ispc.rst, docs/perfguide.rst, docs/template-news.txt, docs/template-perf.txt, docs/template.txt
- copyright update
- pulling typo fix from ispc.github.com repo
- updating rst2html invocation script
=> Docs update

docs/ispc.rst, main.cpp
Following on from my previous change-set, this updates the help text and documentation to cover the new command-line option
=> Update docs and help to cover @<filename> 

ispc.cpp
=> Issue 1253 : Adding new CPU to handle SSE2 only target.

stdlib.ispc, tests/all_false.ispc, tests/all_true.ispc, tests/any_false.ispc, tests/any_true.ispc, tests/none_false.ispc, tests/none_true.ispc
=> Fixing 'any()' implementation to work correctly with mask.

builtins/util.m4
=> Fixing memory_barrier() implementation.

Makefile, builtins/util.m4, module.cpp
- Makefile: compile builtins-c-32.cpp and builtins-c-64 before link step.
- minor bug in module.cpp due to copy-paste typo
- Typo in comments in util.m4
=> Set of minor fixes

examples/sgemm/SGEMM_kernels.ispc, examples/sgemm/SGEMM_main.cpp
Addresses whitespace and comment concerns.  Restores working build for windows.
=> Sgemm fixes2

.travis.yml, docker/fedora/Dockerfile, docker/ubuntu/Dockerfile, fail_db.txt, run_tests.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ispc/ispc/1360)
=> Enabling Travis CI for Linux

llvm_patches/5_0_6_0_7_0_r347287_optimize_zero_extended_mul.patch
=> Issue #1362: Porting llvm patch.

src/stmt.cpp
=> Issue #1309 : Updating expr created during type conversion.

llvm_patches/5_0_port_llvm_fixes_to_work_in_debug_mode.patch
=> Issue #1375 - This patch ensures compilation of ispc files with '-g' switch.

docs/ispc.rst
Tested the code snippet by making compiling and running it.
=> Fixing aos_to_soa3 documentation error.

llvm_patches/5_0_6_0_r347287_optimize_zero_extended_mul.patch, llvm_patches/7_0_r347287_optimize_zero_extended_mul.patch
The original fix works for 7.0 but needs an additional change for 6.0 and below.
=> Fix for #1385 ; modifying Issue 1362.

llvm_patches/6_0_7_0_fix_popcnt.patch
=> LLVM patch to fix popcnt.

fail_db.txt
Updating fail.db to reflect LLVM 8.0 change.
=> Fail_db.txt: 8.0 fixes

src/ispc.cpp, src/ispc.h, src/main.cpp, src/module.cpp, tests/lit-tests/1425.ispc
=> #1425 : switch to Pragma once in headers

alloy.py, run_tests.py
* Fix a typo in the fix for avx512skx-i32x8
* Timeout increase for tests.
=> Alloy fixes

builtins/target-avx512-common-8.ll, builtins/target-avx512-common.ll, builtins/target-avx512-utils.ll, builtins/target-skx-8.ll
- Had to include "target-avx512-common-8.ll" header for 9.0.
- Restructured the avx512 builtins to consolidate common code in single file.
=> Fix for issue #1514 :

tests/1475.ispc
There was a bug in the test implemenation. Fixing that.
=> Correcting tests for ispc#1475.

alloy.py
Also a fix for LLVM build on Mac when using git checkout.
=> LLVM 8.0.0 => LLVM 8.0.1

src/ispc.cpp, tests/lit-tests/ps4_cpu.ispc
=> Fixing CPU definition for PS4

src/ispc.cpp, src/ispc.h, src/main.cpp
Fixing support for PS4 - defaults needs to be enforced are the options parsed
=> PS4 default

examples/CMakeLists.txt
=> Fix examples compilation error

examples/tasksys.cpp
=> Fix alignment of struct

.appveyor.yml, .travis.yml, CMakeLists.txt, src/ispc.cpp, src/ispc.h, src/main.cpp, src/module.cpp, src/target_enums.cpp, src/target_enums.h, src/target_registry.cpp, src/target_registry.h, tests/lit-tests/arg_parsing_errors.ispc
* Print support matrix under --support-matrix
* Use information about dynamically link targets to report supported targets/arches/oses.
=> Support matrix

src/module.cpp
Fix for -M -MF file --target=target1,target2,...
=> Fix for #1647.

check_format.sh
Modify check_format.sh to check all source files, instead of changed in the last revision.
=> Modify check_format.sh to check all source files.

docs/ispc.rst
Here are a few errors I found reading through the user's guide. (Great job on the guide, btw!)
=> Small fixes in the user's guide

docs/ispc.rst
Another documentation fix. This one is a little less straight forward, but I had to run examples to be sure how it worked.
=> Doc fixes exclusive scan

src/llvmutil.cpp, src/util.cpp, tests/lit-tests/1673.ispc
=> Fix for A+B-->A|B breaking gather elimination in LLVM 11+

.gitmodules, CMakeLists.txt, benchmarks/01_trivial/CMakeLists.txt, benchmarks/01_trivial/README.md, benchmarks/02_medium/CMakeLists.txt, benchmarks/02_medium/README.md, benchmarks/02_medium/test01.cpp, benchmarks/02_medium/test01.ispc, benchmarks/03_complex/CMakeLists.txt, benchmarks/03_complex/README.md, benchmarks/CMakeLists.txt, benchmarks/README.md, benchmarks/cmake/AddBenchmark.cmake
Infrastructure for adding Google Benchmark-based benchmarks.
=> Benchmarks

docs/faq.rst, docs/perfguide.rst
See comments on individual changes.
=> Doc fixes for FAQ and perfguide

.appveyor.yml
Restructuring .appveypr.yml, so adding macOS or any other platform would be straightforward in the future.
=> Restructure .appveyor.yml

src/expr.cpp, tests/lit-tests/refBoolArgSelect.ispc
=> Fixing assert condition : Reference type can also return valid bool value.

examples/sgemm/SGEMM_kernels.ispc, examples/sgemm/SGEMM_main.cpp
This commit adds additional validation of input arguments (matrix sizes) to prevent errors in algorithms that require matrix size to be a multiple of SIMD width. It also modifies the mechanism of
=> SGEMM: fix MT version issues

docker/v1.13.0/centos7/Dockerfile, docs/ReleaseNotes.txt, doxygen.cfg, src/ispc_version.h
* bumping version to 1.14.0dev
* typos in release notes
* Dockerfile to build 1.13.0
=> V1.14.0dev

CMakeLists.txt, alloy.py, builtins/target-avx2-i16x16.ll, builtins/target-avx2-i8x32.ll, builtins/util.m4, src/ispc.cpp, src/target_enums.cpp, src/target_enums.h
Targets are functional, but need more performance tuning.
=> avx2-i8x32 and avx2-i16x16 targets

llvm_patches/10_0_Fix_For_1767.patch, tests/lit-tests/1767.ispc
=> Fix #1767 - Assertion `V.getNode() && "Getting TableId on SDValue()"' failed.

src/expr.cpp, tests/short-vec-int-logical.ispc
=> Fix #1769 - ISPC asserts when doing logical and/or with vectors.

src/ctx.cpp, src/expr.cpp, src/type.cpp, tests/lit-tests/1747.ispc, tests/short-vec-bool3.ispc, tests/short-vec-bool4.ispc
varying bool vector is stored in IR as array type. So, need to be
treated similar to array type in IR.
=> Fix  #1747 - Change base type for varying bool vector to int8.

src/expr.cpp, tests/lit-tests/1739.ispc
=> Fix #1739 - Print error when accessing vector elements incorrectly.

src/type.cpp, tests/lit-tests/1738.ispc
=> fix #1738 - Fix header file for SOA struct type.

llvm_patches/10_0_fix_for_1788.patch, tests/lit-tests/1788.ispc
=> fix #1788 - porting llvm patch from 11.0

.github/workflows/rebuild-llvm10.yml, alloy.py, docker/fedora/Dockerfile, docker/ubuntu/full_ispc_build/Dockerfile, docker/ubuntu/llvm_build/Dockerfile, llvm_patches/10_0_9_0_fix_for_1767.patch, llvm_patches/10_0_fix_for_1771_1.patch, llvm_patches/10_0_fix_for_1771_2.patch, llvm_patches/10_0_fix_for_1788.patch, llvm_patches/10_0_i8_shuffle_avx512_i8_i16.patch, llvm_patches/10_0_k_reg_mov_avx512_i8_i16.patch, llvm_patches/10_0_vXi1calling_avx512_i8_i16.patch, llvm_patches/5_0_6_0_r347287_optimize_zero_extended_mul.patch, llvm_patches/6_0_7_0_7_1_fix_popcnt.patch, llvm_patches/6_0_bug1381.patch, llvm_patches/7_0_7_1_fixWindows.patch, llvm_patches/7_0_7_1_r347287_optimize_zero_extended_mul.patch, llvm_patches/7_0_7_1_r355228_fix_gather_scatter_intrinsic.patch, llvm_patches/8_0_9_0_Fix_for_1595.patch, llvm_patches/8_0_issue1454_windows_O0.patch, llvm_patches/8_0_r362675.patch, llvm_patches/8_0_r372480_Fix_For_1627.patch, llvm_patches/9_0_10_0_avx512_disable_fast_isel_vxi1.patch
* Alloy support for svn and configure was removed
* Moving alloy.py to use "git apply" instead of "patch" utility for applying patches.
* Enabling Windows build in Github Actions
=> Alloy clean up and Windows build for Github Actions

.github/workflows/rebuild-llvm10.yml
👋 I was investigating the issue below and noticed this tiny typo. I've opened a ticket to provide some feedback when unknown attributes are added to triggers, sorry for the confusion.
Closes https://github.com/actions/runner/issues/545#issue-638549409
=> Fix Actions workflow path filter

.github/workflows/linux-nightly.yml, .github/workflows/rebuild-llvm10.yml, fail_db.txt
* Check CPU of the runner and print failing tests to the log
* Trigger rebuild on alloy.py and rebuild-llvm10.ym change
* Remove old fails from fail_db.txt
=> Set of minor CI changes

src/ctx.cpp, src/expr.cpp
Issue #1822 was filed to refactor the code to solve this problem in a propper way.
=> Fix static analysis.

alloy.py, src/ispc.h, src/ispc_version.h, src/opt.cpp
Tested locally but please wait for tests to pass anyway.
=> Modifying storeInst for latest llvm builds.

.github/workflows/rebuild-llvm10.yml, docker/ubuntu/full_ispc_build/Dockerfile, docker/ubuntu/llvm_build/Dockerfile, tests/lit-tests/1844.ispc
=> Add release builds to LLVM rebuild Github Action.

.github/workflows/linux-nightly-trunk.yml, .github/workflows/linux-nightly.yml
=> Update SDE version in Github Actions

llvm_patches/10_0_packed_load_store_avx512skx.patch, llvm_patches/11_0_packed_load_store_avx512.patch
=> Porting llvm patch to fix expandload/compressstore intrinsics for avx512skx.

.calcite/calcite.config.js, .calcite/package-lock.json, .calcite/package.json, .github/workflows/linux-benchmarks.yml, benchmarks/CMakeLists.txt
This is slightly modified PR #1907, which doesn't have visibility of organization secrets for some reason.
Resubmitting should fix that.
=> calcite - benchmarks in CI - retry

docker/centos7/Dockerfile, docker/fedora/Dockerfile, docker/ubuntu/full_ispc_build/Dockerfile
* do not install SVN in docker
* do not build macOS target in Linux docker
* set http_proxy as proxy for git if it's available in docker
=> Dockerfiles update

docker/v1.15.0/centos7/Dockerfile, doxygen.cfg, src/ispc_version.h
* change version to v1.16.0dev
* Dockerfile for v1.15.0 build
=> Post release changes

CMakeLists.txt, README.md
msi and zip files are generated simultaneously.
=> Return back zip cpack generator on windows

.github/workflows/linux-nightly-12.yml
This is temporary until 12.0 is released.
=> Adding 12.0 nightly testing

.appveyor.yml, .github/workflows/ispc-ci.yml, .github/workflows/linux-benchmarks.yml, .github/workflows/scripts/install-build-deps.ps1, .travis.yml
The repo to be used: https://github.com/ispc/llvm-project
Old repo: https://github.com/dbabokin/llvm-project
=> Use pre-built LLVM binaries for testing from ispc repo

src/opt.cpp
This is essentially dead code. 'FixBooleanSelectPass::fixSelect' is not called and the 'runOnFuction()' is basically a dummy call.
=> Removing 'dead' pass.

docs/ispc_for_gen.rst, ispcrt/detail/gpu/GPUDevice.cpp, ispcrt/tests/level_zero_mock/ze_mock.cpp, ispcrt/tests/level_zero_mock/ze_mock.h, ispcrt/tests/mock_tests/ispcrt_mock_main.cpp
* Fix limit of enqueued kernel launches
=> Updates for Gen target

src/ctx.cpp, src/ctx.h, src/expr.cpp, tests/launch-10.ispc, tests/launch-11.ispc, tests/lit-tests/2198.ispc
Fix for https://github.com/ispc/ispc/issues/2198
=> Allow uniform function pointers for launch expression

builtins/util-xe.m4, examples/xpu/README.txt, examples/xpu/pipeline-dpcpp/pipeline-dpcpp.cpp, examples/xpu/simple-dpcpp-l0/simple-dpcpp-l0.cpp, examples/xpu/simple-dpcpp/simple-dpcpp.cpp, examples/xpu/simple-esimd/simple-esimd.cpp, src/stmt.cpp, tests/lit-tests/print_errors.ispc, tests/lit-tests/print_errors_xe.ispc, tests/lit-tests/xe_barrier.ispc
This PR includes improved compiler diagnostics for incorrect format in print statements, implementation of `memory_barrier` stdlib function for Xe targets, and updates for ISPC/DPC++ examples aligned with recent DPC++ compiler changes.
=> Updates for Xe targets (4)

ispcrt/CMakeLists.txt
Pass `-fstack-protector-strong` to ispcrt build
=> Use stack protection in ispcrt build

docker/v1.17.0/centos7/Dockerfile
Updated docker for XPU build. Added docker for v1.17.0.
=> Updated docker files for v1.17 release

README.md, docs/ReleaseNotes.txt, docs/ispc.rst, doxygen.cfg, src/ispc_version.h
- version update
- readme update
- docs update
- release notes update
=> Release 1.17.0

README.md
=> Fix download link for Linux on README page

docs/ispc.rst
=> Add missing d suffix for hexadecimal double value in the docs

.travis.yml, docker/README.md, docker/ubuntu/18.04/cpu_ispc_build/Dockerfile
- Enabling aarch64 for Ubuntu 18.04 Dockerfile
- Move Travis to LLVM Ubuntu 18.04 build
=> Ubuntu 18.04 Dockerfile for aarch64

.github/workflows/rebuild-llvm14.yml, alloy.py
Also add a workflow to rebuild LLVM 14 binaries.
=> Move LLVM 14 tag to a release 14.0.0 version.

benchmarks/01_trivial/07_loop_unroll_varying.cpp
Changes:
*   Reduced the run time for the loop unroll benchmark.
*   ~Formatting.~
=> Benchmark: Loop Unroll Fixes

docker/ubuntu/20.04/cpu_ispc_build/Dockerfile, docker/ubuntu/22.04/cpu_ispc_build/Dockerfile
Fix for https://github.com/ispc/ispc/issues/2408
=> Removed duplicated deps from Ubuntu Dockerfiles

.github/workflows/copyright-check.yml, check_copyright.sh
To use run with any git ref as argument, e.g.:
```bash
$ ./check_copyright.sh HEAD^
```
=> Add check_copyright.sh script

ispcrt/cmake/ispc.cmake
Introduce CMake variables `ISPC_X86_ENABLED`, `ISPC_ARM_ENABLED`, `ISPC_XE_ENABLED` to ispc.cmake to detect what targets are supported. It's needed in is ispc.cmake to check if x86 targets are enabled, otherwise the build is failing. These variables may be also beneficial in user's apps.
=> Detect supported ISPC architectures in ispc.cmake

builtins/target-avx-utils.ll, builtins/target-avx512-utils.ll, builtins/target-sse4-common.ll, builtins/util.m4
Use it to portably select greater than ninth argument.
=> builtins: add argn macro

docker/ubuntu/20.04/cpu_ispc_build/Dockerfile, docker/ubuntu/20.04/xpu_ispc_build/Dockerfile
Changes:
*   Update dependency versions for Ubuntu 20.04.
| `docker/ubuntu/20.04/cpu_ispc_build/Dockerfile`,
| `docker/ubuntu/20.04/xpu_ispc_build/Dockerfile`
=> docker: Update Ubuntu Dependencies

ispcrt/cmake/interop.cmake
With latest DPC++ we always need to run sycl-post-link command on bitcode extracted from SYCL.
=> Use sycl-post-link to produce SYCL SPIR-V

src/func.cpp, src/module.cpp, tests/lit-tests/frame-pointers.ispc
Fixes #2473.
Note sure how to write good lit test to check that it actually works.
=> Use correct attribute to retain frame pointers

examples/xpu/README.md, examples/xpu/TestLists.txt, examples/xpu/invoke-sycl-aobench/CMakeLists.txt, examples/xpu/invoke-sycl-aobench/ao.isph, examples/xpu/invoke-sycl-aobench/ao_sycl_kernel.inl, examples/xpu/invoke-sycl-aobench/aobench_stub.ih, examples/xpu/invoke-sycl-aobench/invoke_sycl_aobench.cpp, fail_db.txt, ispcrt/cmake/Findlevel_zero.cmake
- aobench benchmark for perf comparison between SYCL and ISPC.
- add x86_64 lib path for L0 loader
=> Updates for Xe targets (18)

ispcrt/CMakeLists.txt
=> Fix ispcrt rpath on MacOS

tests/lit-tests/1498_unroll.ispc, tests/lit-tests/1678_unroll.ispc
Two more lit tests for the loop unrolling issues fixed by #2521.
=> Added lit-tests for loop-unroll issues: #1498 and #1678

.github/workflows/sanitizers.yml, src/ctx.cpp, src/func.cpp, src/func.h, src/parse.yy, src/sym.cpp
This change allows to enable ASAN for lit_tests and run_tests.
=> Fix memory leaks to enable ASAN for lit_tests and run_tests

tests/lit-tests/2468.ispc
Closes #2468.
The original issue was fixed by #2521.
=> Added 2468.ispc lit test

src/main.cpp
=> Remove CWD from the search path for dbghelp.dll

docker/README.md, docker/ubuntu/18.04/cpu_ispc_build/Dockerfile, docker/v1.21.0/ubuntu18.04/Dockerfile
With this changes this Dockerfile can be used for release build on aarch64.
=> Build cross compiler and package in Ubuntu 18 Docker

tests/lit-tests/1071.ispc, tests/lit-tests/1197.ispc, tests/lit-tests/1238.ispc, tests/lit-tests/1248.ispc, tests/lit-tests/1633.ispc, tests/lit-tests/301.ispc, tests/lit-tests/397.ispc, tests/lit-tests/491.ispc, tests/lit-tests/722.ispc, tests/lit-tests/750.ispc, tests/lit-tests/882.ispc, tests/lit-tests/895.ispc, tests/lit-tests/905.ispc
This PR adds several tests for issues that had been fixed in previous releases but issues have been opened until now.
=> tests: add regression tests for issues fixed in the past

CMakeLists.txt
=> Fix CURSES_LIBRARY usage in CMakeLists.txt

src/module.cpp, tests/lit-tests/2650.ispc
=> Emit struct keyword for vectors to C/C++ header

.github/workflows/linux-benchmarks.yml, .github/workflows/scripts/install-build-deps.sh
Requires https://github.com/ispc/ispc/issues/2666.
=> Llvm benchmarks 16

.github/workflows/ispc-ci.yml, .github/workflows/scripts/install-build-deps.sh, .github/workflows/scripts/install-test-deps.sh
This PR add jobs to build XE_ENABLED ISPC on Linux and Windows.
=> CI: add job to build XE_ENABLED build

docker/README.md, docker/centos/7/xpu_ispc_build/Dockerfile
This PR updates docker README and add the patch that saves built ISPC package.
=> Small docker fixes

src/ispc.cpp, src/stmt.cpp, tests/lit-tests/intrinsic_target_specific.ispc
This PR fixes small spelling error in messages which appears in the ispc binary.
=> Fix spelling errors.

src/ctx.cpp, tests/lit-tests/2272.ispc, tests/lit-tests/2272_2.ispc, tests/lit-tests/2272_3.ispc
=> Switch bool types when gathering bools into collections

superbuild/osPresets.json
This PR updates dependencies:
- SPIRV-LLVM Translator
=> Updates for Xe targets (24)

.github/workflows/ispc-ci.yml, .github/workflows/scripts/install-build-deps.ps1
Android NDK path is needed to run macOS job.
=> CI: add LTO jobs with LLVM 16

src/target_enums.cpp, src/target_registry.cpp
This PR fixes two copy-paste errors target registry related code.
=> Fix copy paste errors

src/opt.cpp
It makes sense to dump the whole IR modules when `--dump-file=<dir>` provided. It is reasonable assumption that one may want to pass them into `opt` to analyze some issues.
=> Dump the whole module with --dump-file

src/expr.cpp, tests/lit-tests/2517.ispc
=> Treat enum values as uints in constant folding on ast

src/ispc.cpp, tests/lit-tests/1253.ispc
=> Fix CPU for sse2-i32x8 target

docs/ispc_for_xe.rst, ispcrt/detail/gpu/GPUDevice.cpp
=> ispcrt: support multiple drivers

docker/ubuntu/22.04/xpu_ispc_build/Dockerfile, docker/v1.23.0/centos7/Dockerfile, docker/v1.23.0/centos7/oneAPI.repo, docker/v1.23.0/ubuntu18.04/Dockerfile
Added/updated Dockerfiles for v1.23.0 release
=> Added Dockerfiles for v1.23.0 release

src/ctx.cpp, tests/lit-tests/2754.ispc
Fix ISPC build after https://github.com/llvm/llvm-project/commit/9997e0397156ff7e01aecbd17bdeb7bfe5fb15b0
=> Fix build with LLVM trunk

src/opt.cpp
=> Fix memorySSA enablement under debugPM

.github/workflows/ispc-ci.yml
This PR merges build and test ISPC jobs with different LLVM version into matrix jobs with corresponding parameters. It reduces the amount of copy-paste in workflow.
=> Refactor build and test CI jobs

docs/design/templates.rst, docs/ispc.rst, src/expr.cpp, src/func.cpp, src/func.h, src/parse.yy, tests/lit-tests/func_template_nontype_1.ispc, tests/lit-tests/func_template_nontype_2.ispc, tests/lit-tests/func_template_nontype_3.ispc, tests/lit-tests/func_template_nontype_4.ispc, tests/lit-tests/func_template_nontype_5.ispc, tests/lit-tests/func_template_nontype_6.ispc, tests/lit-tests/func_template_nontype_7.ispc, tests/lit-tests/func_template_nontype_8.ispc, tests/lit-tests/func_template_nontype_9.ispc, tests/lit-tests/func_template_not_supported.ispc
This PR requires https://github.com/ispc/ispc/pull/2789.
Introduces support of integral and enum template parameters.
The docs will be added after initial review.
=> Support of integral and enum template parameters.

.github/workflows/ispc-ci.yml, src/builtins.cpp, src/ctx.cpp, src/ctx.h, src/expr.cpp, src/func.cpp, src/llvmutil.cpp, src/module.cpp, src/opt/CheckIRForXeTarget.h, src/opt/GatherCoalescePass.h, src/opt/ISPCPasses.h, src/opt/ImproveMemoryOps.h, src/opt/InstructionSimplify.h, src/opt/IntrinsicsOptPass.h, src/opt/IsCompileTimeConstant.h, src/opt/MakeInternalFuncsStatic.h, src/opt/MangleOpenCLBuiltins.h, src/opt/PeepholePass.h, src/opt/ReplacePseudoMemoryOps.h, src/opt/ReplaceStdlibShiftPass.h, src/opt/XeGatherCoalescePass.h, src/opt/XeReplaceLLVMIntrinsics.h, src/sym.cpp, src/sym.h, tests/lit-tests/err-enum-type.ispc
This PS deletes a few functions that are not used in the project. It also deletes most of `#if 0` code (either debug or commented out since the beginning).
It also updates upload actions that left unupdated since https://github.com/ispc/ispc/pull/2820
=> A small clean up

src/module.cpp, stdlib.ispc, tests/lit-tests/num-limits.ispc
=> Add user-visible definitions of numeric limits

src/ispc.cpp, src/main.cpp, src/module.cpp, src/util.cpp, src/util.h, tests/lit-tests/2856.ispc
=> Fix path processing

docker/ubuntu/18.04/cpu_ispc_build/Dockerfile, docker/ubuntu/22.04/xpu_ispc_build/Dockerfile, docker/v1.22.0/centos7/Dockerfile, docker/v1.22.0/ubuntu18.04/Dockerfile, docker/v1.23.0/centos7/Dockerfile, docker/v1.23.0/ubuntu18.04/Dockerfile, docker/v1.24.0/centos7/Dockerfile, docker/v1.24.0/centos7/oneAPI.repo, docker/v1.24.0/ubuntu18.04/Dockerfile, docs/ReleaseNotes.txt, docs/ispc.rst
This PR updates docs, release notes and Dockerfiles for the upcoming ISPC release v1.24.0.
=> Update for release v1.24.0

.github/workflows/compiler-warnings.yml, .github/workflows/sanitizers.yml, .github/workflows/scripts/install-build-deps.sh, tests/lit-tests/check_dispatch.c, tests/lit-tests/check_dispatch.ispc, tests/lit-tests/dispatch.ispc
This PR fixes fix `check_dispatch` test and add a new one `dispath.ispc`.
This also installs SDE for build jobs to run these tests.
=> Add lit-test for the dispatcher

src/opt/ImproveMemoryOps.cpp, src/opt/ReplaceMaskedMemOps.cpp, src/opt/ReplacePseudoMemoryOps.cpp
=> src/opt: include unordered_map

docker/ubuntu/16.04/cpu_ispc_build/Dockerfile, docker/ubuntu/18.04/cpu_ispc_build/Dockerfile, tests/lit-tests/func_template_nontype_3.ispc
This fixes #2877 and disables test from #2852
=> Fix docker dependencies

.github/workflows/linux-nightly-trunk.yml, .github/workflows/nightly-17.yml, docker/ubuntu/16.04/cpu_ispc_build/Dockerfile, docker/ubuntu/18.04/cpu_ispc_build/Dockerfile
Fix and re-enable nightly builds.
The change to them is needed after https://github.com/ispc/ispc/pull/2848
=> Fix nightly builds

.github/workflows/yarpgen.yml, docker/centos/7/cpu_ispc_build/Dockerfile, docker/centos/8/cpu_ispc_build/Dockerfile
Workflow to run Yarpgen. 
The timeouts for scheduled runs will be adjusted as soon as we fix current findings. Currently it is 240 minutes.
=> ci: added yarpgen workflow

docs/perfguide.rst
Fixes https://github.com/ispc/ispc/issues/2945
=> perfguide: fix iteration space for foreach

src/opt.cpp, tests/lit-tests/2954.ispc, tests/lit-tests/blend-curves-loop.ispc
This fixes #2954 extra moves issue.
=> Enable NewGVN for CPU also

src/decl.cpp, src/expr.cpp, src/ispc.cpp, src/llvmutil.cpp, src/main.cpp, src/module.cpp, src/opt/ImproveMemoryOps.cpp
This PR fixes a few warnings including 3 recent ones and 4 old ones.
=> Fix static analysis warnings

.github/dependabot.yml, .github/workflows/bandit.yml, .github/workflows/cve-bin-releases.yml, .github/workflows/cve-bin.yml, .github/workflows/third-party/requirements.txt
Fixes #2978 and https://github.com/ispc/ispc/issues/2980
=> ci: added dependabot configuration

.github/workflows/bandit.yml, .github/workflows/dll-inject-release.yml, .github/workflows/dll-inject.yml, .github/workflows/scripts/check-dll-injection.py
Fixes https://github.com/ispc/ispc/issues/2999.
Example workflows:
trunc: https://github.com/aneshlya/ispc/actions/runs/10962931653/job/30443305086 (passed)
v1.24.0: https://github.com/aneshlya/ispc/actions/runs/10963689254/job/30445675459 (passed)
v1.20.0: https://github.com/aneshlya/ispc/actions/runs/10963691256/job/30445682219 (failed)
=> GA to test DLL injection

src/decl.cpp, src/decl.h, src/expr.cpp, src/parse.yy, src/stmt.cpp, src/type.cpp, src/type.h, tests/lit-tests/func_template_array_1.ispc, tests/lit-tests/func_template_array_2.ispc, tests/lit-tests/func_template_array_3.ispc, tests/lit-tests/func_template_array_4.ispc, tests/lit-tests/func_template_array_5.ispc, tests/lit-tests/func_template_array_6.ispc, tests/lit-tests/func_template_array_7.ispc, tests/lit-tests/func_template_array_8.ispc, tests/lit-tests/func_template_array_9.ispc, tests/lit-tests/func_template_nontype_9.ispc
This is continuation of non-type template parameters support. This PR adds support of template parameters in arrays.
Related to #2522 and https://github.com/ispc/ispc/issues/2737
=> Support non-type template parameters in arrays

src/expr.cpp, src/expr.h, tests/lit-tests/2661.ispc
Fixes https://github.com/ispc/ispc/issues/2661.
=> Fix incorrect template argument variability (#2661)

llvm_patches/18_1_19_1_x86ISel-fix-combineMul.patch
Port of https://github.com/llvm/llvm-project/commit/9459d729d22b7bfedad9d3a4237162077c6984a4
=> Added LLVM patch with fix to #3041

cmake/Stdlib.cmake
=> Fix FreeBSD build

src/module.cpp, tests/lit-tests/3066.ispc
This should fix deps file generation for ISPC windows binary.
This PR fixes #3066
=> Fix deps file generation 2

src/module.cpp, tests/lit-tests/3086.ispc
=> Check the size of global initializer list (#3086)

src/opt/ReplaceMaskedMemOps.cpp, tests/lit-tests/1323_1.ispc, tests/lit-tests/2738_one_init.ispc, tests/lit-tests/2954.ispc, tests/lit-tests/avx512spr-i32x8.ispc, tests/lit-tests/bool-casts-vectors.ispc, tests/lit-tests/bool-store-varying.ispc, tests/lit-tests/cpus_x86_llvm14.ispc, tests/lit-tests/disable_gather_scatter.ispc, tests/lit-tests/float16_varying.ispc, tests/lit-tests/fp16_code_gen.ispc, tests/lit-tests/func_template_array_5.ispc, tests/lit-tests/func_template_nontype_1.ispc, tests/lit-tests/func_template_nontype_5.ispc, tests/lit-tests/interleaved.ispc, tests/lit-tests/ispc-opt.ll, tests/lit-tests/lit.cfg, tests/lit-tests/load_store_vectorizer_loopunroll.ispc, tests/lit-tests/perf-warnings.ispc, tests/lit-tests/target_x86_macos_no_spr.ispc, tests/lit-tests/targets_x86_llvm14plus.ispc
1. Replace getPointerTo with PointerType::get
2. Update lit tests
=> Fix trunk build

docs/ispc.rst, src/parse.yy, tests/lit-tests/func_template_nontype_10.ispc
=> Support bool non-type template parameter

.github/workflows/ispc-ci.yml, .github/workflows/ispc-svml.yml, .github/workflows/linux-nightly-trunk.yml, .github/workflows/nightly-19.yml, .github/workflows/sanitizers.yml, .github/workflows/scripts/install-svml-test-deps.sh, .github/workflows/scripts/install-test-deps.ps1, .github/workflows/scripts/install-test-deps.sh, .github/workflows/slim-binary.yml, .github/workflows/yarpgen.yml
Fixes #3103.
Currently is being tested: 
https://github.com/ispc/ispc/actions/runs/11806913030
https://github.com/ispc/ispc/actions/runs/11806917945
=> Fix for SDE download in CI

CMakeLists.txt
=> CMake: enable /DEPENDENTLOADFLAG

src/parse.yy, tests/lit-tests/func_template_shortvec_10.ispc
=> Fixed short vector casts inside template

docs/ispc.rst, src/main.cpp, tests/lit-tests/3150.ispc, tests/lit-tests/3150_1.ispc
This PR partially addresses #3150
=> Deprecate --nocpp command line flag

builtins/target-neon-common.ll, builtins/target-neon-i32x4.ll, builtins/target-neon-i32x8.ll, builtins/util.m4, docs/ispc.rst, src/builtins.cpp, src/ispc.cpp, src/ispc.h, src/module.cpp, stdlib/include/builtins.isph, stdlib/include/core.isph, stdlib/include/stdlib.isph, stdlib/stdlib.ispc, tests/func-tests/dot4add_i8i8-1.ispc, tests/func-tests/dot4add_i8i8-2.ispc, tests/func-tests/dot4add_i8i8-sat-1.ispc, tests/func-tests/dot4add_i8i8-sat-2.ispc, tests/func-tests/dot4add_u8u8-1.ispc, tests/func-tests/dot4add_u8u8-sat-1.ispc, tests/lit-tests/aarch64_dotprod.ispc, tests/lit-tests/arm_dotprod.ispc
Fixes https://github.com/ispc/ispc/issues/2951
=> Dot product on ARM

src/opt.cpp, tests/lit-tests/ispc-intrinsics.ispc
=> Enable lower ispc intrinsics pass

examples/cpu/cmake/AddISPCExampleLegacy.cmake, examples/cpu/gmres/CMakeLists.txt, ispcrt/cmake/ispc.cmake, src/opt/XeGatherCoalescePass.cpp, src/opt/XeReplaceLLVMIntrinsics.cpp
=> Fix XE_ENABLED build with LLVM 19

tests/lit-tests/3084-1.ispc
This fixes https://github.com/ispc/ispc/pull/3166#issuecomment-2587745463
=> Fix 3084-1 for LLVM trunk

.github/workflows/pre-release-artifacts.yml
Fixes https://github.com/ispc/ispc/security/code-scanning/97
=> CI: set top-level read permissions in pre-release-artifacts.yml

docs/ReleaseNotes.txt
=> Release Notes for v1.26.0

.github/workflows/rebuild-llvm17.yml, .github/workflows/rebuild-llvm18.yml, .github/workflows/rebuild-llvm19.yml, .github/workflows/rebuild-llvm20.yml, .github/workflows/reusable.rebuild.yml
=> Fix concurrency groups for LLVM rebuild jobs

.github/workflows/snap.yml
This PR fixes #3222. Switching to a public ARM runner fixes the issue. I also refactored this workflow to use a single matrix job.
I have published the last snap release for ARM using this job here https://github.com/ispc/ispc/actions/runs/13266329139.
=> Fix snap aarch64 job

src/expr.cpp, src/func.cpp, src/func.h, src/type.cpp, src/type.h, tests/lit-tests/3229.ispc, tests/lit-tests/template_argument_deduction10.ispc, tests/lit-tests/template_argument_deduction11.ispc, tests/lit-tests/template_argument_deduction12.ispc, tests/lit-tests/template_argument_deduction7.ispc, tests/lit-tests/template_argument_deduction8.ispc, tests/lit-tests/template_argument_deduction9.ispc
=> Support argument deduction for short vector in templates

src/expr.cpp, tests/lit-tests/2285.ispc
=> Permit smearing for uniform Enum values

.github/workflows/cve-bin-releases.yml, .github/workflows/hardening-check-release.yml, .github/workflows/ispc-ci.yml, .github/workflows/reusable.ispc.test.yml, .github/workflows/rk-superbuild-release.yml, .github/workflows/yarpgen.yml
Tests run: https://github.com/ispc/ispc/actions/runs/13531551449
Fixes #3248 , #3249
=> Add LLVM 19 to full ISPC testing + minor CI fixes in release workflows

.github/workflows/ispc-ci.yml, .github/workflows/linux-nightly-trunk.yml, .github/workflows/nightly-19.yml, .github/workflows/nightly-next.yml, src/ispc.cpp, tests/lit-tests/3126.ispc
Full run Nightly 20.1: https://github.com/ispc/ispc/actions/runs/13823493858
Full run Nightly trunk: https://github.com/ispc/ispc/actions/runs/13844876180
=> Fix nightly 19 and trunk workflows

src/module.cpp, src/module.h, src/parse.yy, src/stmt.cpp
This PR fixes warnings produced by static analysis tools after #3274 and #3283
=> Fix warnings

src/parse.yy, tests/lit-tests/ptr-assign-inst.ispc
This implements https://github.com/ispc/ispc/issues/3253
=> Support instantiation of template function on pointer assignment

CMakeLists.txt, builtins/dispatch.c, cmake/GenerateBuiltins.cmake, src/isa.h, src/ispc.cpp, src/ispc.h, src/module.cpp, tools/check_isa.cpp
=> Check ISA consolidation

contrib/ispc.vim.README
Add documentation for distribution packagers how to globally install.
=> Also highlight header files.

src/ast.cpp, src/ctx.cpp, src/decl.cpp, src/expr.cpp, src/func.cpp, src/module.cpp, src/parse.yy, src/type.cpp, src/type.h
This PR adds alignment field to Type. This is needed to implement #2145
=> Refactor types and add alignment to them

.github/workflows/ispc-ci.yml, .github/workflows/reusable.ispc.build.yml, .github/workflows/reusable.ispc.test.yml, .github/workflows/scripts/install-build-deps.sh, .github/workflows/scripts/install-test-deps.sh
This PR introduces reusable workflow for ISPC build on different platforms similar to reusable.ispc.test introduced in https://github.com/ispc/ispc/pull/3250
Full run is here: https://github.com/ispc/ispc/actions/runs/14181517913
=> Reusable workflow for ISPC build

.github/workflows/nightly-next.yml
Full run is here: https://github.com/ispc/ispc/actions/runs/14345758419
=> Enable AVX10.2 targets in testing with LLVM 20

.github/workflows/hardening-check-release.yml, .github/workflows/hardening-check.yml, tests/func-tests/fmod-double-varying-2.ispc, tests/func-tests/round-double-uniform.ispc, tests/func-tests/round-double-varying.ispc, tests/func-tests/test-149.ispc, tests/func-tests/test-150.ispc
- Fix hardening check workflow: https://github.com/ispc/ispc/actions/runs/14367775288/job/40284675177
- Reorder skipping rules in some tests to skip them on GPUs.
=> Fix skipping tests and fix hardening check workflow

.github/workflows/ispc-ci.yml, .github/workflows/reusable.ispc.test.yml, .github/workflows/scripts/load-vs-env.ps1
Github recently added support of Windows ARM runners. This PR adds testing on Windows ARM and slightly refactors reusable test workflow.
Full run is here: https://github.com/ispc/ispc/actions/runs/14581259840
=> Add testing on Windows ARM runners

src/module.cpp
This reflects upstream LLVM change in Commit 985410f
=> Fix build with trunk LLVM

src/expr.cpp, tests/lit-tests/2825-1.ispc, tests/lit-tests/2825-2.ispc, tests/lit-tests/3354.ispc
=> Fix nested template without arguments

src/module.cpp
This reflects the change in LLVM commit 13e1a2cb2246
=> Fix build with the trunk LLVM

.github/workflows/clang-tidy.yml, .github/workflows/compiler-warnings.yml, .github/workflows/coverity.yml, .github/workflows/format-check.yml, .github/workflows/ispc-ci.yml, .github/workflows/ispc-svml.yml, .github/workflows/ispcrt.yml, .github/workflows/linux-nightly-trunk.yml, .github/workflows/nightly-next.yml, .github/workflows/pre-release-artifacts.yml, .github/workflows/reusable.ispc.build.yml, .github/workflows/reusable.ispc.test.yml, .github/workflows/rk-superbuild.yml, .github/workflows/sanitizers.yml, .github/workflows/scripts/init-env.ps1, .github/workflows/scripts/init-env.sh, .github/workflows/scripts/install-build-deps.ps1, .github/workflows/scripts/install-build-deps.sh, .github/workflows/scripts/install-svml-test-deps.sh, .github/workflows/scripts/install-test-deps.ps1, .github/workflows/scripts/install-test-deps.sh, .github/workflows/slim-binary.yml, .github/workflows/yarpgen.yml
Reduce boilerplate environment variable initialization across CI
=> Reduce boilerplate environment variable initialization across CI

.github/workflows/ispc-ci.yml, .github/workflows/reusable.ispc.test.yml
This PR includes tests for some ISPC command flags that are not currently being tested.
=> CI: add tests run with different ISPC options

src/main.cpp
- Extracted command-line argument parsing logic into a new function `ParseCommandLineArgs`, simplifying the `main` function 
- Replaced `exit()` calls with a new `ArgsParseResult` enum.
Based on https://github.com/ispc/ispc/pull/3452 and required for further refactoring for support of ISPC as a library.
=> Extract compiler options parsing from main()

docs/ispc.rst
This PR is only about documentation.
It add missing news in the changelog (addressed by recent past PR) and also updates the table mentioning all targets (add missing targets, bold table header, add information about AMD CPUs, add more precision about Intel one, cleaner/better-structured information).
=> Improve the doc and update the changelog

benchmarks/04_intrinsics/02_sse2_intrinsics.cpp, tests/func-tests/select-short-vec.ispc, tests/lit-tests/func_template_operator_1.ispc
=> Fix couple of issues found in internal testing

.github/workflows/scripts/init-env.ps1, .github/workflows/scripts/init-env.sh, tests/func-tests/srgb8-uniform.ispc, tests/func-tests/srgb8-varying.ispc
Update SDE version in CI. Nightly run is here: https://github.com/ispc/ispc/actions/runs/16760878362
=> Update SDE to 9.58.0 version

README.md, docker/v1.28.0/Dockerfile, docs/ReleaseNotes.txt, docs/ispc.rst, examples/cpu/README.txt
Release notes, docs updates and docker for upcoming release.
=> Update for v1.28.0 release
