- Makefile
- type.cpp
All example/portables are compilable now, and no new fails are introduces with CUDA7.
> Change name mangling to support for NVVM in CUDA7.

- ispc.cpp
It`s necessary to pass the result by reference instead of creating a new object: otherwise, its data might be used beyond the point of its disposal.
> Fixed CPU name retrieval

- examples/intrinsics/knc.h
Codegenerator sometimes creates __unordered_*_and_mask functions.
> New unordered function

- builtins/dispatch.ll
- builtins/svml.m4
- builtins/target-avx-common.ll
- builtins/target-avx-x2.ll
- builtins/target-avx.ll
- builtins/target-avx1-i64x4base.ll
- builtins/target-generic-1.ll
- builtins/target-generic-common.ll
- builtins/target-neon-common.ll
- builtins/target-nvptx.ll
- builtins/target-sse2-common.ll
- builtins/target-sse2-x2.ll
- builtins/target-sse2.ll
- builtins/target-sse4-16.ll
- builtins/target-sse4-8.ll
- builtins/target-sse4-common.ll
- builtins/target-sse4-x2.ll
- builtins/target-sse4.ll
- builtins/util-nvptx.m4
- builtins/util.m4
- module.cpp
- opt.cpp
New LLVM IR for getelementptr instruction (https://github.com/llvm-mirror/llvm/commit/198d8baafbfdfcf5a5e219602a5d94ed263973b4) and load instruction (https://github.com/llvm-mirror/llvm/commit/7c9c6ed761bf9d28c0c257a045b35781969136e0). DataLayoutPass became obsolete (https://github.com/llvm-mirror/llvm/commit/c94da20917cb4dfa750903b366c920210c5265ee)
> Fix for trunk

- examples/intrinsics/knc.h
This fixes './tests/half-3.ispc' compfail on LLVM trunk
> Added '__ordered_float_and_mask' function to 'knc.h'

- alloy.py
- ispc.sln
- ispc.vcxproj
LLVM dropped MSVC pre-2013 compatibility, so its headers now require 2013+ to compile.
> Windows build fix

- ConstantsScanner.h
- cbackend.cpp
Header ConstantsScanner.h was removed from LLVM, so we need to have our own for cbackend.cpp (https://github.com/llvm-mirror/llvm/commit/bf71e29ec5008c9ac9abc264a4fc405b99b91e23)
> Fix for revision

- ispc.cpp
If you want to have 'CPU_None' as CPU type, than you have to have a name for it (even if that's an empty string)
> Fix assertion fail when specify illegal/unsupported target to ISPC

- builtins/target-neon-16.ll
- builtins/target-neon-32.ll
- builtins/target-neon-8.ll
- examples/timing.h
ISPC and examples are now can be build on ARM. When using IPSC on arm it reports:
Warning: Module DataLayout is incompatible with library DataLayout: 
Module DL: e-p:32:32:32-S64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f16:16:16-f32:32:32-f64:64:64-f128:128:128-v64:64:64-v128:64:128-a0:0:64-n32 
Library DL: e-p:32:32:32-S32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f16:16:16-f32:32:32-f64:32:64-f128:128:128-v64:32:64-v128:32:128-a0:0:64-n32
> Added fix for ispc on ARM

- module.cpp
- module.h
- type.cpp
Reverts ispc/ispc#1019
Clean solution doesn't work in the cases when we have struct forward decl... So reverting.
> Revert "Multitaget function return types fixed"

- expr.cpp
ptr1 - ptr2 should ignore const.
> Ptr Diff should ignore const

- ctx.cpp
String arguments supplied to user-defined external functions such as `ISPCInstrument()` were missing the null-terminator.
> Fixed string argument missing null-terminator.

- examples/intrinsics/knl.h
It is necessary for knl-generic-x16 in multitarget.
> Replace static const variables in knl.h

- module.cpp
Fix for the bug, which crashed ispc during object file write (showed up on MacOS and Windows with LLVM trunk).
> Fix for the bug, which crashed ispc during object file write.

- alloy.py
- Apparently the uninitialized compiler_exe var was set to 'icpc' on 3.4 knl testing and remained so on 3.5, 3.6 and 3.7 producing errors (mostly because of icpc's internal errors). Now the default compiler (clang, if available) will be used again with non-knc/knl targets.
> Fix unitialized default compiler_exe

- alloy.py
- 'run_tests.py' does not recognize ' ' as a request to automatically choose a compiler. It should be 'None' instead
> Fixed default compiler value from ' ' to None

- func.cpp
Fix name-mangling for metadata when built with NVPTX
> ptx build fix

- alloy.py
- builtins/dispatch.ll
- builtins/util.m4
- ispc.h
- ispc_version.h
Added LLVM 3.7 version in alloy.py with temporary repository + some additional changes for compiling trunk 3.8.
> Trunk38 fixes

- builtins.cpp
- builtins/target-knl.ll
- The IR has changed significantly since LLVM 3.7. However, AVX-512 target is supported only with 3.7 and older, so there is no need to build it against old LLVM versions
> Fixed AVX-512 IR incompatibility issue

- opt.cpp
all functions from llvm::initializeIPA() already included in the function llvm::initializeAnalysis()
> trunk 3.8 fix

- module.cpp
Fix issues with LLVM 3.7 and trunk on MacOS when building for multiple targets.
> Set target tripple and data layout for dispatch module.

- builtins/target-avx-x2.ll
- builtins/target-avx.ll
- builtins/target-avx1-i64x4base.ll
- builtins/util.m4
LLVM git mirror: [link](https://github.com/llvm-mirror/llvm/commit/eb09365c843560601b374d4de7322fd2b05611f5)
> IR change for x86 mask load/store instructions in LLVM 3.8 (r250817)

- llvm_patches/3_7_r251275-AVX-512-not-materializable-instructions.patch
Apply R251275 on LLVM 3.7 to fix https://llvm.org/bugs/show_bug.cgi?id=25270
> Apply R251275 on 3.7

- opt.cpp
The old pass was being really dumb with a few simple examples.  The "new" hotness of the SROA pass produces better code for these cases.
We probably should've changed this a year ago. ;)
> Replace old ScalarReplAggregates pass with no longer new SROA pass.

- cbackend.cpp
"I.hasStructRetAttr()" will throw an assertion, if "I" has zero arguments.
> Fix bug in cbackend

- ispc.cpp
Added default target --target=host which help to avoid warning like this: 
Warning: No --target specified on command-line. Using default system target "avx1-i32x8".
> Fix issue #1122

- cbackend.cpp
Link to commit: https://github.com/llvm-mirror/llvm/commit/0317b8efaff0addbf14d66583f37483c65e3f7f2
> Fix fabs intrinsic in generic target (fail after LLVM r249702)

- ispc.cpp
I moved strcasecmp on isa to _after_ comparing isa against NULL.
> Fix crash when not specifying --target option

- ispc.cpp
- ispc.h
- main.cpp
- module.cpp
LLVM omits frame pointer by default. New option was added to disable it. (see #1137)
> Add --no-omit-frame-pointer option.

- fail_db.txt
tracked in https://llvm.org/bugs/show_bug.cgi?id=26338
> Remove passes compfails; Black out avx-512 gather/scatter llc fails

- Makefile
- alloy.py
Fixing Makefile to support LLVM builds with -DNDEBUG (default with cmake).
Also adding LLVM_ENABLE_ASSERTIONS=ON to build, as well as list of target to build (x86 and nvptx).
> improvements in cmake build support

- ctx.cpp
- ctx.h
- expr.cpp
- tests/struct-test-126.ispc
- tests/struct-test-127.ispc
According to https://ispc.github.io/ispc.html#struct-types, uniform field of varying struct is still uniform, so we don't need cast it to varying. (#1164)
> Fix cast from uniform struct to varying struct.

- stmt.cpp
- tests/foreach-32.ispc
This basic block runs only on the last step. Therefore, this check during mask calculation is not very expensive.
> Fixed the last useless step in foreach_tiled in some cases

- module.cpp
When compiling with `--instrument` the declaration for ISPCInstrument is not valid C and thus can't be included in a C program since `extern "C"` is not in C. The fix in this PR wraps the `extern "C"` in the same `#if`'s that are used for the `extern "C"` statement on the exported ISPC functions:
```c++
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
extern "C" {
#endif // __cplusplus
void ISPCInstrument(const char *fn, const char *note, int line, uint64_t mask);
#if defined(__cplusplus) && (! defined(__ISPC_NO_EXTERN_C) || !__ISPC_NO_EXTERN_C )
} /* end extern C */
#endif // __cplusplus
```
I noticed this function is written in two places, `Module::writeHeader` and `Module::writeDispatchHeader`, but I'm not sure what the different headers being written …
> Fix C compatibility of ISPCInstrument declaration in export header

- ispc.cpp
Now it requires Optional<Reloc::Model> instead of just Reloc::Model.
> Fix for LLVM trunk - TargetMachine interface has changed.

- builtins.cpp
- builtins/target-avx512-common.ll
- ispc.cpp
- lex.ll
Switching AVX-512 implementation to use i8x32 mask instead of i1x32 to be able to address elements of varying bool in memory.
> Knl int8 mask

- builtins/target-neon-16.ll
- builtins/target-neon-32.ll
- builtins/target-neon-8.ll
- builtins/target-neon-common.ll
As per the topic posted at https://groups.google.com/forum/#!topic/ispc-users/2AZ4ZLbAY9Q, manually audited every one of the ARM NEON LLVM builtins, adding alwaysinline to almost all of the items where missing (those I did not add to was because I could not see its implementation in these files) and adding readnone to any functions which do not read any state. Quality of ARM NEON generated by LLVM was substantially improved in my particular use case, stack spillage due to lack of scratch registers dropped by a massive 32 bytes and the code output looked much, much better though only a 2% performance improvement was actually found in practice.
I also implemented __fastmath() for ARM NEON. It's perhaps an excessively conservative implementation but it should be very portable across ARM …
> Fix ARM NEON output not always being inlined. Also improved scope for ARM NEON optimisation by LLVM, gained about 2% on my code here.

- builtins.cpp
- module.cpp
As per [rL286566](https://reviews.llvm.org/rL286566), utilities for Bitcode reading and writing reside in separate files
> Support llvm 4.0: Bitcode/ReaderWriter.h -> BitCode/BitcodeWriter.h

- alloy.py
- builtins/target-avx512-common.ll
For LLVM 3.9 we also stick with 3.9.0 as 3.9.1 has couple regressions.
> SVML support for AVX512 and a couple of script fixes

- examples/aobench/ao.ispc
- examples/aobench/ao_serial.cpp
- examples/aobench_instrumented/ao_instrumented.ispc
Hi,
The following change allows for non-deformed, non-square image output.
Before (1024x768):
After (1024x768):
Also (768x1024):
Regards,
-Colin
> ISPC AO example: fix for non-square output images

- Makefile
gcc-6.2.0 generates a couple of warnings when compiling ispc, so
allow to drop '-Werror' from the cxxflags. It is anyhow a bad idea
to enforce that flag as it is unclear what future compiler
versions will warn about.
Ref: https://bugs.gentoo.org/595254
> Makefile: allow dropping -Werror from cxxflags

- stdlib.ispc
Includes the patch hinted in #1198, for both the varying and uniform variant of `float_to_srgb8()`.
> Clamp to _almost_ zero in float_to_srgb8(), fixes #1198

- alloy.py
- cbackend.cpp
- llvm_patches/5_0_r317463_better_permute.patch
- module.cpp
Scripts:
- different ways to specify LLVM_ENABLE_DUMP for different versions
- Fix for macOS build. Drop system root switch and rely on C headers from Command Line Tools fo Xcode. Otherwise we have a problem building clang on macOS 10.12 with XCode 9.
LLVM trunk:
- tool_output_file -> ToolOutputFile
> Scripts and changes for LLVM trunk

- LICENSE.txt
- Makefile
- alloy.py
- builtins/dispatch.ll
- builtins/target-knl.ll
- builtins/target-skx.ll
- builtins/util-nvptx.m4
- builtins/util.m4
- docs/ispc.rst
- docs/perfguide.rst
- docs/template-news.txt
- docs/template-perf.txt
- docs/template.txt
- ispc.cpp
- ispc.h
- ispc_version.h
The changes of this commit are completely analogue to the changes
introduced in 6dc0ccc404c877531f06b42881272f15f4209b17 (aside from some additional 2017->2018 bumps)
Please note that there isn't a RELEASE_600 tag on llvm.org yet (see
https://llvm.org/svn/llvm-project/llvm/tags/). Therefore, the change in
alloy.py is a bit ahead of time as of now.
> Patches for llvm 7.0 support

- module.cpp
`WriteBitcodeToFile` now takes the module by reference instead of by pointer.
Phabricator: https://reviews.llvm.org/rL325155
GitHub: https://github.com/llvm-mirror/llvm/commit/06d6207c1c631716d4e6310246d198aa9e05c0d0
> [NFC] Fix for llvm upstream change 325155

- main.cpp
For reasons that I won't go into, I need to pass a large number of arguments to ISPC and the resulting command line can exceed the command-line length limit on Windows. Hence, I have implemented a patch to the command-line handling that allows some or all command-line arguments to be specified in a file.
This change takes the gcc format of `@<filename>`. If `<filename>` does not exist or cannot be opened, the argument is accepted as-is. The file (or `ISPC_ARGS`) is itself allowed to contain another `@<filename>` argument.
The content of the file is split into arguments in essentially the same way as was used for `ISPC_ARGS`. It does not (yet) support any method of escaping or quoting to allow white space within an argument. These arguments then replace the original `@<filename>`.
This …
> Allow command-line arguments to be passed in a file

- main.cpp
- module.cpp
- module.h
Hello there,
Here's a little change that I found useful in my own work.
This commit adds handling of commandline options `-M` and `-MF` in a way inspired by what GCC does (inspired, as in, the switch names and semantics have been borrowed from GCC).
`-M` generates a makefile-compatible target rule for the current output object (or the canonical `a.out`, if nothing is specified), and outputs it to `stdout`.
`-MF <filename>` puts the output in `<filename>` instead.
`-MT <target name>` allows overriding the name of the target in the rule generated by `-M`.
The functionality of `-MMM` remains unchanged, apart from the fact that a subsequent `-MF` may alter the filename.
In order to achieve this, a new bitflag type `Module::OutputFlags` is introduced. It replaces the `generatePIC` boolean and …
> Implement GCC-style makefile dependency rule generation

- stmt.cpp
- tests/empty-do-while.ispc
Hi there,
Apparently, the LLVM dynamic cast isn't protected against casting null pointers. The following code snippet crashes ISPC:
```
export void Kernel()
{
do {} while (false);
}
```
The fix is trivial - check if the pointer isn't null before attempting the cast.
This is on LLVM 6.0, I should mention.
> Fix crash when compiling an empty `do {} while (false)` loop

- src/ctx.cpp
> Fix to match LLVM trunk change for createFunction() signature.

- src/ctx.cpp
- src/ispc.cpp
pentium4 does not support x86-64 which causes failure for
./ispc <ispc_file> --target=sse2-i32x4 --arch=x86-64
> Replace pentium4 with x86-64.

- llvm_patches/5_0_bug1381.patch
- llvm_patches/6_0_bug1381.patch
This patch is required to fix #1381.
Extend inputs with elements smaller than i32 to sint_to_fp/uint_to_fp
before type legalization. In this particular case extending
bool to 32 bits.
> Fix for #1381 : picked from the llvm commit r324820.

- .appveyor.yml
- .travis.yml
- CMakeLists.txt
Added option to link ISPC statically. Verified on different versions of fedora, ubuntu and centos.
Now when package is created, ISPC is built statically by default.
Also added build and run of check_isa utility.
> Static link

- src/util.cpp
1.  Prevent compilation failure with --werror for warnings which
the user choose to ignore using #pragma ignore warning.
2. Cause compilation to fail for performance warnings too
when using --werror
> Issue #1394 : Fix warnings

- fail_db.txt
Update for: #1430 (9.0/8.0 fails)
> Fail_db.txt update after LLVM bug 40891 fix in trunk

- fail_db.txt
9.0 fails update after https://reviews.llvm.org/D58805 fix.
#1430
> Fail_db.txt: 9.0 fixes

- src/main.cpp
Custom build systems on large projects send down many folders as includes. Increase number ISPC supports to 512 to support this.
> Increase number of input args supported to 512

- CMakeLists.txt
Security hardening link options are available only on Linux. macOS doesn't have analogs.
> Fixing macOS build

- CMakeLists.txt
- src/llvmutil.cpp
- src/llvmutil.h
- src/main.cpp
- src/module.cpp
- src/opt.cpp
- src/util.cpp
Adding a possibility to build with LLVM distribution, which doesn't have dump() functions enabled
> ISPC_NO_DUMPS

- cmake/GenerateBuiltins.cmake
It fixes the link error: "relocation R_X86_64_PC32 against symbol stdout@@GLIBC_2.2.5..."
> Fixed ospray build

- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/opt.cpp
1. Added --dump-file option to dump module IR to file after each pass (after doInitialization and runOnModule)
2. Added --debug-llvm option to turn on llvm debug info dumps
3. Fixed --debug-phase=first:last option interpretation
> Add dump-file and debug-llvm options

- builtins/builtins.c
- fail_db.txt
- src/ispc_version.h
- src/module.cpp
- tests/lit-tests/noinline.ispc
* update ISPC_MAJOR_VERSION and ISPC_MINOR_VERSION with version change
* change the version string to 1.12.0dev, as the next version is going to be 1.12.0
* fix noinline.ispc lit test on Mac
* update faildb for Windows
* add missing ifdef for __puts_nvptx()
> Set of minor changes

- src/expr.cpp
- tests/FNeg.ispc
There are 2 issues here-
1. We were not creating negative 0
2. Code was not optimal for certain fma scenarios-
A pattern like -c+a* b was not creating optimal code. We ended up creating additional assembly code to create 0 and subtract
xorps	%xmm1, %xmm1, %xmm1
vsubps	(%rcx), %ymm1, %ymm1
vfmadd231ps	(%rdx), %ymm0, %ymm1 # ymm1 = (ymm0 * mem) + ymm1
With change, this becomes
vmovups	(%rdx), %ymm1
vfmsub213ps	(%rcx), %ymm0, %ymm1 # ymm1 = (ymm0 * ymm1) - mem
See attached files for test case
[negTestFma.zip](https://github.com/ispc/ispc/files/3474545/negTestFma.zip)
> Fixing floating point negation

- .appveyor.yml
- CMakeLists.txt
- cmake/GenerateBuiltins.cmake
- common.py
- src/parse.yy
* Fix for macOS build: initialize SDK path by default
* Update parse.yy not to use depricated derictive
* No need to see warnings triggered by system includes
> Build fixs for macOS

- src/util.cpp
In order to point to the correct code snippet we have to treat tab
as space since during lexing when we calculate the original column number,
tab and spaces are both treated as same.
> Fix for #1493

- builtins/dispatch.ll
- src/ispc.h
- tests/lit-tests/1576.ispc
There doesn't seem to be any reason for us to set enum field values explicitly. Having the values set explicitly was causing a crash when iterating through enum with last value as upper limit since we removed AVX11.
> Fix for #1576.

- src/main.cpp
- src/util.h
- tests/lit-tests/arg_parsing_errors.ispc
Change the way errors are reported during arguments parsing.
* report all errors, but not only the first one
* Take into account --quiet, --nowrap, and --werror, even if they are
specified after the arrorneous argument
* do not print help message on every argument error
* add test for errors during argument parsing
> Argument parsing error reporting improvement

- llvm_patches/8_0_9_0_Fix_for_1595.patch
- tests/lit-tests/1595.ispc
Porting llvm fix to fix returning nested structs in IR during
constant propagation pass.
> Fix for #1595.

- cmake/GenerateBuiltins.cmake
- examples/tasksys.cpp
* Removing <sys/sysctl.h> from tasksys.cpp. It's deprecated in latest Linux (Ubuntu 19.10) and is not needed for current version of tasksys.cpp.
* Trigger build fail on build error during builtins.c compilation (fix for #1614 and #1612).
> Minor fixes

- src/main.cpp
- src/module.cpp
- src/util.cpp
- src/util.h
- tests/lit-tests/1588_stdin.ispc
- tests/lit-tests/arg_parsing_errors.ispc
- utils/lit/lit/builtin_commands/cat.py
Change the default behavior from reading from stdin (if input file is not specified on the command line) to require the input file. If it's required to read from stdin, user needs to pass "-" as input file.
What's included in this PR:
- changing default behavior
- adding tests
What's not included, but still required by #1588:
- handle Ctrl+C correctly on stdin on Windows.
> Fix for #1588: do not read from stdin by default.

- CMakeLists.txt
- alloy.py
- src/cbackend.cpp
- src/ctx.cpp
- src/ispc.h
- src/ispc_version.h
- src/main.cpp
- src/module.cpp
- src/opt.cpp
- src/type.cpp
Main Changes are-
1. Updated latest llvm version to 11.0
a. Since 10.0 has branched but released, using the temporary branch in alloy. Has to update this once 10.0 official release happens
2. LLVM moved openmp to a new library - frontendopenmp. Modified Cmake to add this
3. Changes in headers caused us to add some new headers
4. setjmp and longjmp deprecated and removed. From what I understand they have not been supported for a while now. Hence the complete removal.
5. BasicBlockPass removed in llvm. switched to FunctionPass
6. Alignment no longer use integer values. have to use llvm::MaybeAlign
> Fixing build for llvm trunk and 10.0.

- CMakeLists.txt
- cmake/LLVMConfig.cmake
* properly compare LLVM versions
* correctly detect LLVM build without asserts/dumps.
> CMake fixes

- src/main.cpp
> Adding <cstdarg> include to main.cpp, which is required for va_arg

- builtins/target-avx512-common-8.ll
- builtins/target-avx512-common.ll
- builtins/target-avx512-utils.ll
- src/ispc.cpp
- tests/lit-tests/1608.ispc
- tests/lit-tests/1609.ispc
Changing avx512 mask to i1 from i8.
i1 is a more natural mask size for avx512. By changing mask size to i1, we can skip constantly converting i8 to i1 for use in intrinsics.
> Fix for #1608/#1609.

- src/builtins.cpp
- src/cbackend.cpp
- src/ctx.cpp
- src/llvmutil.cpp
- src/opt.cpp
Fix after LLVM change requiring explicit conversion from StringRef to std::string
LLVM commit: llvm/llvm-project@777180a32b61
> Fix to match LLVM trunk

- src/expr.cpp
- src/expr.h
- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/module.cpp
- src/parse.yy
- src/stmt.cpp
- tests/1596.ispc
- tests/lit-tests/1596.ispc
This mostly has logic to identify compile time constants
which are global addresses and their variants.
Enables following initializations -
uniform int sz = sizeof(uniform int);
static uniform float a = 1.0;
static uniform float * uniform pa = &a;
static const uniform float * uniform parr[] = {NULL, &a, &a};
static const uniform float b[] = {0.,4., 3., 2., 1.};
static const uniform float * uniform pb[] = {NULL, b+3, b};
> Fix for #1596.

- builtins/target-avx512skx-i32x8.ll
- src/llvmutil.cpp
- src/llvmutil.h
- src/opt.cpp
1. Removing version check in avx512skx-i32x8 builtin file.
2. An OR in IR could be equivalent to an ADD.
Checking for these add-equivalent ORs in our opt passes.
> Fixing llvm-trunk build warnings + lit test failures.

- .travis.yml
- benchmarks/01_trivial/01_aossoa.cpp
- benchmarks/01_trivial/01_aossoa.ispc
- benchmarks/01_trivial/02_soaaos.cpp
- benchmarks/01_trivial/02_soaaos.ispc
- benchmarks/common.h
- Benchmarks fixes: aligned memory allocation, typos, corrects type to run on all platforms.
- Enabling benchmark build and running sanity check in Travis. This adds less than a minute for individual run and about 3 minutes for total compute time consumed.
> Benchmarks fixes and enable benchmark testing

- run_tests.py
The pattern with checking Queue.empty() and doing Queue.get() without critical
section leads to dead locks. So, options are: use critical section or different
mechanism to pull the new job. This solution uses "STOP" markers in the Queue.
So, no check for empty queue is needed. The same queue is also used to indicate
that all tests are handled, as it's JoinableQueue. Hence getting rid of extra
Queue for signaling completion.
Also queue for signalling errors is removed. All exception will be reported as
Runtime failures and reported in the log.
> Fix synchronization issue in run_tests.py.

- .appveyor.yml
Changing the order to get the "latest" build first, so people can download it and try faster.
> Change build order for Appveyor

- bitcode2cpp.py
- cmake/GenerateBuiltins.cmake
- docker/v1.10.0/centos7/Dockerfile
- docker/v1.11.0/centos7/Dockerfile
- docker/v1.12.0/centos7/Dockerfile
- docker/v1.9.1/centos7/Dockerfile
- docker/v1.9.2/centos7/Dockerfile
- src/builtins.cpp
- src/ispc.cpp
- src/target_enums.cpp
* Adding Dockerfiles for reproducing 1.9.1-1.12.0 releases.
* GetISATargetString() is fixed. It doesn't have uses, so it's not really affecting anything.
* Parse ``--arch=wasm32``, which we forgot to add earlier.
* Removing outdated comment about cross-compilation support, which also affects setting triple for ARM targets.
* Enable stricter arguments checking in bitcode2cpp.py.
* Do not use amd64 as arch on FreeBSD, as internally it's just and alias for x86_64 and only create confusion.
> Bunch of small fixes

- cmake/GenerateBuiltins.cmake
* use ``-isystem`` to include system includes when building ``builtins.c`` instead of ``-I``
* use Android include to build FreeBSD target on macOS.
> Fixes for cross builds

- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- stdlib.ispc
- tests/lit-tests/avx512skx-registers.ispc
- tests/lit-tests/cpus_x86.ispc
- tests/lit-tests/cpus_x86_llvm_80plus.ispc
* introduce ``--opt=disbale-zmm`` switch to allow using only ymm registers even for avx512skx-i32x16 target.
* fix ``icl`` cpu definition.
> AVX512 code gen tuning

- .travis.yml
- scripts/install_v8.sh
- src/cbackend.cpp
- src/ctx.cpp
- src/llvmutil.cpp
- src/module.cpp
- src/opt.cpp
* Add v8 install script to CI
* Fix LLVM 11.0(trunk) build
Unfortunately LLVM trunk had some changes that prevent building ISPC so I had to fix some of the issues. The fixes are ad-hoc and it'd be better to wrap changed API in a separate function that handles all the differences.
If the initial version doesn't break the CI I'll push WASM testing to this or a new PR
> [WASM] Add v8 install script to CI

- CMakeLists.txt
- alloy.py
- builtins/target-avx512skx-i16x32.ll
- builtins/target-avx512skx-i8x64.ll
- perf.py
- run_tests.py
- src/ispc.cpp
- src/target_enums.cpp
- src/target_enums.h
* target are fully functional, but not fully optimized.
* remaining improvements are marked with TODO.
* alloy still supports LLVM before 8.0, should be no harm.
> AVX512skx i8 and i16 targets

- .travis.yml
- run_tests.py
- scripts/install_emscripten.sh
- scripts/install_v8.sh
- scripts/v8-redirect.sh
- test_static.cpp
V8 is switching to new simd binary opcodes (https://github.com/v8/v8/commit/41fbbd12a35d4f7bb89859c91da4b7b88e9d2d74) due to this PR (https://github.com/WebAssembly/simd/pull/209) so versions of emscripten and v8 have to be aligned to the recent compatible for now. Later the versions would have to be bumped manually.
expected failures:
* tests/clock.ispc - the kernel is too fast for low precision timer available for web 
To run:
```console
python3 run_tests.py --arch=wasm32 --target=wasm-i32x4
```
> [WASM] Enable tests

- docker/fedora/Dockerfile
- docker/ubuntu/Dockerfile
As ISPC now requires CMake 3.13 make sure the docker image has the correct version.
Additionally update to download from the github release page as it has better download speeds.
> Dockerfiles uses required CMake version

- tests/lit-tests/1638.args
- tests/lit-tests/nested_response_files.args
- tests/lit-tests/response_files.ispc
I couldn't find any test that verified the fix to https://github.com/ispc/ispc/issues/1638 so I went ahead and added one. This behavior is important to the project I am working on.
At the same time I noticed that ISPC didn't have any tests verifying missing or nested response files so I added those as well.
> Add a collection of tests for ISPC response file handling

- .travis.yml
- check_format.sh
* update check_format.sh to use clang-format 10.0.0.
* change the script to accept alternative name of clang-format as a first parameter.
* change the script to be more robust in recognition of clang-format version (accept clang-format-10 from Ubuntu packages).
* change the TravisCI job for checking format to use Ubuntu 20.04 image with clang-format package. This reduces time for this stage from 8min50 sec to 1min0sec.
> check_format.sh update

- tests/CMakeLists.txt
- tests/lit-tests/lit.cfg
Using single quote (i.e ' ) around strings is treated differently on Unix and Windows. So passing ON and OFF without quotes. Also asserting for if the parameter is not recognized as either ON or OFF.
> Fix behavior of lit tests on Windows

- src/stmt.cpp
- tests/lit-tests/print_bool.ispc
The _do_print() implementation assumes that bools are 32 bit wide. The existing check was not able to identify 'varying bools' . It was working before the bool storage type change since for target with mask = i32, varying bool was already 32 bit. For something like sse4-i8x16 with mask i8, the logic for printing int8 was handling it - hence why we see varying bool printed as 0,1 instead of true/false on non i32 masked targets.
I haven't added a comment in code since the logic has not been changed.
> Fix print for varying bools.

- llvm_patches/10_0_fix_for_1771_1.patch
- llvm_patches/10_0_fix_for_1771_2.patch
- tests/lit-tests/1771.ispc
Closes #1771 .
1. For 9.0 and 11.0, this doesn't seem to be an issue.
But 9.0 does create a different xor - https://godbolt.org/z/WeN9zM
Hence test being written for 10.0+ and patch applied only for 10.0
2. Lit test not run for avx512 targets- No constant folding happening anyway. So, assembly is same for 10.0 and 11.0 anyway. And no xor exists : https://godbolt.org/z/gKEGby
3. Craig said he is making a request to backport it to 10.0.1
> Fix #1771 - wrong code for avx2-i64x4, back-porting LLVM patch. 

- .travis.yml
- docker/ubuntu/Dockerfile
- tests/clock.ispc
* Travis restructured to allow adding more jobs not fitting in matrix
* Add ARM and macOS build jobs.
* Disable tests/clock on ARM (issue #1783)
* Switch docker/ubuntu to 10.0 as default
* Fix bug in Dockerfile, which led to not removing *_temp folders (5Gb total size)
Note, ARM and macOS currently using ``dybaboki/llvm-project`` repo for downloads. I'll switch it to ``ispc/llvm-project`` in future changes.
> CI improvements

- src/ctx.cpp
- src/expr.cpp
Using 'SwitchBoolSize()' for switching between bools and non-bool types
and removing legacy check.
> Fixing bool->non bool conversions for avx512.

- src/ctx.cpp
- src/ctx.h
- src/ispc.cpp
- src/ispc.h
- src/module.cpp
- src/type.cpp
fixes #1772 
Adding namespace for ispc module and adding variability to name in some cases prevents symbol colliding with CodeView.
> fix #1772 - adding ispc namespace for global

- src/type.cpp
- tests/lit-tests/1806.ispc
This affects how true (1) is treated. In case of unsigned it's 1. In case of signed, it's treated as -1.
There's another problem with boolean </> comparison - we do compare without promoting to i32, which is inconsistent with C/C++. If it causes a problem again, we should change it.
> Fix #1806 - treat bool as unsigned, not as signed.

- .github/workflows/linux-nightly-trunk.yml
- .travis.yml
- docker/ubuntu/llvm_build/Dockerfile
- add nightly testing with LLVM trunk
- adjust nightly time to nidnight PST
- add CMake download to LLVM build dockerfile, as LLVM 12 will require CMake 3.13.4+.
- update CMake version in Travis
> Add nightly testing with LLVM trunk

- .appveyor-clean-cache.txt
- .appveyor.yml
- Appveyor to use LLVM builds from Github Releases
- Fail Appveyor if run if "make check-all" is failing.
- Check env before building (for debugging purposes).
What's not in this PR, but needs to be done as well:
- Remove dependency on Docker file (cross tools, macOS SDK)
> Fix Appveyor

- src/ctx.cpp
- src/opt.cpp
Rearranging ifdefs to makethe code easier to read and more maintainable:
- LLVM versions are going from lesser to greater.
- Do not break function calls by multiple ifdefs.
- Number of "(" should match ")" to make possible jumping between them in the editor.
> Rearranging ifdefs

- .appveyor.yml
The problem was that "Environment" for job description in Appveyor has changed, while permanent download link requires fully specifying it. The fix reverts Environment change.
> Fix download links for Appveyor

- src/ctx.cpp
- src/ctx.h
- src/decl.cpp
- src/decl.h
- src/expr.cpp
- src/func.cpp
- src/func.h
- src/ispc.cpp
- src/ispc_version.h
- src/llvmutil.cpp
- src/main.cpp
- src/module.cpp
- src/module.h
- src/opt.cpp
- src/target_registry.cpp
- src/type.cpp
- src/util.h
The changes are assumed to be purely editorial. includes go separate groups:
(1) ISPC includes
(2) C++ library includes
(3) LLVM includes
clang-format was applied to sort these groups.
> Cleanup for includes: all LLVM includes are treated as system includes

- CMakeLists.txt
This fixes #1828.
Using an `if/else` for Clang and GCC is fine I hope.
> Fix compiling with GCC (#1828)

- .appveyor.yml
- benchmarks/01_trivial/01_aossoa.cpp
- benchmarks/01_trivial/01_aossoa.ispc
- benchmarks/01_trivial/02_soaaos.cpp
- benchmarks/01_trivial/03_popcnt.cpp
- benchmarks/01_trivial/04_fastdiv.cpp
- benchmarks/02_medium/test01.cpp
- benchmarks/common.h
* fix build warnings when building benchmarks on Windows
* enable benchmarks build in Appveyor (on WIndows).
> Benchmarks

- .appveyor.yml
- .travis.yml
- alloy.py
- docs/template-perf.txt
- docs/template.txt
- run_tests.py
- scripts/install_emscripten.sh
- Adding testing with LLVM 11.0 to Appveyor and Travis.
- Removing testing with LLVM 8.0 from Appveyor and Travis.
- Changing emcc testing for Linux to use fixed version instead of trunk (as we do on Windows).
- Fix alloy.py to fail uniformly with native testing and SDE.
- Fix site template to say that ISPC compiler for CPU *and GPU*.
> Add testing with LLVM 11.0 and other fixes.

- .github/workflows/linux-nightly-llvm10.yml
- .github/workflows/linux-nightly-llvm11.yml
- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/rebuild-llvm10.yml
- .github/workflows/rebuild-llvm11.yml
- Correct use of GITHUB_ENV and GITHUB_PATH in nightly testing and LLVM rebuild pipelines
- Use pre-build LLVM for testing with LLVM 11.0
- Update SDE to 8.59.0
- Start LLVM 11.0 nightly one hour later
- Use 7z extension for LLVM Windows archives
- Enable manual triggering for workflows
> Github Actions fixes

- .travis.yml
- alloy.py
- fail_db.txt
Fix first two issues from #1904 and extend timeout for alloy runs to avoid flaky fails in Github Actions.
> Fixes for C++17 readiness in CI.

- CMakeLists.txt
- alloy.py
- docker/centos7/Dockerfile
- CMakefile to require flex 2.6 and later (otherwise C++17 compiler would compilain on `register` keyword). See #1904 for more details.
- Centos7 based Dockerfile, which includes flex 2.6.4.
- Support LLVM debug build on Windows (in alloy.py).
- Extend timeout for individual tests when running under alloy.py to 1200 sec, as CI still fails from time to time.
> More changes for C++17 enabling

- .calcite/package-lock.json
- .calcite/package.json
- .github/workflows/linux-benchmarks.yml
As asked, this updates calcite-cli to be using the latest version of `class-transformer` since 0.2.3 had a CVE.
> Update calcite cli to 0.7.2 (no more out of date dependencies)

- src/type.cpp
- tests/lit-tests/1755.ispc
The hack to return uniform type for bool varying was needed earlier since returning i1 causes a crash when trying to store it. But it's not a problem anymore since now we are storing both uniform and varying as i8 irrespective of mask type.
> fixes #1755.

- .calcite/calcite.config.js
Due to an oversight during refactoring, diff/regression policies for the calcite datapoints were not set.
The calcite CLI default values were not meant to be used (will be fixed in an upcoming update) as it leads to very noisy results.
The slightest difference that passed our statistical tests would be considered as regressions/improvements, even if the change was as small as 1%. This is of course not what one would want for such benchmarks.
Following a general guideline, we now use the the median to compute the importance of the changes, with a threshold set at 20%.
This is a bit high, but takes into account the fact by default benchmarks (perhaps not the case for ISPC, but this is a general guideline) do not take into account for CPU issues such as the JCC erratum.
The threshold could …
> [CI] Use safe defaults for calcite benchmarks diff/regressions policies

- builtins/util.m4
This commit prevents llvm optimization passes to be run on __keep_func_live()
which is a temporary function created by ISPC to prevent certain pseudo functions etc.
from being removed.
> fixes 1937 : reduces compile time - do not optimize `__keep_funcs_live()`

- src/sym.cpp
- src/sym.h
- tests/lit-tests/scoped-typedef.ispc
- tests_errors/scoped-typedef.ispc
Fixes #1929
Changes were minor but `ClosestTypeMatch` and `RandomType` remaining untested/unused even though they are part of the patch.
> Added Type Scoping

- .calcite/calcite.config.js
When I converted to the latest calcite CLI I forgot to filter out aggregates in the google bench reports.
This PR ensures that we only send actual data to calcite.
Note that it didn't have much impact except when viewing the details as we are using outlier aware algorithms on the platform.
> Calcite config: do not take aggregates into account

- src/ctx.cpp
LLVM has removed `DebugLoc::get()` function, which was a wrapper around `DILocation::get()` in  llvm/llvm-project@41c3b2713. This PR removes the use of `DebugLoc::get()`.
> Fix to compile with LLVM trunk after llvm/llvm-project@41c3b2713

- .github/workflows/ispc-ci.yml
- examples/CMakeLists.txt
- examples/portable/genx/cmake/AddPerfExample.cmake
- ispcrt/CMakeLists.txt
- src/ispc_version.h
* reduce amount (and time) of `smoke` testing
* Introduce testing with `-g` in `full` mode
* enabled LLVM10 testing for `smoke`
* Fix ISPCRT version to match ISPC version
* Editorial changes
> CI adjustments and editorial changes

- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/rebuild-llvm11.yml
- alloy.py
- docker/centos7/Dockerfile
- docker/fedora/Dockerfile
- docker/ubuntu/full_ispc_build/Dockerfile
- docker/ubuntu/gen/Dockerfile
- docker/ubuntu/llvm_build/Dockerfile
* make alloy.py return proper exit code when failing to build LLVM
* Make LLVM 11 rebuild pipeline to producer correctly named artifacts (11.0.0 -> 11.0.1)
* Use more robust wget parameters in Dockerfiles
* When running LLVM trunk nightly pipeline use gzip instead of xz, so reducing overall time.
> CI & scripts & Dockerfile fixes

- .github/workflows/linux-benchmarks.yml
As mentioned by mail with @dbabokin, this enables calcite performance alerts when new commits are pushed to the `main` branch.
We use [`${{github.event.before}}`](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#webhook-payload-object-34) as the previous commit for the diff, which means it should only trigger against a commit already benchmarked to the main branch. (assuming CI is ran in order)
Note that it triggers a calcite workflow with the tag `push_main` which currently has no alerts set up.
This can be configured directly from the calcite project "alerts" page, to send diff reports either by email or slack (see the [documentation](https://doc.calcite.siliceum.com/usage/alerting.html) ) for more information.
> [calcite] Trigger workflow on push to main

- test_static.cpp
Fix Win64 tests when using run_tests.py.
> Do not use __vectorcall calling convention on WIN64 by default.

- .github/workflows/ispc-ci.yml
`alloy.py` return non-zero error code only if there were problems during testing (i.e. the process failed to complete, etc). Failing tests are not triggering non-zero error code. So `if: failure()` would not trigger in case of fails.
`git diff --exit-code` produces non-zero exit code if there are differences, so the job will be indicated as failing and fail log will be uploaded.
> Fix fails reporting in ISPC CI

- src/ctx.cpp
- src/ctx.h
- src/expr.cpp
- src/llvmutil.cpp
- src/llvmutil.h
- src/opt.cpp
Planning to switch to llvm::Twine for the entire repo for (const char *) in stages. This is stage 1.
> fixes #1821 - Removing LLVMGetName() and switching to LLVM::Twine.

- src/ctx.cpp
Removes '=' + concatenation for llvm::Twine.
> Fixing build on llvm trunk.

- alloy.py
Use `subprocess.Popen()` in `alloy.py` to execute shell commands. This allows manual control over produced output, hence no need for `tee` utility in `verbose` mode.
This fixes the problem of not detecting non-zero exit code with `--verbose` switch and make it work on all OSes.
> Fix --verbose for alloy builds - make it work on all OSes and honor exit code

- .github/workflows/scripts/install-build-deps.sh
This fixes Nightly pipeline for LLVM 12.0, which was failing when installing build dependencies (doing wget)
> Check that LLVM_REPO is defined when doing wget for compiler dependencies install

- docs/ReleaseNotes.txt
- docs/ispc.rst
Github deprecates redirection from github.com to github.io, so link need to point to github.io.
> Fix ispc.github.com -> ispc.github.io

- CMakeLists.txt
- examples/cpu/CMakeLists.txt
This sets correct options while compiling with GCC or Clang in Win32.
> CMake: Check MSVC before adding compiler and linker options.

- CMakeLists.txt
- builtins/target-genx.ll
- examples/xpu/common/L0_helpers.h
- examples/xpu/mandelbrot/mandelbrot.cpp
- fail_db.txt
- ispcrt/CMakeLists.txt
- ispcrt/detail/TaskQueue.h
- ispcrt/detail/cpu/CPUDevice.cpp
- ispcrt/detail/gpu/GPUDevice.cpp
- ispcrt/ispcrt.cpp
- ispcrt/ispcrt.h
- ispcrt/ispcrt.hpp
- ispcrt/tests/level_zero_mock/ze_mock.cpp
- ispcrt/tests/level_zero_mock/ze_mock.h
- ispcrt/tests/level_zero_mock/ze_mock_driver.cpp
- ispcrt/tests/mock_tests/ispcrt_mock_main.cpp
- run_tests.py
- src/builtins.cpp
- src/ctx.cpp
- src/expr.cpp
- src/ispc.h
- src/module.cpp
- src/opt.cpp
- test_static_l0.cpp
- tests/lit-tests/full_mask.ispc
- tests/lit-tests/genx_addr_space.ispc
- tests/lit-tests/genx_short_circuit.ispc
- tests/print_bool_simd.ispc
- Performance fix for short-circuit logic on Gen.
- `TaskQueue::submit()` method was add to ISPCRT.
- SVM block loads to use unaligned version - conservative fix for stability.
- `-presched` passed to finalizer to enabled register allocation before scheduling, it's good for performance.
- Do not generate full function mask if the function doesn't have a mask parameter (in this case it's always equivalent to internal mask).
> Updates for Gen target

- cmake/FindLLVM.cmake
I suppose this part needs to be indented?
Otherwise this throws `Failed to find clang++` for me on NixOS all the time.
> FindLLVM.cmake: fix indentation

- builtins/builtins-c-cpu.cpp
The `__num_cores` intrinsic is not found when compiling with stdlib for WASM:
stdlib.ispc:1765:12: Error: Undeclared symbol "__num_cores". Did you mean "num_cores"?
This function was moved from a c to cpp file in 2f6d077e ("New print implementation with support of genx.") but `extern "C"` wasn't added to every function declaration, leading to a mangled symbol name that cannot be found by its demangled C name.
> builtins/cpu: Give __num_cores C-linkage when building WASM

- CMakeLists.txt
/DYNAMICBASE is linker switch, also it must be all-caps. It's "Use address space layout randomization"
/GS is a compiler switch, it's a "Buffer Security Check".
> /DYNAMICBASE is a linker option, not a compiler option.

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/linux-benchmarks.yml
- .travis.yml
- CMakeLists.txt
- src/module.cpp
Bump pre-built LLVM versions for testing:
- Travis: `11.1` => `12.0`
- Appveyor: `10.0` & `11.1` => `11.1` & `12.0`
- Github Actions smoke& nightly: `10.0` & `11.1` => `11.1` & `12.0`
- Benchmarks: `11.1` => `12.0`
> Switch to LLVM 12 (part2)

- CMakeLists.txt
- src/bitcode_lib.cpp
- src/expr.cpp
- src/main.cpp
- src/stmt.cpp
- src/type.cpp
- Accommodate to clang13 switch `-Wunused-but-set-variable`
- Explicitly include `FileSystem.h` and use not deprecated version of `F_Text`, i.e. `OF_Text`
> Changes for LLVM13

- CMakeLists.txt
The change implementing -Wno-unused-but-set-variable in clang was reverted, so commenting it out for now.
> Temporarily disabling -Wno-unused-but-set-variable for clang13

- .github/workflows/scripts/install-build-deps.ps1
- .github/workflows/scripts/install-test-deps.ps1
Choco doesn't have retry mechanism (see https://github.com/chocolatey/choco/issues/385 for more details), so if it fails, we have a failed pipeline. We had quite a few such pipelines recently.
The rescue comes from Github Actions wrapper `Choco-Install`, which does retries (see https://github.com/actions/virtual-environments/pull/721 for more details).
> Fix choco timeouts in Github Actions.

- alloy.py
- common.py
For some reason `alloy.py` doesn't return properly on Windows. It reaches `sys.exit(n)` and hangs. This means that trying to clean up (release file handlers, flush streams, etc) it gets locked. In GH Actions we have 1-2 hangs (out of 84 jobs) per nightly run almost daily.
The fix is to use `os._exit(n)` instead, which exits the script, but doesn't release all resources.
The PR also contains several improvements in exception handling in `alloy.py` and a fix for a problem with `pickle`, which was previously hidden my exception handlers.
> Fix sporadic GH Actions test hangs on Windows

- docker/ubuntu/full_ispc_build/Dockerfile
- docker/ubuntu/llvm_build/Dockerfile
- docker/ubuntu/xpu_ispc_build/Dockerfile
Fix Ubuntu dockers.
`software-properties-common` package brings `python3.5`, which has alias `python3`. So `alloy.py` runs with `3.5`, which is not sufficient and causes the fail.
> Ubuntu images to use python3.6 explicitly to run alloy.py

- builtins/util.m4
- src/opt.cpp
This is the fix for https://github.com/ispc/ispc/issues/2082
To avoid uninitialized error from GCC I'm moving structs definition level up from the condition.
For successful compilation, it is required to declare genx specific intrisnics for CPU targets.
> Fixed alignment issues when using gcc

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/scripts/build-ispc.sh
- .travis.yml
- CMakeLists.txt
- benchmarks/CMakeLists.txt
- docker/ubuntu/cpu_ispc_build/Dockerfile
* Update `sde` version used in CI `8.59`->`8.63`.
* Fix #2080: fail in CMake if no targets are specified for ISPC.
* Remove `-Werror` from default build flags, add it manually in CI instead.
* Suppress warnings during Google Benchmark build, as this appears to be a problem with clang trunk.
> CMake and CI updates

- run_tests.py
* default to different targets based on host
* make verbose output copy-pastable
* remove -no_pie on macOS, it's not needed on x86 and doesn't work on ARM
* assume that aarch64 compiler targets aarch64 by default
* report target and arch
> run_tests.py improvements

- src/ispc.cpp
- tests/lit-tests/cpu_arm.ispc
- tests/lit-tests/cpu_arm_llvm12.ispc
* Adding definition for Apple ARM CPUs: A7, A10-A14 (missing A8 and A9, as they are just aliases for A7).
* Change default CPU target for ARM macOS and iOS.
Note, there's not M1 definition in open source LLVM right now, so using the latest A-series definition, which is good enough approximation for our purposes.
> Apple cpu definitions

- README.md
- examples/cpu/README.txt
- examples/xpu/README.txt
Update links to ispc GitHub Pages resulted from ispc.github.com to ispc.github.io.
The ispc.github.com links are broken and take you to this 404 page:
> 404
> 
> There isn't a GitHub Pages site here.
> 
> Did you mean to visit ispc.github.io? Please note that this site belongs to a GitHub user and is not an official GitHub site.
> 
> If you're the owner of this site, please update your links to use ispc.github.io instead. Subdomains of github.com are deprecated for GitHub Pages. They will not redirect to github.io after April 15, 2021.
> Contact Support — GitHub Status — @githubstatus
> Update broken GitHub Pages links.

- src/module.cpp
- src/opt.cpp
Deprecate attributes were removed in LLVM trunk (13.0).
No changes in behavior is expected.
> Do not use deprecated file open flags

- tests/exp-uniform-float16.ispc
- tests/exp-varying-float16.ispc
- tests/log-uniform-float16.ispc
- tests/log-varying-float16.ispc
- tests/pow-uniform-float16.ispc
- tests/pow-varying-float16.ispc
- tests/shuffle2-12.ispc
This commit includes
1. Fixing precision check for float16 pow/exp tests
2. Fixing range of arg for exp() tests so that values remain in valid range for float16
3. Removing unnecessary skip
4. Cleaning up reference value calculation for better understanding.
> Fixing float16 tests.

- src/expr.cpp
- tests/lit-tests/2116.ispc
This change contains the following
- Unary operations on reference type should update the referenced address and return value(updated or not depending on post/pre). This means, the unary expressions 'type' is the reference target type and not the reference type. This commit fixes this.
-  Test to check the behavior and crash. 
With no fix : https://ispc.godbolt.org/z/rov7axnqW
This test also checks for correctness to ensure that prefix/postfix properties hold.
> Fixes #2116: Fixing crash while using unary expression with reference type as rvalue.

- CMakeLists.txt
`xcrun` is known to fail to report SDK version properly for standalone SDK installations and in some default conditions (without executing `xcode-select -s <path>` first). So the detection code tries `xcrun` first and looks at folder name as a fallback option.
Thanks to @chrstphrchvz for bringing up this problem and helping with investigation in #2115.
> Improving macOS SDK version detection

- src/ast.cpp
- tests/2150.ispc
The problem is described in #2150. The fix also does similar check for `AllocaExpr` and `SyncExpr`.
> Fix #2150: safety check for unary expressions

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/nightly-13.yml
- .github/workflows/rebuild-llvm11.yml
- .github/workflows/rebuild-llvm12.yml
- .github/workflows/rebuild-llvm13.yml
- .github/workflows/scripts/install-build-deps.ps1
Starting LLVM 13, `clang++`  and some other binaries on Windows are created using symlinks (they used to be a copy of other binaries). `7zip` doesn't preserve symlink by default, so we need to do an extra step to preserve them. We create tar and then archive it using `7z` algorithm. So LLVM archive now has `.tar.7z` extension.
Note that to preserve symlinks when creating tar file, we need to use `7zip` and use `-snl` switch. Using stock `tar` which comes with Windows image doesn't work out of the box.
> CI: fix LLVM13 based build on Windows

- src/opt.cpp
I'm not sure why it worked earlier, but the fixed code is clearly wrong, as it inserts the instruction before its first argument is defined.
> Fix #2156: Insert shuffle instruction after its arguments are defined, but not before

- docs/ispc.rst
Following on from discussion #2159, this is an update to the documentation making clear the memory access behaviour of the aos_to_soa/soa_to_aos functions.
> Tweak aos_to_soa documentation

- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/scripts/install-build-deps.sh
- .github/workflows/scripts/install-svml-test-deps.sh
- .github/workflows/scripts/install-test-deps.sh
- alloy.py
* `alloy.py` to support two new switches `--compiler` and `--ispc-flags`
* Github Action pipeline to test SVML on Linux - triggered manually.
* More robust code in CI scripts to catch `apt-get` errors
* Move git tag used to build LLVM 13 in alloy.py to `13.0.0`.
> Adding CI pipeline to test --math-lib=svml

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-benchmarks.yml
- .github/workflows/nightly-13.yml
- .travis.yml
- alloy.py
This also has a missing patch for `alloy.py` to work properly with `--compiler` switch is defined.
> Add testing with released LLVM 13.0 to CI

- contrib/ispc.vim
Update vim syntax highlighting file to accommodate ISPC language changes, and fix inaccuracies:
- add `assert`, `assume`, `task`, and `unmasked` to statements
- moved `new` and `delete` from types to statements
- remove `reference` from statement list (not sure why it was there)
- add `uint8`, `uint16`, `uint32`, `uint64`, and `float16` types
- add `in` and `...` operators
- add `noinline` and `__vectorcall` as "storage class". Note `inline` is part of C syntax
- add all macros defined in ISPC.
- add llvm instrinsic calls support (@llvm.x86.blah-blah)
- properly define ISPC integer literals. Key differences are binary format support and [kMG] suffixes. Note that the suffix syntax is more restrictive that real patterns accepted by ISPC. The intent is to fix the parser to match this syntax …
> Update vim syntax file

- src/expr.cpp
- src/expr.h
- src/llvmutil.cpp
- src/llvmutil.h
- src/parse.yy
- tests/lit-tests/2148.ispc
- tests/lit-tests/constant_folding_double.ispc
- tests/lit-tests/constant_folding_float.ispc
- tests/lit-tests/constant_folding_float16.ispc
- tests/lit-tests/fast_math_opt.ispc
- tests/lit-tests/select_folding.ispc
Switching ConstExpr representation of `float` and `double` types to APFloat. This is done for two reasons:
1. it's the right thing to do, as internal representation using `float` and `double` types is error prone and depends on build options and may have portability problems
2. consistency with handling of `float16` type
Note: these changes do not completely eliminate the use of host logic involving `float` and `double` types.
Along with switching `float` and `double` to APFloat, all optimizations / foldings available for these types were also enabled for `float16` (specifically for BinaryExpr and SelectExpr)
Other changes included in this PR:
- regression test for #2148 
- fix for the bug with constant folding of select expression with `double` and `bool` types
- enabling fast-math …
> Switching to APFloat for representing 'ConstExpr' for all floating point types.

- builtins/target-xe.ll
- docs/ispc_for_xe.rst
- examples/xpu/aobench/ao.cpp
- examples/xpu/mandelbrot/mandelbrot.cpp
- examples/xpu/noise/noise.cpp
- examples/xpu/simple-dpcpp/simple-dpcpp.cpp
- examples/xpu/simple-esimd/simple.cpp
- examples/xpu/simple/simple.cpp
- fail_db.txt
- ispcrt/detail/Device.h
- ispcrt/detail/cpu/CPUDevice.cpp
- ispcrt/detail/cpu/CPUDevice.h
- ispcrt/detail/gpu/GPUDevice.cpp
- ispcrt/detail/gpu/GPUDevice.h
- ispcrt/ispcrt.cpp
- ispcrt/ispcrt.h
- ispcrt/ispcrt.hpp
- ispcrt/tests/level_zero_mock/ze_mock_driver.cpp
- ispcrt/tests/mock_tests/ispcrt_mock_main.cpp
- run_tests.py
- src/func.cpp
- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/module.cpp
- tests/lit-tests/xe_devices.ispc
- tests/lit-tests/xe_task_count.ispc
This GPU update introduces mainly performance improvements of ISPC Runtime:
- fixed setting of local group size for kernels
- implemented a new synchronization mechanism using events. There is no need to use barrier() before and after copying memory to/from the device, it will be done automatically.
- introduced usage of HW compute and copy engines
Also added functionality to pass stack size to VC backend using ISPC switch `--xe-stack-mem-size=N` (in case of AoT compilation) and `ISPCRTModuleOptions.stackSize` in ISPC Runtime (in case of JIT compilation)
> Updates for Xe targets (3)

- src/ispc.cpp
- src/main.cpp
- src/target_enums.cpp
- src/target_enums.h
- src/target_registry.cpp
- tests/lit-tests/cpus_x86.ispc
- tests/lit-tests/ps5_cpu.ispc
This PR adds support for PS5 target "OS". What it really does:
- sets target triple to `x86_64-scei-ps4`
- defaults CPU to `zen2` (which is what PS5 has according to Wikipedia) and adds `ps5` alias for it
- restricts `--arch` to `x86_64`
- enables `--pic`
This was not tested on PS5 hardware, but as PS5 is backward compatible with PS4, it should work out of the box.
> PS5 support

- src/ispc.cpp
The build was broken by this commit: https://github.com/llvm/llvm-project/commit/9cd55c7c3463fea334fd3169023bb63cca7276e5
The fix avoids using `AttrBuilder(const AttrBuilder &)` method.
> Fix build error with LLVM 14

- builtins/util.m4
- tests/lit-tests/aossoa_alignment.ispc
Recent changes in `aos_to_soa` and `soa_to_aos` stdlib calls made them use wide stores and these stores are aligned by default. This increases the alignment requirements, which potentially may cause stability regressions. At the same time, modern hardware handles unaligned stores as efficiently as aligned. So we should use unaligned stores.
> aos<->soa to use unaligned stores

- src/ispc.cpp
The build was broken after this commit: https://github.com/llvm/llvm-project/commit/d2cc6c2d0c2f8a6e272110416a3fd579ed5a3ac1 which changed `llvm::AttrBuilder` interface.
> Follow LLVM trunk with AttrBuilder changes

- CMakeLists.txt
- src/builtins.cpp
- src/ispc_version.h
- src/main.cpp
- src/module.cpp
- tests/lit-tests/llvm_ident.ispc
- removes existing `!llvm.ident` metadata with clang version used to build stdlib bitcode file. If ISPC is built correctly, this should be also correct, but not it's not guaranteed.
- explicitly add the correct info in two separate strings for ISPC itself and LLVM.
- use the same ISPC version string in LLVM IR metadata and for `ispc --version` output.
- unify Unix and Windows output for version strings. The current divergence seem to be a heritage of separate build system on Unix and Windows before CMake.
Here's how it looks like now for a trivial file:
```llvm
source_filename = "foo.ispc"
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-macosx"
@i = local_unnamed_addr global <8 x i32> zeroinitializer
!llvm.ident = …
```
> Add ISPC and LLVM version strings to !llvm.ident metadata.

- builtins/target-avx512knl-i32x16.ll
- src/main.cpp
- missed removing `BUILD_VERSION` in recent commit, that caused a warning on Windows
- missed that `rsqrt28` and `rcp28` precision is not enough for `double` on KNL, so doing on NR iteration to have better precision
> Fix a warning and a failing test

- check_format.sh
- stdlib.ispc
- Avoid using constant format not consumed by `clang-format` in `stdlib.ispc`
- Use `clang-format` to format `stdlib.ispc`
- Add `stdlib.ispc` to the list of files checked by `check_format.py` (i.e. in CI)
> Format stdlib.ispc with clang-format

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-benchmarks.yml
- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/nightly-13.yml
- .github/workflows/rebuild-llvm11.yml
- .github/workflows/rebuild-llvm12.yml
- .github/workflows/rebuild-llvm13.yml
- docker/README.md
- docker/ubuntu/18.04/cpu_ispc_build/Dockerfile
Support for Python 3.6 on Ubuntu 16.04 is EOL (more details here: https://github.com/deadsnakes/issues/issues/195). So Ubuntu 16.04 [Dockerfile](https://github.com/ispc/ispc/blob/fdf009cce84c741b5a74ea3c0e2d75c0c0d4cd45/docker/ubuntu/16.04/cpu_ispc_build/Dockerfile) stopped working. We could manually build and install Python 3.6, but I think it's time to move to Ubuntu 18.04 as a minimum version we use to build ISPC in CI.
The PR does the following:
- introduces Ubuntu 18.04 Dockerfile
- switches GitHub Actions CI to use Ubuntu 18.04 Dockerfile to build LLVM when LLVM re-build is needed
- switches GitHub Actions CI to use prebuilt LLVM binaries built on Ubuntu 18.04
- switches Appveyor CI to run on Ubuntu 18.04 image and use LLVM built on Ubuntu 18.04
What's still missing:
- aarch64 …
> Docker / CI update: move Ubuntu build from 16.04 to 18.04

- src/ctx.cpp
- src/expr.cpp
- src/func.cpp
- src/llvmutil.h
- src/module.cpp
- src/opt.cpp
This is the fix to make ISPC building with LLVM trunk, but more meaningful changes are required to support Opaque Pointers.
The current breakage was caused by LLVM commit https://github.com/llvm/llvm-project/commit/184591a.
Opaque Pointers are tracked in #2245
> Avoid build errors due to depricated function. This is due to Opaque Pointers changes in LLVM

- llvm_patches/11_0_11_1_12_0_shuffle_fix_2243.patch
- tests/lit-tests/2243.ispc
LLVM 12 binaries were updated, so CI is expected to pass with new regression test.
> Fix for #2243. Patch for LLVM 11 & 12 and a regression test

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-benchmarks.yml
- .github/workflows/nightly-14.yml
- .github/workflows/rebuild-llvm13.yml
- .travis.yml
- Switch CI (Github Actions, Appveyor, TravisCI) to use LLVM 13.0.1 instead of 13.0.0
- Retarget "Nightly 13" action to 14, as it's just branched. It's not enabled in cron yet (but still can be triggered manually).
> Switch to LLVM 13.0.1 in CI

- docker/centos/8/cpu_ispc_build/Dockerfile
Building static ncurses and symlinking  so -lcurses works as -lncurses(libcurses.a linked to libncurses.a). Not required for LLVM-only version but required for package build
> Centos 8 Dockerfile - lack of ncurses-static workaround

- llvm_patches/13_0_disable-DIArgList-in-SPIR-V.patch
- tests/lit-tests/xe_diarglist.ispc
This is a patch to LLVM 13 to disable generation of DIArgList for dbg.val for Xe targets plus lit test.
DIArgList construction is not supported by SPIR-V translator yet.
With this patch debug info for the cases when DIArgList looks the same as for LLVM 12.
> LLVM 13.0 patch to disable DIArgList for Xe targets

- src/module.cpp
- tests/lit-tests/1323.ispc
- tests/lit-tests/2134.ispc
The problem is that `LLVMType()` was used to evaluate alignment during header generation, instead of `LLVMStorageType()`. The difference between these two is only for `bool` type, which translates as `i1` by `LLVMType()` and as `i8` by `LLVMStorageType()`
> Fix #2134. Bool alignment issue.

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/nightly-14.yml
- .github/workflows/rebuild-llvm11.yml
- .github/workflows/rebuild-llvm12.yml
- .github/workflows/rebuild-llvm13.yml
- .github/workflows/scripts/install-build-deps.ps1
- .github/workflows/scripts/install-svml-test-deps.sh
- .github/workflows/scripts/install-test-deps.ps1
- .github/workflows/scripts/install-test-deps.sh
- README.md
- alloy.py
- use VS2022 as a default toolchain on Windows. Would need to use `generator="Visual Studio 16 2019"` for `alloy.py` to use VS2019.
- Actions / Appveyor with LLVM13 to use VS2022. LLVM 11 & 12 to stay on VS2019.
- SDE version upgraded to 9.0.0. They use another download location now (sigh...)
- GnuWin32 download not to use quite mode, as it's failing frequently lately
The decision to move to VS2022 is debatable. And we might choose to postpone it. Though I don't see the reasons not to move to VS2022 now. Earlier we move, more experience we'll get with it before releasing.
> CI updates: VS2022, SDE 9.0.0

- run_tests.py
ISPC supports a whole bunch of deprecated forms of target spelling, like `sse4-x2` and `avx` (see full list [here](https://github.com/ispc/ispc/blob/8c0153760929c2f8ff119a90ac86e074ad53f9ce/src/target_enums.cpp#L101)). This is for backward compatibility reason. But it doesn't make sense to support all of them in test scripts. This PR changes `run_tests.py` to accept only canonical spelling, which is either `isa`-`base type`x`width` (for example, `avx2-i32x8`) or `isa`-x`width` (for example, `avx512skx-x16`.
This also fixes the problem of incorrect detection of `avx512skx-x4` target width, which was detected as 8 (see fails in the latest nightly run).
> run_tests.py to recongnize only canonical form of the target names

- src/module.h
- src/type.cpp
- tests/lit-tests/1308.ispc
- tests/lit-tests/1323.ispc
Fix #1308 
Types in ISPC are created in the heap, not in the pool. So when we do multi-target compilation, any type caches should be reset, if they may contain any target-specific type. In the reported test case, the problem was unintentional reuse of function pointer type of the same width, but with different mask type (i.e. `<i1 x 8>` for AVX512 vs `i32 x 8` for AVX2).
> Fix #1308: reset struct cache for every target in multi-target compilation

- ispcrt/CMakeLists.txt
- ispcrt/cmake/ispc.cmake
- ispcrt/cmake/ispcrtConfig.cmake.in
This change improves detection of ispcrt version:
1. prints found ispcrt path and version when find_package(ispcrt) is used:
`-- Found ispcrt: /home/users/ispc/build/install/lib/cmake/ispcrt-1.18.0`
2. detects when requested ispcrt version is not found:
`find_package(ispcrt 1.19.0 REQUIRED)`
```
Could not find a configuration file for package "ispcrt" that is compatible with requested version "1.19.0".
The following configuration files were considered but not accepted:
/home/users/ispc/build/install/lib/cmake/ispcrt-1.18.0/ispcrtConfig.cmake, version: 1.18.0
/home/users/ispc/build/ispcrt/ispcrtConfig.cmake, version: 1.18.0
```
3. prints version of found ISPC compiler:
`--Found ISPC v1.18.0: /home/users/ispc/build/bin/ispc`
> Added print and check of ispcrt version

- docs/ispc.rst
- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/module.cpp
- src/module.h
- tests/lit-tests/2280.ispc
- tests/lit-tests/preprocessor-target=multi.ispc
Closes #2257, #1212, and #800.
Changes:
* Adds `-E` and `--ignore-preprocessor-errors` flags to CLI.
* Updates `execPreprocessor` to return a status code.
Updated: 03/18/2022.
> Preprocessor Fixes and Updates

- src/ast.cpp
- src/ast.h
- src/builtins.cpp
- src/decl.cpp
- src/decl.h
- src/expr.cpp
- src/expr.h
- src/func.cpp
- src/func.h
- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/module.cpp
- src/stmt.cpp
- src/stmt.h
- tests/lit-tests/ast_dump.ispc
- tests/lit-tests/ast_expr.ispc
- tests/lit-tests/ast_stmt.ispc
- tests_errors/soa-11.ispc
This PR adds `--ast-dump` switch, which is similar to clang's one. May be used in the following form:
- `--ast-dump=user` or `--ast-dump` to print AST for user code.
- `--ast-dump=all` to print all the code including stdlib.
The format of AST dump is intentionally made similar to format of clang AST, so it would look familiar for those who has experience with clang.
Other changes worth to note:
- `ASTNode` (and hence `Stmt` and `Expr`) class, and `Function` got member function `void Print()`, which works in the debugger. The one that was there previously didn't work in the debugger out of the box, as didn't do flashing, so nothing was printed unless `fflush()` was invoked manually.
- Most of functionality for `Print()` functions were kept the same, in some cases it was extended. But the …
> --ast-dump switch

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/nightly-15.yml
- .github/workflows/rebuild-llvm14.yml
- .travis.yml
- alloy.py
- `alloy.py` to build 14.0.1 when building `14.0`
- Rebuild14 pipeline to build files named 14.0.1
- `nightly-14` pipeline renames to `nightly-15` and changed accordingly. It supposed to be enabled when 15.0 is branched
- Remove build directories on Windows before packing LLVM 14, as the worker may run out of space
- GitHub Actions to testing to run LLVM 14 jobs: LLVM 13.0 & 14.0 - full testing, LLVM 11.1 & 12.0 sanity. Was LLVM 13.0 & 12.0 full, LLVM 11.1 - sanity
- Appveyor to test LLVM 13.0 and 14.0, instead of 12.0 and 13.0
- Travis to test 14.0, instead of 13.0.
> CI to test with LLVM 14.0

- CMakeLists.txt
- builtins/util-xe.m4
- ispcrt/CMakeLists.txt
- ispcrt/detail/TaskQueue.h
- ispcrt/detail/cpu/CPUDevice.cpp
- ispcrt/detail/gpu/GPUDevice.cpp
- ispcrt/ispcrt.cpp
- ispcrt/ispcrt.h
- ispcrt/ispcrt.hpp
- ispcrt/tests/mock_tests/ispcrt_mock_main.cpp
- src/opt.cpp
- tests/lit-tests/xe_prefetchw.ispc
- tests/prefetch-varying.ispc
- tests/prefetch.ispc
This update for Xe targets includes:
1. New ISPC Runtime API to copy MemoryView on device
2. Support of "device-only" memory without corresponding "appMemory" on CPU in ISPC Runtime
3. Changed behavior of prefetch operation on the targets where it is not natively supported: no operation is performed instead of reporting error.
> Updates for Xe targets (7)

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/rebuild-llvm11.yml
- .github/workflows/rebuild-llvm12.yml
- .github/workflows/rebuild-llvm13.yml
- .github/workflows/rebuild-llvm14.yml
- .github/workflows/scripts/build-ispc.sh
- .travis.yml
- README.md
- alloy.py
- tests/lit-tests/arg_parsing_errors.ispc
- Adding LLVM rebuild on ARM on self-hosted runner
- Move LLVM 14.0 version: 14.0.1 => 14.0.3
- Use `windows-2019` image to build ISPC with LLVM 11/12. Use both `windows-2019` and `windows-2022` to run tests.
- Due to https://github.com/ispc/ispc/issues/2326 switch to using VS2019 for LLVM 13/14 builds.
- Adding release build with LLVM 14 (doing sanity testing and running tests for `avx2-i32x8` only)
- Adding build with `-DISPC_NO_DUMPS=ON` and sanity testing (`make check-all`).
> CI fixes: LLVM rebuild on arm and LLVM 14 upgrade

- .github/workflows/docs.yml
- .github/workflows/format-check.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-benchmarks.yml
- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/nightly-15.yml
- .github/workflows/rebuild-llvm11.yml
- .github/workflows/rebuild-llvm12.yml
- .github/workflows/rebuild-llvm13.yml
- .github/workflows/rebuild-llvm14.yml
- alloy.py
- check_format.sh
- ISPC CI to use options selections for manual dispatch instead of sting input (`full` / `smoke`)
- `clang-format` to be used for format checking to be 12.0. More recent ones are still not available in the latest Ubuntu distributions
- `actions/checkout@v3` to be used instead of `v2`. No reason to stay on `v2`.
- Docs check pipeline to trigger only for docs changes (fixing typo in existing rules)
- LLVM to build `14.0.3` => `14.0.5`
> CI updates

- src/builtins.cpp
- tests/lit-tests/2128.ispc
Fix for https://github.com/ispc/ispc/issues/2128
> Added __cast_mask_to_i32/i64 to internal functions

- src/llvmutil.cpp
Fix for #2283 .
Usage of `&shufVec[shufSize]` when `shufVec` is `std::vector` seems invalid, so I changed it with to a standard array. It is the same approach as we use in other similar places of ISPC code.
> Replace usage of std::vector with array in LLVMShuffleVectors

- .github/workflows/rebuild-llvm15.yml
- .gitlab/.gitlab-ci.yml
- CMakeLists.txt
- alloy.py
- cmake/GenerateBuiltins.cmake
- run_tests.py
- src/ispc.cpp
- src/ispc_version.h
- src/opt.cpp
- `alloy.py` changes to build LLVM15 rc2
- workflow to build LLVM 15
- changes to support LLVM 16 / trunk
- unused GitLab files are removed
- CMake `ISPC_OPAQUE_PTR_MODE` flag to govern if opaque pointers are enabled (off by default)
- disabling `llvm::createArgumentPromotionPass()` for LLVM15+, as it's not supported by old pass manager. To be reenabled when we migrate to the new pass manager.
- Tests to build with `--pic`.
> Fixes to enable ISPC build with LLVM15

- builtins/svml.m4
- builtins/target-avx2-i16x16.ll
- builtins/target-avx2-i8x32.ll
- builtins/target-avx512skx-x32.ll
- builtins/target-avx512skx-x64.ll
- builtins/target-xe.ll
- builtins/util-xe.m4
- builtins/util.m4
- stdlib.ispc
The change is required to support opaque pointers in ISPC.
I use cast to `uniform int8* uniform` in stdlib.ispc and not to `void * uniform` for example because when we match stdlib to builtins functions we restore ISPC type from LLVM types (used in builtins) https://github.com/ispc/ispc/blob/main/src/builtins.cpp#L127.
To keep the logic working we can only use `uniform int8* uniform`.
> [opaque pointers 1] Use int8 pointer instead of typed pointers in stdlib/builtins

- src/opt.cpp
This change prepares ISPC code base to support opaque pointers mode.
1. removes usage of getElementPointerType from opt.cpp (also hidden in PTYPE macro)
NOTE: there is a bunch of functions related to the processing of our pseudo gathers/pseudo scatters intrinsics where the base pointer element type is always int8. There is no way to get it from the function signature in opaque mode, so I'm keeping it in the constructors of helper structures.
2. aligns common pointer calculation for CPU and Xe targets (before we calculated the base before the common pointer due to limitations in VC BE, now it's fine)
> [opaque pointers 2] Removed usage of getElementPointerType from opt.cpp

- src/builtins.cpp
- src/ctx.cpp
- src/ctx.h
- src/expr.cpp
- src/func.cpp
- src/module.cpp
- src/stmt.cpp
- src/sym.cpp
- src/sym.h
`AddressInfo` class is necessary to support opaque pointers. It contains the pointer itself, LLVM pointer element type and ISPC type (may be NULL).
This PR is the first set of changes switching ISPC to use `AddressInfo`:
1. `AllocaInst` starts returning `AddressInfo*` instead of `llvm::Value*`
2. `Symbol` class keeps `AddressInfo*` instead of simple `llvm::Value*`
Note: Many `getPointer()` calls will be removed in future PRs.
> [opaque pointers 3] Introduce AddressInfo class to ISPC

- src/ctx.cpp
- src/ctx.h
- src/expr.cpp
- src/expr.h
- src/func.cpp
- src/stmt.cpp
- src/type.cpp
- src/type.h
- tests/lit-tests/bool_swizzle.ispc
Depends on https://github.com/ispc/ispc/pull/2363.
This PR introduces more usages of `AddressInfo` class in particular in `StoreInst` and `InitSymbol`.
It also introduces a method to get LLVM types of function arguments `LLVMFunctionArgTypes` and simplifies `StoreInst` - we don't need to pass info about uniform data anymore.
During the testing, I also discovered the problem with bool swizzles: https://github.com/ispc/ispc/issues/2367.
> [opaque pointers 4] Use AddressInfo in StoreInst

- src/ctx.cpp
- src/ctx.h
- src/expr.cpp
- src/func.cpp
- src/module.cpp
- src/stmt.cpp
This PR switches `StoreInst` to use `AddressInfo` class.
Also eliminates usage of `getPointerElementType` in easy cases.
> [opaque pointers 5] Use AddressInfo in LoadInst

- CMakeLists.txt
Link `windowsdriver` component on all platforms, otherwise macOS blows up. Linux works just because linker is smart.
> Fix linking problem caused by windowsdriver component on macOS with LLVM 15+

- tests/lit-tests/fp16_support.ispc
Disable fp16_support test on unsupported configurations related to ARM support.
> Disable fp16_support test on unsupported configurations

- src/ctx.cpp
- src/ctx.h
- src/expr.cpp
- src/func.cpp
- src/stmt.cpp
- tests/CMakeLists.txt
- tests/lit-tests/1323_1.ispc
- tests/lit-tests/1323_2.ispc
- tests/lit-tests/1763.ispc
- tests/lit-tests/2376.ispc
- tests/lit-tests/float16_uniform.ispc
- tests/lit-tests/float16_varying.ispc
- tests/lit-tests/lit.cfg
- tests/lit-tests/load_unaligned.ispc
- tests/lit-tests/print_bool.ispc
The last piece of changes related to opaque pointers.
1. Eliminated remaining usages of getPointerElementType
2. Fixed signature of `llvm.memcpy` intrinsic in opaque mode
3. Fixed lit tests
> [opaque pointers 6] Final fixes

- src/expr.cpp
- src/func.cpp
- src/module.cpp
- src/sym.h
- src/type.cpp
- Make `FullResolveOverloads()` function to be static, as it's used in one file.
- Print function type in AST dump.
- When printing function type designate that a parameter has default value.
- Remove unnecessary breaks in error message encoding in the source code. clang-format doesn't change this be default. Initial code width limit was 80, now it's 120.
- Fix a comment.
> Several editorial fixes

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-benchmarks.yml
- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/nightly-15.yml
- .github/workflows/rebuild-llvm15.yml
- .github/workflows/reusable.rebuild.yml
- .github/workflows/scripts/install-llvm-deps-mac.sh
- .travis.yml
- alloy.py
- docker/ubuntu/18.04/cpu_ispc_build/Dockerfile
- docker/ubuntu/20.04/cpu_ispc_build/Dockerfile
- docker/ubuntu/20.04/xpu_ispc_build/Dockerfile
- docker/ubuntu/22.04/cpu_ispc_build/Dockerfile
- docker/ubuntu/22.04/xpu_ispc_build/Dockerfile
- Install `python-dev` instead of `python` in Ubuntu images, otherwise LLVM trunk doesn't build.
- Use `macos-11` for LLVM builds.
- Build LLVM on macOS in two stages, as building in one now timeouts.
- Move LLVM 15 build from `15.0.0` to `15.0.2`, it contains critical fix for enabling macOS testing in CI (static link of ZSTD).
- Move CI testing to use `15.0.2`
- Use `v3` of download/upload actions.
> CI updates: 15.0.2, macos-11, others

- .github/workflows/rebuild-llvm15.yml
- alloy.py
- src/func.cpp
- src/func.h
- src/parse.yy
- src/sym.cpp
Most of the changes are editorial, except these two:
- `Function` class constructor to run `TypeCheck()` and `Optimize()` after all the symbols are saved. This should not affect compiler behavior, but it's done, as it's more consistent.
- LLVM 15 to build in `alloy.py` is `15.0.4` instead of `15.0.3`. CI still uses `15.0.3`
Editorial changes:
- Reorder includes in `parse.yy` in alphabetical order.
- Add documentation for `Function` class constructor and outline typechecking & optimization calls.
- `Symbol` constructor to use initialization list.
> Set of minor fixes

- ispcrt/CMakeLists.txt
Default value is ON. When OFF static library building is omitted.
> ispcrt: Add ISPCRT_BUILD_STATIC option.

- ispcrt/ispcrt.hpp
Related to https://github.com/ispc/ispc/commit/fa3c06ef4055686b3c70151f991cb38e390c2cf4.
The fix was missed for `Array` constructor using `Context`.
Plus submodules update having required fix for build on Ubuntu 22.04: for https://github.com/google/googletest/pull/3024
> Fix of ISPC Runtime memory leak

- .github/workflows/rebuild-llvm15.yml
- alloy.py
- src/decl.cpp
- src/expr.cpp
- src/expr.h
- src/stmt.cpp
- tests/lit-tests/ftz_daz_flags_aarch64.ispc
- tests/lit-tests/ftz_daz_flags_arm.ispc
- tests/lit-tests/ftz_daz_flags_x86.ispc
- tests/lit-tests/ftz_daz_flags_x86_64.ispc
- tests/lit-tests/lit.cfg
- Fix FTZ/DAZ test on macOS (which doesn't support 32 bit version of x86 and arm).
- Removed unused LLVM14/15 macros in lit testing, as LLVM13, which is used by one of the tests.
- Move LLVM15 build (not use in CI) to `15.0.5`
- Clean up in FunctionSymbolExpr::ResolveOverloads() - this changes error message for builtins, but the logic is not changed. This logic supposed to be different for builtins, but it's not true for very long time.
- Several editorial changes, which were split from Templates PR.
> Editorial and test fixes

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/nightly-15.yml
- .github/workflows/rebuild-llvm15.yml
- .github/workflows/scripts/install-build-deps.sh
- .travis.yml
- alloy.py
- docker/ubuntu/18.04/cpu_ispc_build/Dockerfile
- Build LLVM `15.0.6` with `alloy.py`
- Use LLVM `15.0.6` in CI (instead of `15.0.3`)
- Build LLVM with explicitly turned off ZSTD compression. This should not matter on Linux and Windows, but ZSTD shows up on macOS. We don't use compression anyway.
- Fix git version in Ubuntu 18.04 Dockerfile.
- Explicitly install `libtinfo5` for ISPC build, as it's not available by default in `ubuntu-22.04` image from Github.
- Use `ubuntu-20.04` image for testing with LLVM 11 & 12, as new version of library GLIBCXX has deprecation attributes for some of the stuff used by LLVM 11 & 12 and it causes build errors (with `-Werror` that we have enabled in CI)
- Fix Github Actions warnings: avoid using `set-output` and update `microsoft/setup-msbuild` action by switching to `v1` tag.
> Fix CI and move to LLVM 15.0.6

- .github/workflows/ispc-ci.yml
- .github/workflows/linux-benchmarks.yml
- .github/workflows/scripts/build-ispc.sh
- .github/workflows/scripts/check-ispc.sh
- .github/workflows/scripts/install-build-deps.ps1
- alloy.py
- one of dependencies downloads on Windows we randomly failing - the reason redirect routes to the server with new TLS version requirement. Fix by enabling TLS of all versions.
- add macOS build. macOS testing is not added yet, as `alloy.py` in testing mode fails on macOS in a strange way (this still needs debugging).
> GH Actions: fix Windows & enable macOS build

- src/func.cpp
- src/module.cpp
- tests/lit-tests/windows_dllexport.ispc
Make dispatch export function callable from DLLs.
Required when producing dynamic library from ISPC object for further usage from ISPC Runtime on CPU.
> Make dispatch function dllexport if needed

- check_isa.cpp
- src/ispc.cpp
The existing `__aarch64__` macro is not defined for MSVC ARM64 platforms, so an additional check for `_M_ARM64` needs to be made in order to compile a native ARM64 binary.
> Add support for ARM64 MSVC binary targets

- src/opt/MangleOpenCLBuiltins.cpp
- src/opt/XeReplaceLLVMIntrinsics.cpp
- tests/lit-tests/xe_spirv_ocl_mangle.ispc
This PR fixes ISPC build with spirv_translator v15.0 and removes usages of LLVM `freeze` instruction since it's not supported by LLVM translator v15.0.
Relates to #2419
> fix for build with spirv_translator v15.0

- alloy.py
Add flag `--shallow-clone` to clone `llvm` repository with `--depth=1`. It would be faster and consume less disk space.
> alloy.py: shallow clone repo by default, add --full-checkout option

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/nightly-15.yml
- .github/workflows/rebuild-llvm15.yml
- .travis.yml
- alloy.py
- docker/ubuntu/18.04/cpu_ispc_build/Dockerfile
- Build LLVM `15.0.7` in `alloy.py` instead of `15.0.6`
- Use LLVM `15.0.7` in CI
- Fix Ubuntu 18.04 Dockerfile to avoid certain pinned package versions - more general fix is needed.
> Use LLVM 15.0.7 for build and CI

- CMakeLists.txt
- docker/README.md
- docker/fedora/Dockerfile
- tests/lit-tests/llvm_ident.ispc
Link with static libraries (libclangFrontend.a, ...) if they found. Otherwise, dynamically link with libclang-cpp.so.
> CMakeLists.txt: change libclang linking logic

- .appveyor.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-benchmarks.yml
- .github/workflows/scripts/install-build-deps.ps1
- .travis.yml
Moving build dependencies to be downloadable from [ispc.dependencies](https://github.com/ispc/ispc.dependencies) to avoid confusion. Also moving `libgw32c-0.4-lib.zip` download to the same repo, as downloading from SourceForce appears to be unreliable, yielding constant CI fails.
> Switch CI to use ispc/ispc.dependencies repo instead of ispc/llvm-project fork

- src/main.cpp
#2438 introduced a new `link` command, but failed to check `argc` before reading `argv[1]`, which resulted in a crash.
> Fix crash in main when no command argument is provided

- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/nightly-15.yml
- CMakeLists.txt
- alloy.py
- src/main.cpp
- tests/lit-tests/discard_value_names.ispc
- Remove `LLVM_ENABLE_DUMP` for optimized/release LLVM build. The functionality is enabled by default for debug build (`--debug` switch for `alloy.py`) anyway. For optimized build it costs us ~1.5Mb of binary size and slight slowdown for compile time.
- Change the default behavior for `--[no]discard-value-names`. By default it's only enabled for if the output is bitcode (text or binary). This reduces compile time **significantly**. For the test case I use for the measurement, it brought down compile time from 3:52 to 3:25 (LLVM build was with asserts).
- Add libclangASTMatchers for the list of linked libraries for LLVM 16, as it's required now.
- Upgrade SDE in CI `9.0.0` -> `9.14.0`.
> LLVM build and usage: NODUMPs, discard-value-names

- src/expr.cpp
- src/ispc.cpp
- src/ispc.h
- tests/lit-tests/1963.ispc
- tests/lit-tests/arg_parsing_errors.ispc
- tests/lit-tests/perf-warnings.ispc
This PR add a generic mechanism to enable performance warnings only for selected targets. Such warnings are enumerated in `PerfWarningType` enum and are explicitly enabled for every target (or class of targets based on ISA).
Also, the set of warnings for inefficient converts were changed:
- warnings for `[float16|float|double]` -> `uint[8|16]` were removed, as they are not a problem on any of existing target. Looks like it was a copy-past error for these warnings from day-one (most of them were added really long time ago).
- warnings for `uint[32|64]` -> `[float16|float|double]` were added, because they are as problematic as converts in reverse direction (which we warn for).
Warnings related to `float16` converts were disabled for SSE2/SSE4/AVX1 targets, as these targets do not have any …
> Redesign target-dependent performance warnings

- ispcrt/cmake/ispc.cmake
Introducing x32 CPU targets to ISPCRT confuses some of the existing clients.
> Remove avx512spr-x32 from ispcrt/cmake/ispc.cmake

- builtins/target-xe.ll
- docs/ispc_for_xe.rst
- examples/xpu/sgemm/sgemm.cpp
- ispcrt/cmake/Finddpcpp_compiler.cmake
- ispcrt/cmake/Findlevel_zero.cmake
- ispcrt/detail/gpu/GPUDevice.cpp
- ispcrt/ispcrt.cpp
- ispcrt/ispcrt.h
- ispcrt/tests/mock_tests/ispcrt_mock_main.cpp
- src/ast.h
- src/ctx.h
- src/ispc.cpp
- src/ispc.h
- src/llvmutil.cpp
- src/main.cpp
- src/module.cpp
- src/module.h
- src/sym.cpp
- src/type.h
- tests/lit-tests/mask_extract_first_el.ispc
- Use `icpx` as a compiler name for DPC++
- ISPCRT improvements
- Use native intrinsic for `rsqrt(float16)` on Xe targets.
- Fix for OSPRay build, caused by a bug in `lExtractFirstVectorElement()` function.
- Add "bookkeeping" for AST objects to be able to delete all of them by request, this is an alternative to "disciplined" work with memory and to using memory pools for object allocation.
> Updates for Xe targets (14)

- ispcrt/cmake/ispc.cmake
- src/target_registry.cpp
- tests/lit-tests/avx512spr-i32x8.ispc
- tests/lit-tests/fp16_code_gen.ispc
- tests/lit-tests/perf-warnings.ispc
- tests/lit-tests/target_x86_macos_no_spr.ispc
- tests/lit-tests/targets_x86_llvm14plus.ispc
There's no Mac hardware using SPR, so disabling it for macOS target.
> Disable SPR targets on macOS

- examples/xpu/callback-esimd/CMakeLists.txt
- examples/xpu/cmake/AddPerfExample.cmake
- examples/xpu/simple-esimd/CMakeLists.txt
- examples/xpu/vadd-esimd/CMakeLists.txt
- ispcrt/cmake/interop.cmake
- ispcrt/cmake/ispc.cmake
- ispcrt/detail/cpu/CPUDevice.cpp
- src/type.cpp
- tests/lit-tests/xe_dwarf_addrspace.ispc
This Xe-related PR contains two changes:
First the PR refactors ISPC's handling of CPU and GPU custom commands and targets to support building an ISPC GPU target from multiple ISPC files, linking them with `ispc link`. The PR also makes the ISPC targets act more like regular CMake targets by using generator expressions to process includes, defines, and link libraries at a per-target level. So now an application's ISPC CMakeLists would be as below:
```
add_ispc_library(my_ispc_lib filea.ispc fileb.ispc)
ispc_target_include_directories(my_ispc_lib <some directory path>)
ispc_target_compile_definitions(my_ispc_lib -DMY_DEFINE=1)
add_ispc_library(my_ispc_kernel filec.ispc)
ispc_target_link_libraries(my_ispc_kernel my_ispc_lib)
```
Second, the PR fixes generation of debug information for …
>  Updates for Xe targets (15)

- CMakeLists.txt
If this option is not present, it causes link warnings on macOS with new pass manager or when ISPC is built as a Debug build.
> Add -fvisibility-inlines-hidden to ispc build.

- src/llvmutil.cpp
- src/llvmutil.h
- src/opt/GatherCoalescePass.cpp
- src/opt/ImproveMemoryOps.cpp
- src/opt/InstructionSimplify.cpp
- src/opt/IntrinsicsOptPass.cpp
- src/opt/IsCompileTimeConstant.cpp
- src/opt/PeepholePass.cpp
- src/opt/ReplacePseudoMemoryOps.cpp
- src/opt/ReplaceStdlibShiftPass.cpp
Many of ISPC opt phases are unnecessary O(n^2) on the number of optimization triggers in the single basic block. This is because optimization restart on the basic block once it triggers, but there's not real need for that it iteration is done more carefully. The key is to maintain a valid iterator after the optimization removes "current" instruction.
The PR makes the complexity linear.
The PR reduce compile time for small examples approximately by 5%. For large examples the benefits are way smaller.
> Reduce complexity of ISPC opt phases

- CMakeLists.txt
- examples/xpu/callback-esimd/CMakeLists.txt
- examples/xpu/simple-esimd/CMakeLists.txt
- examples/xpu/vadd-esimd/CMakeLists.txt
- ispcrt/cmake/ispc.cmake
- src/module.cpp
These changes are not Xe specific.
- Fix for #2380 - do not link unnecessary code for preprocessor. The fix reduce ISPC binary size significantly - approximately by 23%.
- Allow 'bc' ISPC_XE_FORMAT
> Updates for Xe targets (16)

- src/target_registry.h
This fix adds missing <cstdint> include to handle "uint32_t" when building with GCC 13 and possibly Clang 15 as illustrated below
```
In file included from /builddir/build/BUILD/ispc-1.19.0/src/bitcode_lib.cpp:40:
/builddir/build/BUILD/ispc-1.19.0/src/target_registry.h:80:14: error: 'uint32_t' was not declared in this scope
80 |     std::map<uint32_t, const BitcodeLib *> m_builtins;
|              ^~~~~~~~
/builddir/build/BUILD/ispc-1.19.0/src/target_registry.h:44:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
43 | #include <map>
+++ |+#include <cstdint>
44 | #include <vector>
/builddir/build/BUILD/ispc-1.19.0/src/target_registry.h:80:42: error: template argument 1 is invalid
80 |     std::map<uint32_t, const BitcodeLib *> m_builtins;
```
> Fix build with GCC 13 and possibly Clang 15

- CMakeLists.txt
- cmake/FindLLVM.cmake
It may be useful when only minimal set of dependencies presented in PATHs not the whole LLVM installed.
Fix #2318
> cmake: look only for llvm-config not LLVM package

- ispcrt/detail/Device.h
- ispcrt/detail/cpu/CPUDevice.cpp
- ispcrt/detail/cpu/CPUDevice.h
- ispcrt/detail/gpu/GPUDevice.cpp
- ispcrt/detail/gpu/GPUDevice.h
- ispcrt/ispcrt.cpp
- ispcrt/ispcrt.h
- ispcrt/ispcrt.hpp
- ispcrt/tests/mock_tests/ispcrt_mock_main.cpp
Changes:
*   Added `getType` to `Device` interface. 
| `ispcrt/detail/Device.h`,
| `ispcrt/detail/cpu/CPUDevice.cpp`,
| `ispcrt/detail/cpu/CPUDevice.h`,
| `ispcrt/detail/gpu/GPUDevice.cpp`,
| `ispcrt/detail/gpu/GPUDevice.h`,
| `ispcrt/ispcrt.cpp`,
| `ispcrt/ispcrt.h`,
| `ispcrt/ispcrt.hpp`,
| `iscprt/tests/mock_tests/ispcrt_mock_main.cpp`
> ispcrt: Expose device type

- src/builtins.h
- src/opt/MangleOpenCLBuiltins.cpp
Changes:
*   Move name mangling out of opt to common builtins header.
| `src/builtins.cpp`,
| `src/builtins.h`,
| `src/opt/MangleOpenCLBuiltins.cpp`,
| `src/opt/MangleOpenCLBuiltins.h`
Description:
>When adding functions declarations to ISPC modules via `AddFunctionDeclaration`, names are expected to be unique.
>If the the same function is registered more than once, the resulting declaration is renamed with a numeric suffix (e.g. `foo.1`).
>For the specialization constants feature, we need declarations for each `constspec` type we would like to initialize.
>However, the base name for the builtin for all types is `__spirv_specConstant`.
>Adding declarations with the appropriate signature does not prevent the mangling from attempting to disambiguate the function names.
>Moving the mangling …
> builtins: Refactor mangling utilities

- .devcontainer/README.md
- .devcontainer/devcontainer.json
- README.md
PR includes a minimal Codespaces container for comfortable browsing, editing, and building ISPC project.
The configuration includes pre-built LLVM 15.0.7.
If it works well, we can add GPU-enabled env, though I'm not sure if we can have Intel GPU-enabled cloud instance.
> Enable Codespaces for ISPC

- .github/workflows/rebuild-llvm16.yml
- README.md
- alloy.py
- `alloy.py` to build `16.0.2` when LLVM 16 is requested.
- add pipeline to build LLVM 16.
- fix README - move Codespaces badge to a separate line
> alloy.py to build LLVM 16.0.2 and build it in CI.

- .github/workflows/linux-benchmarks.yml
Also change installation script to be unified with other actions - this will fix current failure because of lack of `libtbb-dev`
> Move Linux Benchmarks pipeline to LLVM 15

- .gitignore
Ignore the build directory. Useful for Codespaces with build included in the root.
> gitignore: Add build directory to ignored files

- alloy.py
Partial revert of 7b23d8243eb42ac6683d208fdc4108fd27b92d9a.
OpenMP is still needed in some jobs for testing of ISPC Runtime.
> Enable OpenMP back in alloy.py

- .devcontainer/devcontainer.json
- CMakeLists.txt
- alloy.py
Fixes #2461.
To enable the binary running on old macOS, `CMAKE_OSX_DEPLOYMENT_TARGET` needs to be properly set for all components of the binary, so it needs to be done for LLVM and ISPC itself. This PR does this defaulting the target to `10.12` (Sierra) for x86 and `11.0` (Big Sur). `10.12` is pretty old OS, but there seem to be no reasons not to support it. `11.0` is the minimum that supports macOS on ARM.
As a bonus, `CMAKE_EXPORT_COMPILE_COMMANDS` is always enabled now, it makes setting up VSCode browsing easier and it's handy for debugging compilation commands (figuring out what was really passed to the compiler).
> Enable macOS build on the new OS supporting old OS

- src/expr.cpp
- src/llvmutil.cpp
- src/llvmutil.h
- src/type.cpp
- src/type.h
- tests/lit-tests/vector_type_convert.ispc
Currently for uniform short vector conversions ISPC generates scalar instructions.
For example for the following case:
```
uniform float<3> x = {1,2,3};
uniform double<3> z = x;
```
ISPC generates 3x`fpext float` instructions.
The PR enables generation of vector instructions for such cases. So instead of 3x`fpext float`, 1x`fpext<4xfloat>` will be produced.
It's used now for conversions only but planned to be extended for short vector initialization as well.
> Generate vector instructions for uniform vector conversions

- src/expr.cpp
- tests/lit-tests/vector_type_init-1.ispc
- tests/lit-tests/vector_type_init-2.ispc
Try to produce vector type conversion when initializing short vectors.
It's not a partial fix for https://github.com/ispc/ispc/issues/2147. The frontend produces the same code as in https://github.com/ispc/ispc/issues/2147#issuecomment-922027113 with fake varying trick.
> Use vector conversion for uniform vector initialization

- .github/workflows/reusable.rebuild.yml
- CMakeLists.txt
- alloy.py
- llvm_patches/15_0_disable-A-B-A-B-and-BSWAP-in-InstCombine.patch
Fixes #2329.
- add `--macos-universal-binary` to `alloy.py`, which triggers LLVM build as Universal Binary (x86_64 + arm64)
- add `ISPC_MACOS_UNIVERSAL_BINARIES` to CMake on macOS, which builds ISPC as Universal Binary.
- add arch suffix to package name on macOS, it's either `x64_64`, `arm64`, or `universal`.
- build LLVM as Universal Binary on macOS in CI.
- fix LLVM patch for `15.0`, so it properly applies on Windows in CI.
- run macOS rebuild jobs on `macos-12-xl` runners, which are "big" instances (12 cores) and allow finishing selfbuild jobs within the time limit.
The plan is to release 3 set of binaries `x64_64`, `arm64`, and `universal`.
> Build Universal Binaries on macOS

- builtins/dispatch-macos.ll
- builtins/dispatch-no-spr.ll
- builtins/dispatch.ll
- check_isa.cpp
- src/ispc.cpp
Fix #2504.
This fix removes GCC 4.x.x workaround in dispatch code. It causes problems on 64 bit target, which showed up as `check_isa.cpp` fail when compiled with -O0. It could also potentially affect ISPC output produced with auto-dispatch.
For the complete description of the problem see #2504.
> Remove GCC 4.x.x workaround in dispatch code.

- docs/ispc_for_xe.rst
- examples/xpu/CMakeLists.txt
- examples/xpu/README.md
- examples/xpu/TestLists.txt
- examples/xpu/simple-fence/CMakeLists.txt
- examples/xpu/simple-fence/simple-fence.cpp
- examples/xpu/simple-fence/simple-fence.ispc
- ispcrt/detail/CommandList.h
- ispcrt/detail/CommandQueue.h
- ispcrt/detail/Device.h
- ispcrt/detail/Fence.h
- ispcrt/detail/TaskQueue.h
- ispcrt/detail/cpu/CPUDevice.cpp
- ispcrt/detail/cpu/CPUDevice.h
- ispcrt/detail/gpu/GPUDevice.cpp
- ispcrt/detail/gpu/GPUDevice.h
- ispcrt/ispcrt.cpp
- ispcrt/ispcrt.h
- ispcrt/ispcrt.hpp
- ispcrt/tests/level_zero_mock/ze_mock.cpp
- ispcrt/tests/level_zero_mock/ze_mock_driver.cpp
- ispcrt/tests/mock_tests/ispcrt_mock_main.cpp
Expose `CommandQueue`, `CommandList` and `Fence` objects from `L0` to ISPCRT. It allows to explicitly construct them and manage in more ways than `TaskQueue` object. With that change, one can compute something in CPU thread in parallel with GPU computation.
> ispcrt: support Fence

- .github/workflows/ispc-ci.yml
- .github/workflows/scripts/build-ispc.sh
- alloy.py
- `alloy.py` to build LLVM `16.0.3` instead of `16.0.2`
- macOS job to use LLVM Universal Binaries.
- add test run on macOS, instead of just a build.
- limit the number of optsets to run with LLVM 13
- build ISPC as Universal Binary in GHA CI, as this is what we release. We need to verify that it build for both x86_64 and arm64
> Updates for Github Actions CI

- src/expr.cpp
- tests/lit-tests/2514.ispc
This fixes issue #2514 
```bash
./tests/lit-tests/2514.ispc:11:13: Error: 'varying struct D' has no member named "f"
return d.f;
^^^
./tests/lit-tests/2514.ispc:11:6: Error: Must provide return value for return statement for non-void function.
return d.f;
^^^^^^^^^^^
```
> Fix ICE when postfix expession fetches unknown member

- tests/lit-tests/2514.ispc
By default, output of ISPC is wrapped to some fixed width. When ispc test suite is placed in the relatively short or long path, output is wrapped in a way that can disjoint the search pattern to different lines whereas CHECK is searching for substring on the same line. It may cause fails specific to build/test environment.
> tests: fix 2514.ispc test adding --nowrap

- src/expr.cpp
- src/expr.h
- tests/lit-tests/vector_type_init-1.ispc
- tests/lit-tests/vector_type_init-2.ispc
Support vector type conversions in initialization of short vectors from different types.
Additional fix for #2147
> Support different types in short vector type initialization

- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/module.cpp
- src/module.h
- tests/lit-tests/mcmodel.ispc
Fixes #2530 
Add `--mcmodel` switch, it accepts only `small` and `large` values. `medium` was not added as it requires additional parameter (and additional switch, which is `-mlarge-data-threshold` for clang/gcc) and we don't have request for that. Large model is needed to enable random testing using YARPGen which tends to generate large arrays.
Note, that in LLVM there are two mechanisms for setting Code Model - through `TargetMachine` parameter and as a `Module` metadata. We trigger both mechanisms, even though metadata is not necessary if we control TargetMachine directly. But this is necessary if LLVM IR is used in LTO or manually passed to `llc`.
This PR also contains:
- refactor for `OutputFlags`, this is more explicit (and I believe convenient) way of managing flags and is needed …
> Add --mcmodel switch

- CMakeLists.txt
- cmake/Signing.cmake.in
To sign binaries and libraries, the one need to define `ISPC_SIGN_KEY`, when configuring CMake to build a package.
The signature assumed to work on Windows and macOS. Signing works when building `package` target and is executed after stripping.
> Add signing to CMake

- docker/v1.20.0/centos7_oneapi/Dockerfile
The difference that it uses newer TBB for the build. For OpeAPI `libispcrt_device_cpu.so` depends on `libtbb.so.12`, while in regular distribution it depends on `libtbb.so.2`.
> OneAPI version of v1.20.0 linux package

- src/stmt.cpp
- tests/lit-tests/2544.ispc
It fixes the issue #2544 where user reported ICE on invalid syntax inside `print` arguments.
Parser encounters a recoverable syntax error and proceeds further. However, it breaks some assumption in an assert statement later during the code emitting of print statement. This assert is raised resulting in `abort` call to terminate program.
In this case, we may terminate the compiler with `exit(yynerrs)` adding message saying that the assert can be triggered by the reported syntax error.
```bash
$ ./bin/ispc  --arch=x86-64 --target=avx2 2544.ispc -o 2544.o
2544.ispc:3:33: Error: syntax error, unexpected ':', expecting ')' or ','.
print("sum: %", reduce_add(x:1:0));
^
./src/stmt.cpp:3748: Assertion failed: "!printImplArgs.empty() && "Haven't managed to produce __do_print args"".
***
*** …
```
> Fix ICE on invalid print syntax

- src/stmt.cpp
- tests/lit-tests/2509.ispc
- tests/lit-tests/2544.ispc
This fixes ICE when an initializer expression is malformed, e.g., because of the usage of undeclared symbols, as reported in the issue #2509.
Thanks @mingodad for the suggested fix (https://github.com/ispc/ispc/issues/2509#issuecomment-1556850627)
> Fix ICE when undeclared symbol used in initializer expr

- ispcrt/ispcrt.cpp
- ispcrt/ispcrt.h
The new structure of ISPCRT and the logic of loading symbols ISPCLaunch, ISPCAlloc, ISPCSync from ispcrt_device_cpu solib prevents users of ISPCRT (e.g., OSPRay) from overriding these symbols to integrate their own tasking systems and memory allocation with ISPC.
To address that, ispcrtSetTaskingCallbacks was added and exposed to ISPCRT API. It has three arguments to set ISPCLaunch, ISPCAlloc, ISPCSync implementations.
Fixes #2540.
> ispcrt: add ispcrtSetTaskingCallbacks

- src/expr.cpp
- tests/lit-tests/2341.ispc
> Check rvalue before assign operation

- src/module.cpp
- src/sym.cpp
- src/sym.h
- tests/lit-tests/2523.ispc
This is a fix for #2523. Thanks @mingodad for the idea of the fix.
> Clean up symbol table to avoid assertion in destructor

- benchmarks/01_trivial/07_loop_unroll_varying.cpp
- examples/xpu/CMakeLists.txt
- examples/xpu/aobench/ao.cpp
- examples/xpu/cmake/AddPerfExample.cmake
- examples/xpu/common/L0_helpers.h
- examples/xpu/invoke-sycl-aobench/invoke_sycl_aobench.cpp
- examples/xpu/pipeline-dpcpp/CMakeLists.txt
- examples/xpu/sgemm/CMakeLists.txt
- examples/xpu/sgemm/sgemm.cpp
- examples/xpu/simple-dpcpp-l0/CMakeLists.txt
- examples/xpu/simple-dpcpp-l0/simple-dpcpp-l0.cpp
- ispcrt/cmake/ispcrtConfig.cmake.in
- ispcrt/detail/Device.h
- ispcrt/detail/ModuleOptions.h
- ispcrt/detail/cpu/CPUDevice.cpp
- ispcrt/detail/cpu/CPUDevice.h
- ispcrt/detail/gpu/GPUDevice.cpp
- ispcrt/detail/gpu/GPUDevice.h
- ispcrt/ispcrt.cpp
- ispcrt/ispcrt.h
- ispcrt/ispcrt.hpp
- ispcrt/tests/mock_tests/ispcrt_mock_main.cpp
- src/module.cpp
- superbuild/osPresets.json
- test_static_l0.cpp
ISPC for Xe update including:
1. updated ISPCRT API in regards to `ISPCRTModuleOptions` structure. Now it's a generic object as other ISPC objects like `Module` or `Future`.
2. removed compile-time level-zero dependency from ISPCRT which is not needed anymore after the ISPCRT split to CPU and GPU parts.
3. fixed alignment for device allocations made using `zwMemAllocDevice` L0 API
4. enabled 'newspillcostispc' IGC finalizer option on Windows reducing spill size on Xe targets which leads to up to 70% performance improvement on our target workloads on DG2.
> Updates for Xe targets (20)

- src/lex.ll
- src/parse.yy
There are a few places in `lex.ll` that allocate memory on heap to pass some values to the parser. It should be deallocated. 
Two fields of `yylval` struct are used to pass heap allocated memory from lexer to parser: `std::string *stringVal` and `PragmaAttributes * pragmaAttributes`. The first one is filled in `TOKEN_IDENTIFIER`, `TOKEN_TEMPLATE_NAME`, `TOKEN_TYPE_NAME`, `TOKEN_FLOAT16_CONSTANT `, `TOKEN_INTRINSIC_CALL`, `TOKEN_STRING_LITERAL`. The second one is allocated in `TOKEN_PRAGMA`.
To make `stringVal` memory management identical for all tokens, `operator` rules are made to allocate string as well.
> Deallocate memory allocated in lexer

- src/decl.h
- src/parse.yy
- src/sym.h
After that change, no memory leaks left originated from `parse.yy` on trivial example with stdlib. The fixed allocation is cause of around 2MB in32k allocations. The left part after the fix is around 0.2MB in 2600 allocations.
`Symbol`, `Declaration`, `DeclSpec`, `Declarator`, `StructDeclaration` is freed via bookkeeping (`Tracable`). 
There are also quite a few auxiliary vectors created during parsing that deallocated directly after usage.
> Deallocate memory allocated in parser

- src/type.cpp
- src/type.h
Changes:
*   Add `IsSignedType` and `GetAsSignedType` counterparts to `IsUnsignedType` and `GetAsUnsignedType`.
| `src/type.cpp`, `src/type.h`
> Types: Add IsSignedType and GetAsSignedType methods

- .github/workflows/compiler-warnings.yml
- CMakeLists.txt
- src/ispc.cpp
- src/opt.cpp
This fixes and suppresses GCC warnings, so it is green (https://github.com/nurmukhametov/ispc/actions/runs/5613763085/job/15210488452).
MSVC job with /WX (analogue of -Werror) flag was added also.
> Fix GCC warnings and MSVC /WX build into CI

- .github/workflows/sanitizers.yml
- src/ast.cpp
- src/ast.h
- src/ctx.cpp
- src/ctx.h
- src/ispc.cpp
- src/ispc.h
- src/lex.ll
- src/main.cpp
- src/module.cpp
- src/opt.cpp
- src/parse.yy
- src/sym.cpp
This change let us enable ASAN with leak sanitizer on examples. There are still a few deallocations detected by LSAN On LIT tests and runtime tests.
> Deallocate memory and enable ASAN for examples

- src/ispc.cpp
- src/ispc.h
- src/module.cpp
This is a follow up on the review of PR2575 and fixes #2578.
TargetMachine really belongs to the Target and needs to be destroyed in its destructor.
The cases when it escapes Target lifetime are not legitimate. For the dispatch module we create a new Target anyway and it creates a TargetMachine as well - and this one needs to be used.
This should make the design a little cleaner and reduce memory footprint for multi-target compilation because of earlier release of TargetMachine.
> Destroy TargetMachine in Target destructor.

- src/decl.h
- src/ispc.h
- src/module.h
Some objects (`Target`, `Module`, `StructDeclaration`) own heap-allocated memory. The absence of user-defined copy constructor and assignment operator may lead to memory leak. At the moment, we do not copy them at all, so I think it is just better to delete them.
> Fix missing copy constructor warnings

- alloy.py
- ispcrt/CMakeLists.txt
- src/builtins.cpp
- src/ctx.cpp
- src/ctx.h
- src/expr.cpp
- src/ispc_version.h
- src/module.cpp
- src/opt.cpp
- tests/lit-tests/1470.ispc
- Add `LLVM 17.0` support to `alloy.py`
- Add `LLVM 18.0` definition to ISPC sources
- Bump required CMake version in `ispcrt` to make newest CMake version (3.27) happy
- Fix compile and test problems with LLVM 17.0
This is not all the changes that are required to fully enable LLVM 17.0+. Starting 17.0 opaque pointers must be enabled.
> LLVM 17.0 fixes and LLVM 18.0 definiton

- docker/ubuntu/18.04/cpu_ispc_build/Dockerfile
- docker/ubuntu/20.04/xpu_ispc_build/Dockerfile
This PR fixes two minor hadolint warnings. It also fixes the logic of installing level zero loader of the ubuntu 20.04 docker.  The link to download deb packages of level zero 1.10 for Ubuntu 18.04 doesn't exist, because level zero provides only deb packages for ubuntu 22.04 since around this version.
> Fix dockers

- src/parse.yy
- tests/lit-tests/2472.ispc
Fixes the problem from #2472 that RHS of "." or "->" expression cannot be a typename and should be treated as field name.
> Treat TOKEN_TYPE_NAME as TOKEN_IDENTIFIER in postfix_expression

- docs/ispc.rst
- src/func.cpp
- src/func.h
- src/module.cpp
- src/module.h
- src/parse.yy
- src/sym.h
- tests/func-template-1.ispc
- tests/lit-tests/func_template_not_supported.ispc
- tests/lit-tests/func_template_spec_1.ispc
- tests/lit-tests/func_template_spec_2.ispc
- tests/lit-tests/func_template_spec_3.ispc
- tests/lit-tests/func_template_spec_4.ispc
- tests/lit-tests/func_template_spec_5.ispc
- tests/lit-tests/func_template_spec_6.ispc
Added support of function template specializations with explicit template arguments:
```cpp
// Primary template
template <typename T, typename C> noinline int goo(T argGooOne, C argGooTwo);
// Specialization with explicit template arguments
template <> noinline int goo<int, float>(int argGooOne, float argGooTwo);
// Not supported yet: specialization with implicit template arguments (requires template arguments type deduction)
template <> noinline int goo(int argGooOne, float argGooTwo);
```
> Function template specialization support

- CMakeLists.txt
- ispcrt/CMakeLists.txt
- ispcrt/detail/cpu/CPUDevice.cpp
- ispcrt/detail/cpu/ispc_tasking.cpp
- ispcrt/detail/gpu/GPUDevice.cpp
- ispcrt/ispcrt.cpp
- src/bitcode_lib.cpp
- src/bitcode_lib.h
- src/ispc.cpp
- src/lex.ll
- src/opt/ISPCPass.h
- src/type.cpp
- src/type.h
Enables `-Wextra` that helps to uncover the real bug that has been introduced in https://github.com/nurmukhametov/ispc/commit/e4ea6d7e285d93a690a1bb36ad15c14999f14a61 and fixed in this PR in the commit https://github.com/ispc/ispc/pull/2600/commits/a73bc2b4cd1f62c66bac69542e2210ca60933467
It also contains some fixes to suppress compiler warnings. Most of them look harmless but clean report and enabling `-Wextra` may help fix some problems earlier in the future.
> Enable more compiler warnings

- tests/lit-tests/2514.ispc
- tests/lit-tests/vector_type_convert.ispc
Fix for #2605 
The test was too aggressively optimized on some targets.
> Fixed vector_type_convert.ispc lit test

- docs/ispc.rst
- src/ctx.cpp
- src/ctx.h
- src/expr.cpp
- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/stmt.cpp
- tests/lit-tests/2460_ind-var_promotion.ispc
- tests/lit-tests/foreach-ind-var.ispc
- tests/lit-tests/ind-var-simplify-xe.ispc
- tests/lit-tests/ind-var-simplify.ispc
- tests/lit-tests/loop_unroll_varying.ispc
- tests/lit-tests/signed-integer-overflow.ispc
- tests/lit-tests/wrap-signed-int-xe.ispc
- tests/lit-tests/wrap-signed-int.ispc
Changes:
*   Add test checking for performant loop codegen.
| `tests/lit-tests/loop-codegen-acc-width.ispc`
May close #2460.
> loops: Fix codegen for overflow in signed expressions

- ispcrt/tests/mock_tests/ispcrt_mock_main.cpp
- src/ctx.cpp
- src/opt/MangleOpenCLBuiltins.cpp
- superbuild/osPresets.json
This PR fixes couple of static analysis issues and updates Level zero loader dependency to [1.13.5](https://github.com/oneapi-src/level-zero/releases/tag/v1.13.5).
> Updates for Xe targets (22)

- CMakeLists.txt
The suffix is added to `aarch64` package. Unlike on macOS suffix is not added for `x86_64`, as there multiple users that depend on existing package naming and changing package name would break them.
> Add .aarch64 suffix for package built on AARCH64

- .github/workflows/compiler-warnings.yml
- CMakeLists.txt
- alloy.py
- check_isa.cpp
- ispcrt/CMakeLists.txt
- ispcrt/detail/gpu/GPUDevice.cpp
- ispcrt/ispcrt.cpp
This change enforces `c++17` standard for all projects including `check_isa.cpp`. It also specifies `/EHsc` for MSVC builds to properly enable exception handling. It fixes macro catching invocation in `ispcrt.cpp` and some minor warnings.
This change makes [compiler-warnings](https://github.com/ispc/ispc/actions/workflows/compiler-warnings.yml) green and enables it for pull requests.
> Sanitize MSVC builds and enable compiler-warnings job in CI

- src/module.cpp
Add `uwtable::Default` (which is async) to every function declatarion in the generated module when target OS is Windows. It enables generating unwind table during codegen. The unwind table is needed to generate correct backtrace during debugging and profiling.
It fixes #2345.
> Add uwtable attr to functions when targeting Windows

- docs/ispc.rst
- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/module.cpp
- tests/lit-tests/arg_parsing_errors.ispc
- tests/lit-tests/debug_type_dwarf.ispc
- tests/lit-tests/debug_type_dwarf_2.ispc
- tests/lit-tests/dwarf_version.ispc
This change lets `--dwarf-version=<n>` to force DWARF format debug info generation on Windows. It may be useful when ISPC code is linked with MINGW generated code. In that case, usual DWARF debug section (_debug_info, _debug_line, and etc.) are generated in PE files. This information is used by MINGW GDB during debug on Windows.
It fixes/implements #2129
> Force DWARF generation on windows with --dwarf-version

- src/ctx.cpp
- tests/lit-tests/2628.ispc
The case of input ISPC vector is needed to be supported likewise it is done in, e.g., in NotOperator.
It fixes #2628
> Fix emission code for FNeg instruction

- docker/centos/7/xpu_ispc_build/Dockerfile
- docker/centos/7/xpu_ispc_build/oneAPI.repo
Support via `build-arg TBB=<default|oneapi>` parameter building `ISPC` both with system tbb and oneapi-tbb.
> centos/7/xpu_docker: support both tbb and oneapi-tbb

- superbuild/CMakeLists.txt
- superbuild/README.md
This PR supports macOS in superbuild CMake. It supports universal binaries generation with `-DMACOS_UNIVERSAL_BIN=ON`.
> Support macOS in superbuild

- .github/workflows/snap.yml
- snap/snapcraft.yaml
This PR extends snap CI job to build and publish both `amd64` and `arm64` snap packages. `snapcraft.yml` is a template file with placeholders `@ISPC_VERSION@` (package version) and `@ISPC_ARCHIVE@` (link to the release tarball). They are changed by CI job to actual values that provided on every run. It also introduces input option `publish`.
Run of this updated job that published `arm64` package [here](https://github.com/ispc/ispc/actions/runs/6015634834/job/16317903458).
> snap: configure job to support packaging both amd64 and arm64

- src/expr.cpp
- src/func.cpp
- src/func.h
- src/module.cpp
- src/module.h
- src/parse.yy
- src/sym.cpp
- src/sym.h
- tests/lit-tests/func_template_1.ispc
- tests/lit-tests/func_template_11.ispc
- tests/lit-tests/func_template_2.ispc
- tests/lit-tests/func_template_6.ispc
- tests/lit-tests/func_template_spec_1.ispc
- tests/lit-tests/func_template_spec_2.ispc
- Produce error when template is used with `extern "C"`/ `extern "SYCL"`
- Fixed storage class for templates, so it's now extern by default as for regular ISPC functions
- Fixed linkage for different types of template instantiations (aligned with Clang behavior)
> Fix function specifiers for templates

- src/expr.cpp
- tests/lit-tests/func_template_operator_1.ispc
- tests/lit-tests/func_template_operator_not_supported_1.ispc
- tests/lit-tests/func_template_operator_not_supported_2.ispc
Depends on https://github.com/ispc/ispc/pull/2641.
Introduces basic template support for operators.
Explicit instantiations and specializations are not supported yet.
Fixes #2634 .
> Support of template operators

- docs/ispc.rst
- src/expr.cpp
- src/func.cpp
- src/func.h
- src/module.cpp
- src/module.h
- src/parse.yy
- src/sym.h
- src/type.cpp
- src/type.h
- tests/lit-tests/func_template_inst_1.ispc
- tests/lit-tests/func_template_spec_7.ispc
This PR fixes and aligns usage of different function specifiers (storage class, inline hints, unmasked keyword etc) for template specializations and instantiations.  
* The keywords ``export``, ``task``, ``typedef``, ``extern "C"`` and ``extern "SYCL"``
are not allowed.
* Calling conventions such as ``__vectorcall`` and ``__regcall`` must be used in conjunction
with ``extern "C"`` or ``extern "SYCL"``, so they are not allowed as well.
* Performance hints like ``inline`` and ``noinline`` are allowed. Primary template, template
specializations and explicit instantiations may have different ``inline`` hints.
* Storage types ``extern`` and ``static`` are allowed. Template specializations and explicit
instantiations must share the same storage type as the primary template.
If not specified, …
> Function specifiers for template specializations and instantiations 

- CMakeLists.txt
- src/ctx.cpp
- src/expr.cpp
- src/ispc.cpp
- src/opt/CheckIRForXeTarget.cpp
- src/opt/XeGatherCoalescePass.cpp
- tests/lit-tests/load_store_vectorizer_loopunroll.ispc
- tests/lit-tests/xe_assert.ispc
- tests/lit-tests/xe_gather_coalescing.ispc
- tests/lit-tests/xe_gather_coalescing_loop.ispc
- tests/lit-tests/xe_gather_coalescing_ptr_alloca.ispc
- tests/lit-tests/xe_gather_test.ispc
- tests/lit-tests/xe_invoke_sycl.ispc
- tests/lit-tests/xe_kernels_spec.ispc
- tests/lit-tests/xe_kernels_spec_addrspace.ispc
- tests/lit-tests/xe_regcall-1.ispc
This PR fixes ISPC build with LLVM 17.0 and lit-tests (https://github.com/ispc/ispc/issues/2633).
Support of LLVM 17.0 is not fully ready, some tests and workloads are failing currently.
> Fixes for Xe-enabled build with LLVM 17

- .github/workflows/ispc-ci.yml
- CMakeLists.txt
Switch ISPC_PACKAGE_EXAMPLES allows to enable/disable packaging examples into ISPC archive. Default is ON.
Add custom target `package-examples` to package them into separate archive from ISPC itself.
> cmake: add switch to opt out examples from package

- src/util.cpp
This fixes build error on macOS like this [here](https://github.com/ispc/ispc/actions/runs/6333187132/job/17200927555)
```bash
Undefined symbols for architecture x86_64:
"std::__1::__libcpp_verbose_abort(char const*, ...)", referenced from:
```
> Provide own definition of __libcpp_verbose_abort

- .github/workflows/snap.yml
- snap/snapcraft.yaml
It allows snap packaged ISPC to access files in the user home directory.
It also adds step to upload the snap package as artifact in CI snap job .
It also add an option to choose the channel to publish snap to.
This fixes #2665
> snap: add home plugs

- check_isa.cpp
- src/ispc.cpp
currently, if you attempt to compile ispc on a host which is not x86_64 or arm, the build fails on inline assembly directives, with the reason why being potentially non-obvious. for example:
```
linear@mihari:~/code/ispc/build $ uname -m
ppc64le
linear@mihari:~/code/ispc/build $ make
[  1%] Building CXX object CMakeFiles/check_isa.dir/check_isa.cpp.o
/usr/people/linear/code/ispc/check_isa.cpp:25:36: error: invalid output constraint '=a' in asm
__asm__ __volatile__("cpuid" : "=a"(info[0]), "=b"(info[1]), "=c"(info[2]), "=d"(info[3]) : "0"(infoType));
^
/usr/people/linear/code/ispc/check_isa.cpp:29:36: error: invalid output constraint '=a' in asm
__asm__ __volatile__("cpuid" : "=a"(info[0]), "=b"(info[1]), "=c"(info[2]), "=d"(info[3]) : "0"(level), "2"(count));
^ …
```
> check_isa.cpp, ispc.cpp: do not assume "not arm" means "x86_64"

- ispcrt/cmake/Finddpcpp_compiler.cmake
The first thing, oneAPI changed the layout of llvm-utilities so make the corresponding change by providing extra subfolders as hints where to find them.
The second one, on Windows oneAPI provides sycl libraries with version in name, e.g., sycl6.dll, sycl7.dll and etc.. Add versioned name in find_labrary to be able to find them.
> interop: fix find dpcpp_compiler logic

- .github/workflows/ispc-ci.yml
- CMakeLists.txt
- tests/lit-tests/lit.cfg
This PR fixes the failing jobs in Test pipeline on windows (like [here]( https://github.com/ispc/ispc/actions/runs/6563815552/job/17828914206)) and skips xe-tests jobs in `full` run of this pipeline.
Jobs started  to fail because GitHub Windows runners updated python version up to 3.12.
test/lit-tests/lit.cfg [imports](https://github.com/ispc/ispc/blob/163b9904ed893d279908c8123e52597fd1b627c8/tests/lit-tests/lit.cfg#L5) distutils package that is deprecated and removed since python 3.12. GitHub Windows runners updated their environment to include 3.12 version.
We may use different package, e.g., packaging, but we need to install it. Windows GitHub runner images have quite strange environment where there are several python installations. I didn't manage to force pip to install packaging …
> Fix CI and skip xe builds for full tests

- .github/workflows/ispc-ci.yml
- alloy.py
This PR fixes two issues with the full Tests pipeline:
1. Full Test pipeline has strange failures and hangs for win-tests on x86 avx1 targets. It is caused by misconfiguration in alloy.py code that resulted in same tests had been run twice: the first time natively on hardware, the second time in SDE. Targets after AVX1.1 have to include both AVX and AVX1.1 otherwise one of them will run under SDE.
2. LLVM14 tests jobs are matrix and have to be run with matrix arguments.
> Fix stability runs

- src/opt.cpp
- tests/lit-tests/blend-curves-loop.ispc
Before v1.20.0, ISPC used LoopUnswitch that was removed and changed by SimpleLoopUnswitch in LLVM 15. However, it stops to optimize by default loops like this:
```
export void foo(const uniform uint32 input[], uniform uint32 output[],
const uniform int index)
{
foreach (i = 0 ... 32) {
if (index == 0) {
output[i] = input[i];
} else {
output[i] |= input[i];
}
}
}
```
To turn on unswithcing for this loop with SimpleLoopUnswitch, we need to enable unswitching of untrivial loops with --enable-nontrivial-unswitch.
> Enable nontrivial unswitch in Simple Loop Unswitch

- .appveyor.yml
This PR fixes appveyor jobs that have recently updated python up to 3.12.
It is similar to problem fixed in https://github.com/ispc/ispc/pull/2685/commits/1f7ac4752ff4700f80961ee5b30714fb7b60906d
> CI: run check_env.py with python 3.11 in appveyor

- src/stmt.cpp
- tests/lit-tests/2333.ispc
- tests/lit-tests/init-const-arrays.ispc
- tests/lit-tests/init-const-varying.ispc
- tests/lit-tests/init-const-vectors.ispc
This PR fixes #2333 and similar crashes with initalization of bool vectors and arrays. 
Code generating static const declaration should match an InitSymbol behaviour that was changed in the commit https://github.com/ispc/ispc/commit/c889cdee2b5c7ebe. The generated constants stored in memory so we should generate storage type bools and bool vectors.
Add also tests for different initialization cases (varying, vector, arrays).
> Fix static const declaration of bool types

- tests/lit-tests/2652_3.ispc
- tests/lit-tests/header-bool-1.ispc
- tests/lit-tests/header-ref-1.ispc
- tests/lit-tests/header-ref-2.ispc
It may have universal binaries that may cause failing due to arm64/x86_64 mess.
> tests: do not run some tests on macOS

- src/expr.cpp
- src/type.cpp
- src/type.h
- tests/lit-tests/2689-2.ispc
- tests/lit-tests/2689-3.ispc
- tests/lit-tests/2689.ispc
- tests/lit-tests/bool-casts-varying.ispc
- tests/lit-tests/bool-casts-vectors.ispc
- tests/lit-tests/bool-store-varying.ispc
- tests/lit-tests/bool-store-vector.ispc
This PR fixes #2689.
ISPC generated a cast like this:
```c
%19 = sext <4 x i1> %18 to <8 x i1>, !dbg !24061
```
by this https://github.com/ispc/ispc/blob/5725fb8d495980af52b417ae0c7a89e2a258d2bd/src/expr.cpp#L6494
`LLVMTypes::Int1VectorType` always has target width whereas short vector length can be different.
> Fix casting of bool short vectors to numeric ones

- src/expr.cpp
- tests/lit-tests/bool_swizzle.ispc
This PR fixes #2367 
StoreInst expects value type as third argument not type of pointer to value. Otherwise, the code inside casting bool is meaningless because PointerType can't be bool. Moreover, other use cases shows that the third argument is just type of the value passed as the first argument. I don't know why argument name is so confusing here.
> Fix bool swizzles

- docker/centos/7/cpu_ispc_build/Dockerfile
- docker/centos/7/xpu_ispc_build/Dockerfile
- docker/centos/8/cpu_ispc_build/Dockerfile
- docker/ubuntu/20.04/cpu_ispc_build/Dockerfile
- docker/ubuntu/20.04/xpu_ispc_build/Dockerfile
- docker/ubuntu/22.04/cpu_ispc_build/Dockerfile
- docker/ubuntu/22.04/xpu_ispc_build/Dockerfile
This PR changes dockers to use superbuild to build ISPC and all dependencies. It also fixes minor hadolint warnings.
> Migrate dockers to superbuild

- llvm_patches/14_0_15_0_16_0_17_0_dbghelp_mitigation.patch
This PR limits the amount of paths that searched for DLL dependencies during run-time.
> Harden dll loading process

- src/lex.ll
This fixes #2706.
When bison is used in `-y` mode that emulates POSIX Yacc, tokens are defined as enums (under `YYTOKENTYPE` ifdef) or as `int` via macro definitions. Defining return type as `yytokentype` causes compile error: invalid conversion from 'int' to 'yytokentype'. To avoid it, return `int` as we do with `lParseInteger` and `lParseFP`.
> Fix return type of lParseOperator

- .github/workflows/scripts/install-build-deps.ps1
- .github/workflows/scripts/install-test-deps.ps1
This PR fixes CI errors on windows caused by renaming the `Choco-Install` command to `Install-ChocoPackage`  https://github.com/actions/runner-images/pull/8865
> CI: rename Choco-Install to Install-ChocoPackage

- CMakeLists.txt
The version 1.22.0 is not [reproducible](https://reproducible-builds.org/) because the binary prints the build time which depends on time zone (see [here](https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/ispc.html) for Debian package version 1.22.0-3 for example).
Adding the `UTC` keyword in the CMake command seems to fix the issue. Let me know if this is an acceptable solution.
Thanks!
François
> Use UTC with timestamp to help reproducible build.

- .github/workflows/rebuild-llvm14.yml
- .github/workflows/rebuild-llvm15.yml
- .github/workflows/rebuild-llvm16.yml
- .github/workflows/rebuild-llvm17.yml
- .github/workflows/reusable.rebuild.yml
- docker/ubuntu/18.04/cpu_ispc_build/Dockerfile
This PR allows to build LTO-enabled LLVM. Although, linux arm64 and x86_64 Release+Asserts builds hit time limit in CI ([job](https://github.com/ispc/ispc/actions/runs/7114600586)).
> Add LTO swtich to rebuild LLVM job

- .github/workflows/compiler-warnings.yml
- .github/workflows/copyright-check.yml
- .github/workflows/docs.yml
- .github/workflows/format-check.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-benchmarks.yml
- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/nightly-16.yml
- .github/workflows/rebuild-llvm14.yml
- .github/workflows/rebuild-llvm15.yml
- .github/workflows/rebuild-llvm16.yml
- .github/workflows/rebuild-llvm17.yml
- .github/workflows/reusable.rebuild.yml
- .github/workflows/sanitizers.yml
- .github/workflows/snap.yml
This PR restricts token permissions used by CI pipelines. It should fix #2732.
It also updates SDE version because the previous one is not accessible anymore.
> CI: set read-all permissions

- .github/workflows/rebuild-llvm16.yml
- llvm_patches/16_0_AArch64-Disable-loop-alignment-for-Windows-targets.patch
Backport LLVM patch [#6ae36c01272](https://github.com/llvm/llvm-project/commit/6ae36c01272) to fix the issue #2713. It requires the rebuild of LLVM. The regression test will be committed later in different PR after LLVM 16 update in CI.
> Disable loop alignment for Windows aarch64 targets

- check_copyright.sh
- docs/ispc.rst
- src/module.cpp
- tests/lit-tests/2738.ispc
- tests/lit-tests/2738_arith_exprs.ispc
- tests/lit-tests/2738_cast_types.ispc
- tests/lit-tests/2738_mixed_types.ispc
- tests/lit-tests/2738_one_init.ispc
- tests/lit-tests/2738_partial_init.ispc
Allow to use arithmetic expression with const int varying initialized by list initializer with constants.
This fixes #2738
> Improve const int varying initialization

- tests/lit-tests/2713.ispc
This PR contains a regression test for issue #2713. We need to wait until LLVM rebuild happens (after merge PR[#2749](https://github.com/ispc/ispc/pull/2749)) to check that everything works as expected.
> tests: add reproducer for #2713

- src/ctx.cpp
- tests/lit-tests/2752-1.ispc
- tests/lit-tests/2752.ispc
- tests/lit-tests/2753.ispc
- tests/lit-tests/bool-store-varying.ispc
- tests/lit-tests/lit.cfg
This PR fixes ABI incompatibility of `bool` type covered by issues #2752, #2753 that were introduced in 1.13 release by commit #https://github.com/ispc/ispc/commit/c889cdee2b5c7ebecb2f159b3173ea22f4318474. That commit split `bool` type to two different representations (internal corresponding to mask and in-memory/storage corresponding to C/C++). Storage representation of `bool` has to comply with ABI not only about their size but about their values either. We need to zero extend values when converting boolean values for storage representation.
Copied from comments:
Internal representation of bool matches mask behavior that requires `true` value to be `-1`. It is an implication of some instruction requirements, e.g., `blendvps` (the most significant bit should be 1). Whereas, storage …
> Zero extend bool values for storage representation

- src/expr.cpp
- src/expr.h
- tests/lit-tests/2754-1.ispc
- tests/lit-tests/2754.ispc
This PR allows to use select expr (ternary operator) as lvalue, e.g., dereference it. This fixes #2754
> Allow select expr to be a lvalue

- superbuild/CMakeLists.txt
Do not pack examples by default to ISPC archive.
> superbuild: change ISPC_PACKAGE_EXAMPLES to OFF

- tests/lit-tests/2752.ispc
- tests/lit-tests/2753.ispc
- tests/lit-tests/bool-store-vector.ispc
Do not try to match x86 asm when arm asm generated. I think we need to create CI jobs that will run tests on `aarch64` worker that we have in our CI to avoid this in future.
When `host` can generate both `x86` and `asm` it is not clear how to distinguish when host is arm target when it is not (especially minding that universal binary contains both), so `X86_ENABLED && !ARM_ENABLED` is used. We need to figure out that properly later.
`bool-store-vector.ispc` checks that ISPC sign extends `i1` for internal `bool` representation. I am not sure whether there is a requirement of internal `true` to be `-1` for `arm`, but it looks like ISPC matched their behavior before. We need to figure out that later.
> lit-tests: adjust tests for arm

- src/opt/ImproveMemoryOps.cpp
- src/opt/ReplacePseudoMemoryOps.cpp
This PR fixes the pattern of searching for function call replacement rules in `ImproveMemoryOps.cpp` and `ReplacePseudoMemoryOps.cpp`. They used an array that created and searched for to match called function upon every call visit.
This fix introduces an unordered_map instead. It is created once and used to lookup called function more efficiently. As a result, ISPC works a few percent faster.
This PR depends on #2771 and #2772
> Fix function lookup

- src/expr.cpp
- src/expr.h
- src/func.cpp
- src/func.h
- src/ispc.h
- src/module.cpp
- src/module.h
- src/parse.yy
- src/type.cpp
- src/type.h
Refactor TemplateArgs to support non-type parameters:
1. Wrap `std::pair<const Type *, SourcePos>` to `TemplateArg`
2. Wrap `std::vector<std::pair<const Type *, SourcePos>>` to `TemplateArgs`
`TemplateArg` will be extended with NonType arguments in a separate PR.
> Refactor TemplateArgs to support non-type parameters

- llvm_patches/16_0_17_0-X86-getFauxShuffleMask-handle-fp-int-bitcast.patch
- tests/lit-tests/2777.ispc
This backported patch fixes generation of redundant vmovd, vpinsrd instructions.
Test case added as XFAIL until LLVM rebuild in CI.
It resolves issue #2777
> llvm_patches: add x86-isel fix

- CMakeLists.txt
Remove `-fdata-sections`, `-ffunction-sections` and `-Wl,--gc-sections` from builds with debug info to avoid removal of unused methods which might be useful for debugging purposes like `Print()`.
Related to discussion https://github.com/ispc/ispc/pull/2789#discussion_r1523138858
> Fix security options for Debug build

- src/expr.cpp
- src/expr.h
- src/func.cpp
- src/func.h
- src/ispc.h
- src/parse.yy
This PR includes 3 changes:
1. Adding `Mangle()` method to `Expr` which is needed to produce mangled names of template functions with non-type parameters.
2. Encapsulation of template parameters logic in `TemplateParam` class
3. Support of non-type template arguments.
> Prerequisite changes for templates with non-type parameters support

- src/module.cpp
- src/opt.cpp
This PR removes `alloca` usage as requested here https://github.com/ispc/ispc/pull/2788#discussion_r1521970362
It also removes unused its declaration in `src/opt.cpp`. There is one more left in `src/util.cpp` - I'm not sure if it is worth changing it.
> Replace alloca with heap allocation

- src/ast.cpp
- src/ast.h
It is needed to avoid name conflict that happens with overloaded virtual method Print(Indent). Debuggers struggle (at least gdb) to resolve it.
This fixes #2805
> Rename Print() method for debuggers

- src/ctx.cpp
- src/ctx.h
- src/expr.cpp
- tests/lit-tests/2799.ispc
Storage and internal bool types can have same type width, so use extra flag to choose the proper sign/zero extension mode.
This PR fixes #2799
> SwitchBoolSize: distinguish bool type by argument

- .github/workflows/rebuild-llvm17.yml
- .github/workflows/reusable.rebuild.yml
- superbuild/CMakeLists.txt
This PR fixes path to `clang_rt.profile.lib` in superbuild.
It also updates name of LLVM artifacts with `-lto` for reusable build triggered with `LTO=ON`. The minor thing is to provide defaults for reusable builds.
> Fix path to clang_rt.profile library

- .github/workflows/ispc-ci.yml
This PR also splits x86 and x86-64 linux jobs to different one matrix jobs.
As a result, we will be able to see the logs with the real issues that sometimes are unclear to reproduce locally.
> CI: upload alloy_results logs on failure

- builtins/target-avx2-i16x16.ll
- builtins/target-avx2-i8x32.ll
- builtins/target-avx512-common-16.ll
- builtins/target-avx512-common-4.ll
- builtins/target-avx512-common-8.ll
- builtins/target-avx512skx-x32.ll
- builtins/target-avx512skx-x64.ll
- builtins/target-avx512spr-x32.ll
- builtins/target-avx512spr-x64.ll
- builtins/util.m4
- docs/ispc.rst
- tests/lit-tests/2780-1.ispc
- tests/lit-tests/2780.ispc
- tests/lit-tests/fp16_code_gen.ispc
Make all implementations of __round_varying across different targets and types to actually do roundeven.
This PR fixes #2780
> builtins: align all implementations of __round_varying

- .github/workflows/compiler-warnings.yml
- .github/workflows/copyright-check.yml
- .github/workflows/docs.yml
- .github/workflows/format-check.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-benchmarks.yml
- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/nightly-16.yml
- .github/workflows/reusable.rebuild.yml
- .github/workflows/sanitizers.yml
- .github/workflows/snap.yml
It is needed because of the warning: "Please update the following actions to use Node.js 20"
This PR fixes #2819
> CI: update actions

- src/opt/ImproveMemoryOps.cpp
After LLVM change [d77067d08](https://github.com/llvm/llvm-project/commit/d77067d08), InstCombine substitutes 
```llvm-ir
%v2 = sext <4 x i32> %v1 to <4 x i64>
```
with
```llvm-ir
%v2 = zext nneg <4 x i32> %v1 to <4 x i64>
```
`lOffsets32BitSafe` should consider `zext` too to be able to replace `__pseudo_scatter64_i32` with `__pseudo_scatter_factored_base_offsets32_i32`. Otherwise, it replaces it with `__pseudo_scatter_factored_base_offsets32_i32` that somehow results in generation of `vunpckhps`.
This fixes https://github.com/ispc/ispc/blob/main/tests/lit-tests/interleaved.ispc (issue #2813) with LLVM 18.1.
> ImproveMemOps: consider zext in lOffsets32BitSafe

- src/func.cpp
- src/llvmutil.cpp
- src/llvmutil.h
- src/module.cpp
- tests/lit-tests/2839-1.ispc
- tests/lit-tests/2839-2.ispc
- tests/lit-tests/2839.ispc
ISPC has several places where LLVM functions created. We need to add the uwtable attribute in all of them to genereate unwind info under Windows.
Initial PR https://github.com/ispc/ispc/pull/2630 with uwtable attr did that only for internal copy of exported functions, and completely missed this attribute for template instantiations and dispatch functions.
This PR fixes #2839
> Add uwtable attr to all created functions

- CMakeLists.txt
- src/opt.cpp
- src/opt/ISPCPassRegistry.def
- src/opt/ISPCPasses.h
- src/opt/ReplaceMaskedMemOps.cpp
- src/opt/ReplaceMaskedMemOps.h
- tests/lit-tests/2611-2.ispc
- tests/lit-tests/2611-3.ispc
- tests/lit-tests/2611-4.ispc
- tests/lit-tests/2611-align.ispc
- tests/lit-tests/2611.ispc
- tests/lit-tests/2611.ll
- tests/lit-tests/2719.ispc
- tests/lit-tests/ispc-opt.ll
It traverses bitcode for masked stores that have the turned-off second part and the turned-on first part. We can safely replace them with narrow unmasked stores and loads with the following shuffle with the passthrough value. This can help the back-end to generate better code (no extra spills, assigning narrow registers).
This fixes that last part of issue https://github.com/ispc/ispc/issues/2611
> opt: add ReplaceMaskedMemOps pass

- docs/ispc.rst
- docs/template-perf.txt
When I generated docs for `ispc.github.io`, I fixed in a few places quotes and wrapped lines to fit code snippets. I have also removed javascript analytics from `template-perf.txt`.
> Minor docs fix

- .devcontainer/devcontainer.json
It also updates the base image up to `ubuntu22.04` to be able to run clang from ispc.dependencies.
> Fix devcontainer build deps

- builtins/target-avx512-common-16.ll
- tests/lit-tests/2866.ispc
> builtins: remove transcendental definitions from avx512-common-16

- docs/ispc.rst
- src/main.cpp
- tests/lit-tests/knl-deprecation.ispc
This is to address #2867. It just adds a warning when avx512knl-x16 target is used.
> Deprecate avx512knl-x16 target

- .appveyor.yml
- .github/workflows/compiler-warnings.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/nightly-17.yml
- .github/workflows/rebuild-llvm15.yml
- .github/workflows/rebuild-llvm16.yml
- .github/workflows/rebuild-llvm17.yml
- .github/workflows/rebuild-llvm18.yml
- .github/workflows/reusable.rebuild.yml
- .github/workflows/sanitizers.yml
- docker/ubuntu/22.04/cpu_ispc_build/Dockerfile
Build Clang/LLVM in same ubuntu as ISPC to avoid issues with linking to different `libstdc++` versions. See #2892 and #2877 for context.
> Use same image to build Clang/LLVM and ISPC

- .devcontainer/devcontainer.json
- .github/workflows/scripts/install-build-deps-aarch64.sh
- .github/workflows/scripts/install-build-deps.sh
- CMakeLists.txt
- docker/centos/7/cpu_ispc_build/Dockerfile
- docker/centos/7/xpu_ispc_build/Dockerfile
- docker/centos/8/cpu_ispc_build/Dockerfile
- docker/ubuntu/16.04/cpu_ispc_build/Dockerfile
- docker/ubuntu/18.04/cpu_ispc_build/Dockerfile
- docker/ubuntu/20.04/cpu_ispc_build/Dockerfile
- docker/ubuntu/20.04/xpu_ispc_build/Dockerfile
- docker/ubuntu/22.04/cpu_ispc_build/Dockerfile
- docker/ubuntu/22.04/xpu_ispc_build/Dockerfile
- third-party-programs.txt
This fixes #2855.
This PR:
1. Remove installation of libncurses and libtinfo in docker/CI/devcontainers.
2. Remove CMake logic to find them.
3. Remove the license entry from `third-party-programs.txt`
> Finalize removing of ncurses/terminfo dependency

- src/decl.cpp
- tests/lit-tests/err-export-1.ispc
- tests/lit-tests/err-inline.ispc
- tests/lit-tests/err-noinline.ispc
- tests/lit-tests/err-task.ispc
- tests/lit-tests/err-unmasked.ispc
This PR fixes #2835.
It fixes the reporting logic for cases when unsuited qualifiers provided for variable declarations.
> Report error when var declarations have incompatible type specifiers

- stdlib.ispc
All of them caused by unbound casting diagnostic.
Under `--debug` there are quite a few errors reported: E.g., on atomic swaps, ispc reported:
```bash
Error: Unable to find any matching overload for call to function (/*unbound*/ int64 * uniform, varying int64)
```
This PR allows to use `--debug` for compilation with enabled stdlib.
> stdlib: fix compilation errors in stdlib

- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/linux-nightly-trunk.yml
- CMakeLists.txt
- tests/lit-tests/1323_1.ispc
- tests/lit-tests/1323_2.ispc
- tests/lit-tests/1408.ispc
- tests/lit-tests/1469.ispc
- tests/lit-tests/1470.ispc
- tests/lit-tests/1608.ispc
- tests/lit-tests/1609.ispc
- tests/lit-tests/1963.ispc
- tests/lit-tests/2134.ispc
- tests/lit-tests/check_dispatch.ispc
- tests/lit-tests/cpus_x86.ispc
- tests/lit-tests/deps.ispc
- tests/lit-tests/disable_gather_scatter.ispc
- tests/lit-tests/dispatch.ispc
- tests/lit-tests/gatherScaleConst.ispc
- tests/lit-tests/gather_scatter.ispc
- tests/lit-tests/knl-deprecation.ispc
- tests/lit-tests/lit.cfg
- tests/lit-tests/nested_response_files.args
- tests/lit-tests/perf-warnings.ispc
- tests/lit-tests/targets_x86.ispc
Remove KNL targets from lit-tests, full testing and trunk testing.
Addresses https://github.com/ispc/ispc/issues/2867#issuecomment-2228893891
I don't want to remove the target completely right now, it should go through deprecation. It's the right approach to communicate about changed targets to users. However (since it's deprecated) we can stop testing it.
> KNL targets partial removal

- .github/workflows/coverity.yml
- .github/workflows/scripts/run-coverity.sh
Our Coverity open source project is set up here: https://scan.coverity.com/projects/intel-ispc?tab=overview.
Open source Coverity has limitations on number of runs: https://scan.coverity.com/faq#frequency so I'm setting it to run by schedule or on workflow_dispatch.
Here is example run: https://github.com/aneshlya/ispc/actions/runs/9998651864
Feel free to contribute to this PR if you think something is missing.
> ci: add coverity scans

- .github/workflows/coverity.yml
- .github/workflows/trivy.yml
- .trivyignore
Security scan for Dockerfiles.
Dockerfiles from released versions are ignored (unfortunately trivy actions doesn't accept regular expressions in`skip-dirs`).
The result of scanning will be availble in Security tab once PR merged. The example of how it look like:
> Trivy scan

- docs/ispc.rst
Hello,
I found that the documentation is not up to date about the doc about the `lanemask` intrinsic. Here is a (minor) quick fix.
> Fix the return type of lanemask in the doc

- src/util.cpp
It is needed when we build with libc++.
Commit this patch as separate PR as requested here: https://github.com/ispc/ispc/pull/2892#pullrequestreview-2208334079
> Declare libcpp_verbose_abort on Linux also

- .appveyor.yml
- .github/workflows/clamav-release.yml
- .github/workflows/clamav.yml
It adds a job to scan trunk archives with ClamAV.
This partially addresses #2913.
This PR also fixes appveyor build for Linux that was broken after https://github.com/ispc/ispc/pull/2894
> CI: add ClamAV scan job

- src/ispc.cpp
- src/ispc.h
- src/lex.ll
- src/main.cpp
- src/sym.cpp
- src/sym.h
This PR removes `--fuzz-target` and `--fuzz-seed=<int>` developer functionality. It is not used anymore. It will eventually be replaced by fuzzing with external tools.
> lexer: remove self-fuzzing functionality

- docs/ispc.rst
- src/decl.cpp
- src/decl.h
- src/expr.cpp
- src/lex.ll
- src/module.cpp
- src/module.h
- src/parse.yy
- src/type.cpp
- src/type.h
- tests/lit-tests/address-space-1.ispc
- tests/lit-tests/address-space.ispc
- tests/lit-tests/ast-dump-attrs.ispc
- tests/lit-tests/err-address-space.ispc
- tests/lit-tests/err-attribute.ispc
- tests/lit-tests/err-noescape.ispc
- tests/lit-tests/noescape-1.ispc
- tests/lit-tests/noescape.ispc
- tests/lit-tests/warn-attribute-1.ispc
- tests/lit-tests/warn-attribute.ispc
- tests/lit-tests/warn-noescape.ispc
Supported syntaxes:
- `__attribute__((attr))`
- `__attribute__((attr(2)))`
- `__attribute__((attr("str")))`
They can be placed on variable declarations (local, global, parameters) and function declaration/definitions.
Placing them on struct declarations is not supported yet.
> Support __attribute__ syntax.

- .github/workflows/ispc-ci.yml
- superbuild/CMakeLists.txt
Fixes #2818, #2931 
- Don't run CI jobs that fail due to SDE failing on AMD runner on Linux x86 (32 bit)
- Don't run jobs for self-hosted runners in forks
- Add `libunwind` for LLVM 18.0+ build on macOS via superbuild.
- Fix artifact name for `aarch64` Linux build job - otherwise a warning generated and no artifact is uploaded.
> Fixes for LLVM mac builds and CI

- benchmarks/cmake/AddBenchmark.cmake
- Add `-mavx2` switch for benchmarks only on x86 - so it can work on ARM. I'm not sure why it was there in the first place, but currently I don't have x86 machine handy to check what will happen if it's removed.
- Update Google Benchmark `v1.8.3` -> `v1.8.5`.
> Fix Benchmarks for ARM

- stdlib.ispc
Hello.
This PR fix an overflow in the exp implementation previously resulting in bad results for -Inf, NaN and big numbers (especially due to an integer overflow). The implementation is now 100% valid with a relative precision of <5 ULP for normal numbers (possibly much more for subnormal numbers).
It was initially a part of the PR #2937 .
> stdlib: fix overflow in exp(float) and exp(uniform float)

- docs/ispc.rst
Hello,
As he name of the PR suggest, it fixes minor typo / English mistakes.
By the way, please note that there is a surprising "XXXX todo" in the performance guide (even [visible online](https://ispc.github.io/perfguide.html#understanding-memory-read-coalescing)).
> docs: fix English typo/mistakes

- builtins/target-avx1-i64x4base.ll
- builtins/target-avx2-common-i32x4.ll
- builtins/target-avx2-common-i32x8.ll
Extracted from https://github.com/ispc/ispc/pull/2743.
It's not related to targets redesign. It happened after https://github.com/ispc/ispc/pull/2924 because I changed the interface in the last moment and forgot to remove `internal` in several places.
-------------------------------------------------------------------
1. It doesn't match with other __shuffle_* definitions in other files.
2. The more important thing is the following one. After the target redesign, builtins module is linked into the stdlib^. It means that no builtin function used in stdlib.ispc should be defined with internal attribute (C static keyword). Otherwise, the linker gets rid of __shuffle_ from builtins instead of resolving __shuffle_ symbol used in stdlib. It would result into unresolved symbol. Only functions …
> builtins: remove internal from __shuffle_*

- .github/workflows/yarpgen.yml
The second checkout action is overriding the directory created by first one (somehow not always).
This PR fixes this problem.
> ci: fix yarpgen workflow

- .github/workflows/linux-nightly-trunk.yml
- .github/workflows/nightly-17.yml
- builtins/target-avx512-common-16.ll
- builtins/target-avx512icl-x16.ll
- builtins/target-avx512knl-x16.ll
- builtins/target-avx512skx-x16.ll
- builtins/target-avx512spr-x16.ll
- examples/cpu/aobench/CMakeLists.txt
- examples/cpu/deferred/CMakeLists.txt
- examples/cpu/mandelbrot/CMakeLists.txt
- examples/cpu/mandelbrot_tasks/CMakeLists.txt
- examples/cpu/noise/CMakeLists.txt
- examples/cpu/options/CMakeLists.txt
- examples/cpu/rt/CMakeLists.txt
- examples/cpu/sgemm/CMakeLists.txt
- examples/cpu/sort/CMakeLists.txt
- examples/cpu/stencil/CMakeLists.txt
- examples/cpu/volume_rendering/CMakeLists.txt
- examples/xpu/mandelbrot/CMakeLists.txt
- tests/lit-tests/fp16_code_gen.ispc
- tests/lit-tests/interleaved.ispc
- tests/lit-tests/lit.cfg
- tests/lit-tests/loop_unroll_varying.ispc
- tests/lit-tests/signed-integer-overflow.ispc
1. Fixed lit tests for LLVM 19+ build unlocking the testing in CI
2. Skip avx512 targets on x86 target in nightly and trunk testing.
3. Remove LLVM rebuild in nightly LLVM 17.0 testing. BTW I'm not fully understand why do we need this workflow at all, this testing is covered by ispc-ci.yml
4. Fixed shuffles for avx512-knl targets (deprecated, not tested anywhere except nightly 17.0 testing)
> Fixes for LLVM 19 build and nightly testing

- src/opt.cpp
- src/opt/ReplaceMaskedMemOps.cpp
- tests/lit-tests/2611.ll
- tests/lit-tests/2955.ispc
- tests/lit-tests/2955.ll
This PR supports the replacement of masked memory operations of effective length 3 with unmasked ones in ReplaceMaskedMemOps. This fixes issue #2955.
> ReplaceMaskedMemOps: support masked ops of length 3

- .github/workflows/clamav-release.yml
- .github/workflows/clamav.yml
- .github/workflows/cve-bin-releases.yml
- .github/workflows/cve-bin.yml
Main problem is that regular scans run in forks and create traffic to nightly builds on appveyor hosting, which is pretty limited on traffic.
Would be good to move nightly builds to github releases.
> Restrict security scans to ispc/ispc repo

- docs/ispc.rst
- src/decl.cpp
- src/module.cpp
- src/type.cpp
- src/type.h
- tests/lit-tests/err-memory-attr.ispc
- tests/lit-tests/err-unmangled.ispc
- tests/lit-tests/memory-attr.ispc
- tests/lit-tests/unmangled.ispc
This PR supports attributes: `unmangled`, `memory("read")`, `memory("none")`. 
This fixes #2956.
> Support more attributes for target redesign

- .github/workflows/bandit.config
- .github/workflows/bandit.yml
- .github/workflows/nightly-17.yml
- alloy.py
- bitcode2cpp.py
- common.py
- docs/ispc.rst
- run_tests.py
- tests/fmod-float-uniform.ispc
- tests/fmod-float-varying.ispc
- utils/lit/lit/TestRunner.py
- utils/lit/lit/formats/googletest.py
- utils/lit/lit/reports.py
- utils/lit/lit/util.py
1. Added bandit scan
2. Excluded `avx512knl-x16` from x86 testing
3. Updated result check in fmod float tests (was failing on x64 targets with -O0)
4. Added description of ispc optimization options to docs
> Bandit scan + minor CI fixes

- builtins/dispatch.c
- cmake/GenerateBuiltins.cmake
This reduces the number of copies when a user application consists of several multi-target modules. Before this change, each module had its own copy, leading to multiple instances of system ISA detection.
This PR fixes #2969 leading to the only instance of dispatcher.
> dispatch.c: make system symbols weak

- src/module.cpp
This passes `raw_stream` handler to actually see the output of verifier if module is malformed.
> module.cpp: fix llvm::verifyModule call

- src/parse.yy
- tests/lit-tests/2351.ispc
> Do not emit error for typedef struct foo {} foo

- src/parse.yy
- src/type.cpp
- src/type.h
- tests/lit-tests/2350.ispc
- tests/lit-tests/address-space-1.ispc
- tests/lit-tests/noescape.ispc
If anonymous struct has typedef then we can use typedef name instead of `$anonN`.
This fixes #2350.
> Use typedef name for anon struct

- src/type.cpp
- tests/lit-tests/anon-struct-rename.ispc
This PR is fix for #2973. `GetAsNamed` always return named struct. This prevents renaming struct when new aliases created with `typedef`.
> Fix anon struct renaming

- .github/workflows/scorecards.yml
- README.md
This PR adds a bunch of security badges to Readme.md. 
If it looks a little overcrowded, we can change names for workflows (e.g. "Bandit" instead of "Scan Python code with Bandit").
It also adds OpenSSF scorecards which shows the issues from OpenSSF [check](https://securityscorecards.dev/viewer/?uri=github.com/ispc/ispc) in Security tab.
> Security badge

- CMakeLists.txt
- src/expr.cpp
- src/func.cpp
- src/func.h
- src/module.cpp
- src/type.cpp
- src/type.h
This PR fixes #2959.
It also has a minor CMakeLists fix regarding `_FORTIFY_SOURCE=2` compile definition that can't be used in Debug mode (triggers warning with new gcc)
> Fix linkage of template instantiations

- .github/dependabot.yml
- .github/workflows/bandit.yml
- .github/workflows/cve-bin-releases.yml
- .github/workflows/cve-bin.yml
- .github/workflows/third-party/requirements.txt
This PR improves configuration of dependabot.yml. In theory (I can't test it until it's merged) it should create one PR for all dependencies update.
It also reverts 7431a910b5be098cc03ef556661d5f91bd91c8f7. Pinning the version didn't help to eliminate warnings like this one: https://github.com/ispc/ispc/security/code-scanning/88. Seems like it should be pinned by hash which is IMO overkill for the tools that are used for testing.
> Dependabot version update

- .github/dependabot.yml
Fixed groups in dependabot.yml.
Now it should create one PR for all the GA dependencies update like this one: https://github.com/aneshlya/ispc/pull/19.
> ci: fix groups in dependabot.yml

- .github/workflows/reusable.rebuild.yml
`xz` by default runs in one thread. With `tar cJvf` command running more than 20 minutes during LLVM build, it makes sense to speed this up by running in all threads.
To run in all threads we can use `xz`'s arg `-T`:
```
-T, --threads=NUM   use at most NUM threads; the default is 0 which uses
as many threads as there are processor cores
```
On Linux we can pass it through `XZ_DEFAULTS` env variable. But on macOS tar is `bsdtar` and for some reason it doesn't act like regular `tar` with `XZ_DEFAULTS` has no effect. But we can run it explicitly.
> Run zx in all threads in CI during LLVM build

- .github/workflows/ispcrt.yml
This PR adds a CI job to build ISPCRT using different tasking libraries. Example: [link](https://github.com/nurmukhametov/ispc/actions/runs/10812832056)
> CI: add job to build ISPCRT

- .github/workflows/hardening-check-release.yml
- .github/workflows/hardening-check.yml
- .github/workflows/scripts/install-build-deps-aarch64.sh
- .github/workflows/scripts/install-build-deps.ps1
- .github/workflows/scripts/install-build-deps.sh
- .github/workflows/scripts/install-svml-test-deps.sh
- .github/workflows/scripts/install-test-deps.ps1
- .github/workflows/scripts/install-test-deps.sh
- .github/workflows/scripts/run-coverity.sh
This PR adds a CI job to check hardening flags of Linux and Windows release binaries. Example of run: [link](https://github.com/nurmukhametov/ispc/actions/runs/10810929910)
> CI: add hardening checks

- docs/ispc.rst
- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/module.cpp
- tests/lit-tests/ffunction-sections.ispc
It forces the compiler to place each function in its own section.
This PR addresses the issue #2902. One can eliminate unused copies of exported functions providing this flag and enabling a linker flag that removes unused sections (`-gc-sections` for `ld` and compatible linkers).
> Add -ffunction-sections flag

- CMakeLists.txt
- cmake/FindLLVM.cmake
- src/module.cpp
- src/opt.cpp
- src/opt/MangleOpenCLBuiltins.cpp
- src/opt/XeGatherCoalescePass.cpp
`ChooseMSVCCRT.cmake` was removed from LLVM and I don't see usages of it in our cmake files: https://github.com/llvm/llvm-project/pull/66850
Also I discovered that `InferAlignmentPass` is needed in one more place to make `LoadStoreVectorizer` pass work correctly. It was caught by tests/lit-tests/load_store_vectorizer_loopunroll.ispc test. I think there may be other cases where optimization is broken because of incorrect alignment and maybe it would be good to run `InferAlignmentPass` before every `InstCombine`. But I'd like to hear more opinions about it.
> Fix xe-enabled build with LLVM 18

- ispc-opt.cpp
- src/llvmutil.cpp
- tests/lit-tests/2870.ispc
- tests/lit-tests/assume_uniform.ispc
This PR fixes issue #2870.
It propagates IR flags from vector operations to extracted scalar ones. This influences the quality of loop counter code. `nsw`/`nuw` flags were assigned to vector operations in https://github.com/ispc/ispc/commit/a3975be118ffdb8f52151ab25ce84cfceb0a1478 to exploit UB to extend loop counters (to 64-bit) avoiding extra redundant sext/zext instructions.
After this, we can reapply https://github.com/ispc/ispc/commit/99a78930624aed76b401e52a4ebae5a77a31b10d
> Propagate IRFlags for binary operators in lExtractFirstVectorElement

- src/builtins.cpp
- src/decl.cpp
- src/decl.h
- src/expr.cpp
- src/expr.h
- src/func.cpp
- src/module.cpp
- src/parse.yy
- src/sym.cpp
- src/sym.h
- src/type.cpp
- src/type.h
- tests/lit-tests/err-vec.ispc
- tests/lit-tests/func_template_nontype_8.ispc
- tests/lit-tests/func_template_shortvec_1.ispc
- tests/lit-tests/func_template_shortvec_2.ispc
- tests/lit-tests/func_template_shortvec_3.ispc
- tests/lit-tests/func_template_shortvec_4.ispc
- tests/lit-tests/func_template_shortvec_5.ispc
- tests/lit-tests/func_template_shortvec_6.ispc
- tests/lit-tests/func_template_shortvec_7.ispc
- tests/lit-tests/func_template_shortvec_8.ispc
- tests/lit-tests/func_template_shortvec_9.ispc
Partially fixes #2522. Support of soa<N> and array types will be added in a similar way.
It also adds a symbol kind to the Symbol class, which is used now only to check if the symbol in the vector size declaration is a TemplateNonTypeParameter. However, I believe it could be useful in other scenarios as well. 
The PR opens up the possibility of using constants in vector/array declarations (as seen in func_template_short_vec_9.ispc), but resolving these constants is non trivial, so I prefer not to introduce it at this stage.
> Support short vectors based on template parameters

- .github/workflows/actionlint.yml
- .github/workflows/cve-bin.yml
Fix missed pinned dependencies and token permissions. 
https://github.com/ispc/ispc/security/code-scanning
> ci: pin dependencies and set token permissions

- CMakeLists.txt
Before this change `ispc_llvm17_macos-14` `63 MB`
After this change `ispc_llvm17_macos-14` `52.7 MB`
> CMake: add -dead_strip for macOS build

- stdlib/stdlib.ispc
- tests/func-tests/fmod-double-uniform.ispc
- tests/func-tests/fmod-double-varying.ispc
- tests/func-tests/fmod-float-uniform.ispc
- tests/func-tests/fmod-float-varying.ispc
- tests/func-tests/fmod-float16-uniform.ispc
- tests/func-tests/fmod-float16-varying.ispc
Fixes #2991 .
The test is failing due to stack overflow with `O0`  on the test function entry.
In this PR I'm reducing the registers number used in fmod stdlib functions and replacing rcp(y) with x/y in test code to reduce the number of instructions.
Full testing is running here: https://github.com/aneshlya/ispc/actions/runs/10853857075
> Fix fmod-double-varying.ispc is failing in Nightly testing is nightly testing

- cmake/GenerateBuiltins.cmake
- src/ctx.cpp
- src/llvmutil.cpp
- src/opt.cpp
- src/opt/GatherCoalescePass.cpp
- src/opt/ISPCPass.h
- src/opt/ImproveMemoryOps.cpp
- src/opt/IntrinsicsOptPass.cpp
- src/opt/ReplaceStdlibShiftPass.cpp
- src/util.h
Fixes #3021
Fixes #3023
Fix the build with LLVM trunk. Three different things are here:
- Update the include paths for Instrumentation headers (#3021)
- Update Instruction Insertion API. See #3023 for details
- Remove unneeded `-c` switch, which was triggering a warning on my system - this one is not related to `trunk`.
Please pay attention during review to Instruction Insertion API. New macros are a little verbose, but it's kinda intentional - we should remove them as soon as the lowest supported version is 19.1.
> Fix build with LLVM trunk: moved `Instrumentation.h`

- docs/ispc.rst
- src/decl.cpp
- src/func.cpp
- src/type.cpp
- src/type.h
- tests/lit-tests/extern-only.ispc
If ~~export "C" ``__attribute__((remove_ispc_copy))``~~  ``__attribute__((external_only))`` is provided then generate only C/C++ version of exported function.
It addresses #2995
> Introduce external_only attribute

- CMakeLists.txt
> CMake: link with tinfo and pthread if LLVM requires them

- .github/workflows/rk-superbuild-release.yml
- .github/workflows/rk-superbuild.yml
Fixes https://github.com/ispc/ispc/issues/2998.
(already uses LLVM 18. for trunk packages).
> ci: add RK superbuild

- docker/README.md
- docker/ubuntu/18.04/xpu_ispc_build/Dockerfile
- docker/v1.25.0/ubuntu18.04/Dockerfile
This PR adds Dockerfile for v1.25.0 release. It is based on `ubuntu18.04` because of `centos7` EOL. It means that release ISPC binary will require at least GLIBC version 2.27.
> Add Dockerfile for v1.25.0 release

- .appveyor.yml
- .github/workflows/clang-tidy.yml
- .github/workflows/compiler-warnings.yml
- .github/workflows/coverity.yml
- .github/workflows/ispc-ci.yml
- .github/workflows/ispc-svml.yml
- .github/workflows/ispcrt.yml
- .github/workflows/nightly-17.yml
- .github/workflows/reusable.rebuild.yml
- .github/workflows/sanitizers.yml
- .github/workflows/slim-binary.yml
- .github/workflows/yarpgen.yml
- superbuild/osPresets.json
Switch CI jobs to use LLVM 18.1 by default.
Do not merge until all tests are passed: https://github.com/aneshlya/ispc/actions/runs/11078718054
> CI: use LLVM 18.1 by default

- builtins/dispatch.c
- cmake/GenerateBuiltins.cmake
> CMake: use explicit x86 target for dispatch

- builtins/target-neon-common.ll
- builtins/target-neon-i32x8.ll
- src/ispc.cpp
- tests/lit-tests/fminnm_vminnm_aarch64.ispc
- tests/lit-tests/fminnm_vminnm_arm.ispc
Fixes https://github.com/ispc/ispc/issues/3048.
`fminnm`/`fmaxnm` are supported for aarch64 targets.
`vminnm`/`vmaxnm` are supported on arm targets with fp-armv8 (starting cortext-a35).
> Generate fminnm/vminnm instructions on arm

- src/ispc.cpp
- tests/lit-tests/cpus_x86_llvm16.ispc
- tests/lit-tests/cpus_x86_llvm18.ispc
ARL and LNL was added into LLVM 18.
GNR is in LLVM since LLVM 16.
Link to [X86TargetParser.cpp](https://github.com/llvm/llvm-project/blob/llvmorg-18.1.8/llvm/lib/TargetParser/X86TargetParser.cpp) for easier review
> Add CPU definitions for ARL, LNL and GNR

- src/opt/ImproveMemoryOps.cpp
- tests/lit-tests/1673-1.ispc
- tests/lit-tests/2870-1.ispc
This PR is the follow-up fix to https://github.com/ispc/ispc/issues/2870
The main reason to propagate nsw/nuw flags from operations above arguments of pseudo_scatter to corresponding operations of pseudo_factored_base_scatter. This influences the quality of loop counter code.  nsw/nuw flags are assigned to vector operations in a3975be118ffdb8f52151ab25 to exploit UB to extend loop counters and some induction variables to wider type to avoid sext/zext instructions.
> Copy shl flags in ImproveMemoryOps

- src/opt.cpp
- tests/lit-tests/2954-1.ispc
- tests/lit-tests/2954.ispc
- tests/lit-tests/blend-curves-loop.ispc
This reverts commit c6543aef74c3690a60d168c9b121dfead39aa8b3 (PR #2961).
NewGVN fails to optimize out loads that drastically decreases performance for some CPUs for speficic GameDev tests.
> opt: disable NewGVN for CPU

- src/module.cpp
- src/module.h
- tests/lit-tests/3062.ispc
This PR fixes warning wrongly emitted for dependency file suffixes (#3062).
It also fixes the content of this file, is should not contain in-memory ISPC headers (`/core.isph`, `/stdlib.isph`) as dependencies for make.
> Fix deps file generation

- src/module.cpp
Fixes #3055 
This pull request includes a change to the `Symbol *Module::AddLLVMIntrinsicDecl` function in the `src/module.cpp` file to ensure compatibility with different versions of LLVM. The most important change is the conditional compilation logic to handle the difference in the `getDeclaration` method between LLVM versions.
Compatibility with LLVM versions:
* [`src/module.cpp`](diffhunk://#diff-91eede7716565a700586788e3f9d285985bf5c449a366cdd3b28fc37c073a616R505-R509): Added conditional compilation to use `llvm::Intrinsic::getDeclarationIfExists` for LLVM version 20.0 and above, while retaining `llvm::Intrinsic::getDeclaration` for earlier versions.
> Fix #3055 - changed llvm::Intrinsic::getDeclaration() function

- src/util.cpp
Fixes #3071.
The issue has long investigation of the problem, and I think that the proposed fix is the right one, as we need to preserve compatibility with older macOS versions.
> Fix for #3071 - inconsistent __libcpp_verbose_abort definition

- src/builtins.cpp
- tests/lit-tests/3068.ispc
> Fix stdlib functions calling convention for --vectorcall

- src/module.cpp
- tests/lit-tests/intrinsic.ispc
Fixes #3055 
Previous fix for the issue (#3069) was incorrect. The code is creating intrinsic declaration, not relying on its existence in the module.
This instantiates in multiple lit test failures:
```
Failed Tests (5):
ispc :: intrinsic.ispc
ispc :: intrinsic_macro.ispc
ispc :: intrinsic_matrix.ispc
ispc :: intrinsic_target_specific.ispc
ispc :: intrinsics_vnni.ispc
```
which I missed on the first iteration, as all of them are x86-specific. So I changed `intrinsic.ispc` to run on all platforms.
> Proper fix for #3055 - fix trunk build

- builtins/dispatch.c
- src/builtins.cpp
Fixes linker error from #3082.
Windows linker doesn’t automatically handle weak symbols across modules and throws an error if conflicting symbols are found.
So first this PR reverts change made it https://github.com/ispc/ispc/pull/2970.
Also it adds internal linkage to `__set_system_isa` and adds `static` to `__get_system_isa` (it's only called from `__set_system_isa` so let's inline it). Overall these changes restores the linkage behavior that was before https://github.com/ispc/ispc/pull/2879.
> Fix dispatch link errors

- .github/workflows/ispc-ci.yml
- .github/workflows/rk-superbuild-release.yml
- .github/workflows/rk-superbuild.yml
Eventually we need to fix warnings in examples build and to build them with `-Werror`.
> CI jobs to build RK ospray on Windows and examples 

- .github/workflows/ispc-ci.yml
- .github/workflows/slim-binary.yml
- scripts/alloy.py
- scripts/run_tests.py
- src/builtins.cpp
- tests/test_static.cpp
Fix for https://github.com/ispc/ispc/issues/3091 and https://github.com/ispc/ispc/issues/3076.
This PR is addition to PR https://github.com/ispc/ispc/pull/3075. The problem of previous PR was that it didn't set calling convention for stdlib function calls, only for functions themselves which led to overoptimization to "unreachable".
Also we should set calling convention only to the functions **defined** in stdlib (not to all functions declared there like builtins).
> Fix stdlib functions calling convention for --vectorcall. Part 2

- llvm_patches/18_1_19_1_InstCombine-foldVecExtTruncToExtElt-extend.patch
This contains the patch https://github.com/llvm/llvm-project/commit/795c24c6fb4f9635c912f4084fa9339ea068c3d5 (PR https://github.com/llvm/llvm-project/pull/109689) that is backported here to LLVM 18 and 19.
This fixes #2954 and #3101.
We can remove `XFAIL` from `2954.ispc` after we rebuild LLVM and update it in dependencies.
> Backport patch for InstCombine to fix #2954

- src/main.cpp
- src/target_registry.cpp
- tests/lit-tests/3126.ispc
Fixes #3126.
Now the error message also mentions a `-support-matrix` with complete info about supported targets/os/archs.
> Fix error message when unknown target/os/arch is used

- src/expr.cpp
- src/expr.h
- src/parse.yy
- tests/lit-tests/func_template_12.ispc
- tests/lit-tests/func_template_spec_1.ispc
This PR fixes #3015.
It has 3 main changes:
1. Unifies `FunctionSymbolExpr` for functions and function templates (it can be improved even better when we refactor `Symbol` and `TemplateSymbol` classes)
2. Extracts `FindBestMatchCost` from `ResolveOverloads`
3. Introduces logic how to choose between template function and function when resolving overloads.
> Fix functions and function templates overloads

- src/intrinsics.cpp
Remove mentions of llvm::Type::X86_MMXTyID: for LLVM 20.0 since it was removed from trunk
https://github.com/ispc/ispc/actions/runs/12194482841/job/34026470500#step:6:281
> Remove llvm::Type::X86_MMXTyID

- src/ctx.cpp
- src/expr.cpp
- src/intrinsics.cpp
- src/llvmutil.cpp
- src/llvmutil.h
- src/type.cpp
- src/type.h
- tests/lit-tests/3117-1.ispc
- tests/lit-tests/3117-2.ispc
- tests/lit-tests/llvm-intrinsics-gather.ispc
- tests/lit-tests/llvm-intrinsics-type-deduction.ispc
This PR supports overloaded LLVM intrinsics. 
We need to produce correct function declarations for overloaded LLVM intrinsics. ISPC used all arguments to mangling in extra suffixes (which is wrong, e.g., see #3117). We need to provide only some arguments.
This PR adds support to `<N x ptr>` ISPC type. It also introduces ISPC type that matches to `<N x i1>` for targets with `mask_bits != 1`. Both are needed to support `llvm.masked.gather` and similar. These intrinsics will be used to implement common target.
This fixes #3117.
> Support overloaded LLVM intrinsics

- builtins/dispatch.c
Change return type of __get_system_isa() to int. It should not matter because its result is anyway saved to __system_best_isa which is just int type.
This PR fixes #3134
> dispatch.c: remove stdint.h header

- src/ispc.cpp
- tests/lit-tests/aarch64_windows.ispc
- tests/lit-tests/aarch64_windows_llvm18_plus.ispc
- tests/lit-tests/arm64_macos.ispc
- tests/lit-tests/arm64_macos_llvm18_plus.ispc
- tests/lit-tests/arm_linux.ispc
- tests/lit-tests/arm_linux_llvm18_plus.ispc
- tests/lit-tests/cpu_arm.ispc
Added new CPU definitions:
1. apple-a15, apple-a16, apple-a17
2. cortex-a55, cortex-a78
3. cortex-a510, cortex-a520
These articular devices are requested by game-dev community.
Related to #3110
> CPU definitions for new aarch64 devices

- stdlib/stdlib.ispc
- tests/func-tests/ldexp-double-zero.ispc
- tests/func-tests/ldexp-float-zero.ispc
- tests/func-tests/ldexp-float16-zero.ispc
This fixes https://github.com/ispc/ispc/issues/3115
Here is comparison of code generation with and without zero handling. Plus evaluation of llvm.ldexp intrinsic as was suggested in #2538.
https://godbolt.org/z/o4qPeh3cd
> Fix ldexp zero handling

- src/module.cpp
- tests/lit-tests/3148.ispc
> Do not generate LLVM IR if preprocessor only mode

- src/intrinsics.cpp
- tests/lit-tests/3141.ispc
- tests/lit-tests/llvm-intrinsics-type-deduction.ispc
Struct and Vector are required to skip next entries also.
This PR fixes #3141
> Fix IITDescs traversing

- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/opt.cpp
- tests/lit-tests/2052-1.ispc
- tests/lit-tests/2052-2.ispc
- tests/lit-tests/2052-3.ispc
- tests/lit-tests/2720.ispc
This PR introduces usage of LoadStoreVectorizerPass and SLPVectorizerPass for ARM. As a result generated code becomes much more cleaner without extra load/stores described in issue #2052. For example:
**Before the changes:**
```
VectorTransformVector___REFs_5B__c_unFVector4_5D_REFs_5B__c_unFMatrix_5D_: // @VectorTransformVector___REFs_5B__c_unFVector4_5D_REFs_5B__c_unFMatrix_5D_
// %bb.0:
ldr	s0, [x1]
add	x8, x1, #4
ld1	{ v0.s }[1], [x8]
add	x8, x1, #8
ld1	{ v0.s }[2], [x8]
add	x8, x1, #12
ld1	{ v0.s }[3], [x8]
ldp	s1, s2, [x0]
fmul	v0.4s, v0.4s, v1.s[0]
mov	s1, v0.s[1]
ldp	s3, s4, [x1, #16]
fmadd	s3, s2, s3, s0
mov	s5, v0.s[2]
fmadd	s1, s2, s4, s1
ldp	s4, s7, [x1, #24]
ldp	s6, s17, [x0, #8]
fmadd	s4, s2, s4, s5
ldp	s5, s16, [x1, #32]
mov	s0, v0.s[3]
fmadd	s3, s6, s5, s3
fmadd	s1, s6, …
```
> Optimize code generation on on ARM (#2052)

- tests/lit-tests/2860.ispc
This is a lit test for https://github.com/ispc/ispc/issues/2860.
The issue itself was unintentionally fixed in v1.25.3.
> Add lit tests for #2860

- CMakeLists.txt
- builtins/generic.ispc
- cmake/GenerateBuiltins.cmake
- scripts/bitcode2cpp.py
- src/ispc.cpp
- src/main.cpp
- src/target_enums.cpp
- src/target_enums.h
- src/target_registry.cpp
- tests/lit-tests/generic-target-aarch64.ispc
- tests/lit-tests/generic-target-arm.ispc
- tests/lit-tests/generic-target-x86.ispc
- tests/lit-tests/generic-target-x86_64.ispc
This PR adds generic targets, including their definitions and corresponding build commands/targets. It introduces builtins/common.ispc (empty at the moment). These targets will be used in target traversal during hierarchical target builtin linking.
> Add common targets

- docs/ispc.rst
- src/decl.cpp
- src/expr.cpp
- src/module.cpp
- src/sym.cpp
- src/sym.h
- tests/lit-tests/deprecated-attr-1.ispc
- tests/lit-tests/deprecated-attr.ispc
Two variants are supported:
`__attribute__((deprecated))`
`__attribute__((deprecated("reason")))`
This fixes #2941
> Support deprecated attribute

- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- src/opt.cpp
- tests/lit-tests/loop_nounroll.ispc
- tests/lit-tests/loop_unroll-1.ispc
- tests/lit-tests/loop_unroll.ispc
- tests/lit-tests/loop_unroll_varying.ispc
- tests/lit-tests/optsize.ispc
Fixes #3164.
Surprisingly ISPC was using optLevel 1 by default. It didn't matter because we didn't pass optlevel to optimization passes but it matters now with the changes in this PR.
1. Change default optLevel to 2
2. Pass `CodegenOptLevel::Default` to codegen when -O1 is selected (it corresponds to LLVM -Os)
3. Pass optLevel to Loop unrolling passes preventing them from aggressing unrolling
4. Get InlineParams from optLevel and sizeOptlevel and pass to Inliner pass
5. Add `optSize` function attribute when -O1 is passed. It's needed for loop unrolling passes.
Note: pragma has priority over optimization level. This behavior is aligned with LLVM.
> Tune -O1 pipeline for code size

- src/expr.cpp
- tests/lit-tests/3084-1.ispc
- tests/lit-tests/3084.ispc
> Fix crash when using sizeof as global variable initializer

- src/module.cpp
This fixes the issue of leaking a file handle (DHI->file) if the file was opened but the compilation was terminated earlier for some reason, e.g., at https://github.com/ispc/ispc/blob/c9ee084affb75700d495a600f52b5ae7c2ff2173/src/module.cpp#L3776
> Fix leak of file handle in DispatchHeaderInfo

- stdlib/include/core.isph
This is needed to avoid possible name conflicts with user's ones as requested here https://github.com/ispc/ispc/pull/3140#discussion_r1911764916
> Add ISPC_ prefix to macro definitions in core.isph

- src/ctx.cpp
Fix ISPC build with LLVM trunk after https://github.com/llvm/llvm-project/pull/119679/commits/aed7ab27bcec8807fa5f4be4bbc070323ed68441
> Fix ISPC trunk build after LLVM commit aed7ab27

- src/func.cpp
- src/ispc.cpp
Fix setting of `optsize` attribute. Currently failing on print tests https://github.com/ispc/ispc/actions/runs/12824288745/job/35760635474 due to incompatible `optnone` and `optsize` attributes.
> Check for incompatible attributes before setting optsize

- .github/workflows/scripts/install-build-deps.ps1
There is no need to install Cygwin just to install `m4`. Install `m4` from Chocolatey straight away.
> Remove cygwin installation

- src/ispc.cpp
- tests/func-tests/fmod-double-varying.ispc
- tests/func-tests/fmod-float-varying.ispc
This PR should repair full tests run for generic targets.
The job result is here: https://github.com/nurmukhametov/ispc/actions/runs/12949417763
This PR sets CPU in CPU_x86_64 for generic targets when `--cpu` is not explicitly specified on command line. Otherwise, the oldest CPU model supported by LLVM is picked in backend that results in very old CPUs in case of `i686-*` triple (when ISPC compiles with `--arch=x86`).
> Set CPU for generic targets

- builtins/dispatch.c
- docs/ispc.rst
- src/builtins-decl.cpp
- src/builtins-decl.h
- src/builtins.cpp
- src/module.cpp
Replace the dependency on the C abort function with a custom implementation (`__terminate_now`), which directly invokes the `ud2` instruction.
This change introduces a breaking change for compiled user programs. Specifically, when no ISA is detected, the behavior changes from triggering an abort to executing an illegal instruction, meaning a different signal is raised (`SIGABRT` → `SIGILL`). User code that installs signal handlers for `SIGABRT` and processes them in any way will break and require modifications.
ISPC does not appear to guarantee any specific behavior for this case, so this change is likely acceptable. However, it is beneficial to document this behavior explicitly.
This fixes #3163 (at least the most important its part).
> dispatcher: remove dependency on C abort

- builtins/target-avx512-common-16.ll
- builtins/target-avx512-common-8.ll
- docs/ispc.rst
- tests/lit-tests/3181.ispc
This PR introduces using of target-specific instructions for masked load/store operations for int8/int16 types on avx512 where is directly maps to HW instructions. These instructions are covered by `avx512_bw` and `avx512_vl` features which are available starting skx (but were not available in knl)
These implementations still performs better then corresponding generic targets. However eventually we should replace remaining masked load/store functions coming from utils to generic implementation which produces much better code.
Fixes #3181.
> Use target specific intrinsics for masked load/store operations for int8/int16 types

- docs/ispc.rst
- src/ispc.cpp
- src/ispc.h
- src/main.cpp
- tests/CMakeLists.txt
- tests/lit-tests/darwin-minos-ver-1.ispc
- tests/lit-tests/darwin-minos-ver-2.ispc
- tests/lit-tests/darwin-minos-ver-3.ispc
- tests/lit-tests/lit.cfg
This PR introduces option to set min OS version for Darwin platforms.
Fixes: https://github.com/ispc/ispc/issues/3143
> Add a flag to set min os version on darwin platforms

- builtins/generic.ispc
- src/intrinsics.cpp
- src/opt/LowerISPCIntrinsics.cpp
- tests/lit-tests/ispc-intrinsics.ispc
- tests/lit-tests/ispc-intrinsics.ll
This PR fixes the tests (https://github.com/ispc/ispc/actions/runs/13108110736). Nightly runs revealed that for generic/neon targets, the `__masked_blend_store` implementation from https://github.com/ispc/ispc/commit/1f1a117743cf5110e7b109b4cd475f1ef83a6bac is effectively recursive for `-O0`. This happens because ISPC generates masked stores even inside blocks where the mask is certainly `all_on` (this occurs when the first IR is generated). Later on, ISPC relies on optimizations to replace such masked stores with usual ones.
To fix that, introduce `llvm.ispc.blend_store` and use it for `__masked_store_blend` implementation.
> Fix generic targets with `-O0`

- docs/ispc.rst
- stdlib/include/core.isph
- tests/lit-tests/macro_values.ispc
This PR fixes #2167 by updating the documentation about predefined macros and fixing the values for some of them.
> Fix predefined macro values

- tests/lit-tests/2954.ispc
This test passes when built with LLVM 20.0 or with LLVM 18/19 built with the backport patch llvm_patches/18_1_19_1_InstCombine-foldVecExtTruncToExtElt-extend.patch It is better to skip it as UNSUPPORTED for the release because many package maintainers will not have older LLVMs patched.
We also need to update LLVM 18/19 prebuilt archives to enable this test in future.
> Skip 2954.ispc

- tests/lit-tests/darwin-minos-ver-1.ispc
- tests/lit-tests/darwin-minos-ver-2.ispc
Split the darwin-minos-ver-1 test into two separate tests:
1. One that verifies the version in the triple.
2. Another that compiles ISPC/C++ and ensures there are no warnings during linkage.
The second test fails when building an x86-enabled ISPC on an ARM64 macOS system. Since I don't have a solution that works across all macOS configurations at the moment, I'm marking it as UNSUPPORTED and will address it after the release.
UPDATE: since it's not possible to do UNSUPPORTED: *, I'm removing 2nd test completely for now.
> Split darwin-minos-ver-1 test

- .github/workflows/release-pipeline.yml
It can build release archives for both Linux aarch64 and x86_64. This fixes #3216
> Add release pipeline

- .github/workflows/rebuild-llvm17.yml
- .github/workflows/rebuild-llvm18.yml
- .github/workflows/rebuild-llvm19.yml
- .github/workflows/rebuild-llvm20.yml
- .github/workflows/reusable.rebuild.yml
- .github/workflows/scripts/install-llvm-deps-mac.sh
This PR refactors LLVM build jobs removing copy-pasted jobs.
It also moves Linux arm builds completely to public runners. It also uses macos public runners for non-LTO builds.
Run: https://github.com/ispc/ispc/actions/runs/13252686163
> Refactor LLVM build jobs

- .github/workflows/clamav.yml
- .github/workflows/cve-bin.yml
- .github/workflows/dll-inject.yml
- .github/workflows/hardening-check.yml
- docs/ispc.rst
1. Mention `stdlib.isph` as a reference for standard library functions, fixes https://github.com/ispc/ispc/issues/2349
2. Replace appveyor with trunk-releases in CI workflows.
> Minor docs and CI update 

- .github/workflows/quick-start-build.yml
- scripts/quick-start-build.py
This PR fixes the `quick-start-build.py` script by correcting the `asset_name` for Windows and adding a help message. It also pins action versions.
> Fix quick-start-build.py

- scripts/quick-start-build.py
This PR fixes the issue that one reruns the `quick-start-build.py` script on Windows, e.g., for rebuilding ISPC after some changes or for running tests.
> Fix the quick-start-build.py script when it is rerun on Windows

- builtins/generic.ispc
- cmake/GenericTargets.cmake
- src/ispc.cpp
- src/parse.yy
- tests/lit-tests/3123.ispc
- tests/lit-tests/err-soa-1.ispc
- tests/lit-tests/generic-target-aarch64.ispc
- tests/lit-tests/generic-target-arm.ispc
- tests/lit-tests/generic-target-x86.ispc
- tests/lit-tests/generic-target-x86_64.ispc
This PR fixes generic_i1x64 target so it can be used in targets' hierarchy.
Fixes #3123
> Fix generic-i1x64 target

- src/ctx.cpp
- src/func.cpp
- src/stmt.cpp
- src/sym.cpp
- src/type.cpp
- src/type.h
- tests/lit-tests/2844-1.ispc
- tests/lit-tests/2844-2.ispc
- tests/lit-tests/2844-3.ispc
- tests/lit-tests/2844-4.ispc
- tests/lit-tests/2844-5.ispc
- tests/lit-tests/2844-6.ispc
- tests/lit-tests/2844-7.ispc
- tests/lit-tests/478.ispc
This fixes #2844 and #478.
This change adds error reports for incomplete types in various situations:
- return values of functions
- parameters of functions
- variable declaration and initialization
> Report compilation errors about incomplete types

- src/ispc.h
- src/main.cpp
- src/module.cpp
- src/module.h
- tests/lit-tests/3205.ispc
Added -dD and -dM options for ispc and tests. 
(Commit clean, no squash merge needed)
Implementation:
Flags macthing clang pre-process options refer to https://clang.llvm.org/doxygen/classclang_1_1PreprocessorOutputOptions.html:
-dM: ShowMacros only - Find customized macros, and no functions
-E: ShowCPP and ShowComments - Find function but no macros definition
-dD: ShowCPP, ShowMacros, and ShowComments - Find both macros definition and function.
Functionality difference: Unlike clang -dD or -dM must be used in addition with -E flag, both flags for ispc in this implementation makes the "-E" implicit. This is an easier implementation and I didn't find the benefit to follow clang. Please leave your thoughts if you prefer the clang way.
Test:
Covered by functions and macros search in results. …
> Add -dD and -dM compile flags for ispc ( Closes #3205 )

- .github/workflows/ispc-ci.yml
- examples/common/tasksys.cpp
- examples/cpu/CMakeLists.txt
- examples/cpu/cmake/AddISPCExampleLegacy.cmake
- examples/cpu/cmake/AddISPCExampleModern.cmake
- examples/cpu/deferred/dynamic_c.cpp
- examples/cpu/gmres/debug.h
- examples/cpu/gmres/main.cpp
- examples/cpu/gmres/matrix.h
- examples/cpu/gmres/mmio.c
fix the warnings in examples/cpu and update CI workflow to enforce -Werror flag for examples build
there are two warnings detected for the examples/cpu
1. in examples/cpu/deferred, the compiler warning arises from the use of a reinterpret_cast to convert the address of a local variable into a float pointer. A common and safe solution is to avoid the reinterpret_cast altogether and use a union for type punning.
2. in examples/cpu/gmres: the warning appears because the variable 'error' is set (in the else branch of the first check) but is never actually used in any decision-making or output. It was fixed by removing the unused 'error' variable
Finally, The ispc-ci.yml workflow was updated to enforce -Werror flag for examples build
> #3098 fix the warnings in examples/cpu and update CI workflow to enforce -Werror flag for examples build

- superbuild/CMakeLists.txt
[bug:3265] Enable CMake option to disable QUIET for superbuild's FetchContent calls Adding an option to superbuild's CMake file to be able to turn ON and OFF the QUIET setting when calling FetchContent_Populate.
Fixes #3265
> Enable CMake option to disable QUIET for superbuild's FetchContent

- src/type.cpp
- tests/lit-tests/412-1.ispc
This PR fixes issue #412.
It allows the creation of pointers to function types and also addresses the issue mentioned in https://github.com/ispc/ispc/issues/412#issuecomment-2382989610
> Allow pointers to function types

- src/ast.h
- src/ctx.cpp
- src/decl.cpp
- src/decl.h
- src/expr.cpp
- src/expr.h
- src/func.cpp
- src/ispc.cpp
- src/ispc.h
- src/module.cpp
- src/parse.yy
- src/stmt.cpp
- src/stmt.h
- src/sym.h
This implements #2974 
Now, the `--yydebug` is annotated like the following:
```bash
Reducing stack by rule 167 (line 1330):
$1 = nterm declarator (: programIndex)
$2 = token '=' (: )
$3 = nterm initializer (: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
-> $$ = nterm init_declarator (: programIndex)
Reading a token: Next token is token TOKEN_IDENTIFIER (: y)
Shifting token TOKEN_IDENTIFIER (: y)
Entering state 536
Reducing stack by rule 43 (line 651):
$1 = nterm postfix_expression (: b)
$2 = token '.' (: )
$3 = token TOKEN_IDENTIFIER (: y)
-> $$ = nterm postfix_expression (: b.y)
Reducing stack by rule 385 (line 2683):
$1 = nterm declaration_specifiers (: uniform  /*unbound*/ float:)
$2 = nterm declarator (: dotProduct)
$3 = nterm $@5 (: )
$4 = nterm compound_statement (: …
```
> Dump semantic values under --yydebug in parser

- src/expr.cpp
- tests/lit-tests/1234.ispc
- tests/lit-tests/3258.ispc
This PR fixes a crash on malformed code.
Fixes #1234 and #3258.
> Report an error when casting to unsized array

- builtins/target-avx-common-8.ll
- builtins/target-avx1-i32x8.ll
- builtins/target-avx2-common-i32x8.ll
For issue: #2295
This PR removes util.m4 macros from [target-avx2-common-i32x8.ll](https://github.com/ispc/ispc/compare/main...daviddjh-intel:dheadric/packed_load_store?expand=1#diff-88e339f0a363a65c810f81dc37eb94252fe598d26570270ae223eee3ffce0956) and replaces them with faster custom implementations. Implementations are largely based off of an algorithm described in this [StackOverflow article](https://stackoverflow.com/questions/36932240/avx2-what-is-the-most-efficient-way-to-pack-left-based-on-a-mask).
At the time of opening the (draft) PR, the only custom implementations are:
@__packed_store_active2i32
@__packed_store_active2i64
Below is a performance comparison, using 05_packed_load_store.exe benchmark and avx2-i32x8 target:
|                                        | MAIN + LLVM 19 | …
> Improve performance of packed_load_store2 on AVX2 i32x8

- src/expr.cpp
- tests/lit-tests/3295.ispc
> Report error when pointer types are used with unsupported binary operators

- src/module.cpp
A small fix for ISPC build with LLVM trunk: https://github.com/ispc/ispc/actions/runs/14165935006/job/39690190700
> Fix constructor of clang::HeaderSearch for LLVM trunk

- builtins/target-avx512skx-x32.ll
- builtins/target-avx512skx-x64.ll
- docs/ispc.rst
- tests/lit-tests/2611-3.ispc
This PR drops the implementation of maked stores and loads from `util.m4` (LLVM IR generic ones) in favor of generic ones from based on LLVM intrinsics from `generic.ispc` for targets `avx512*-x32` and `avx512*-x64`.
It improves performance of `08_masked_load_store` on order of magnitude, i.e., around ~10x times.
This PR changesthe implementation of masked stores and loads from `util.m4` (the generic LLVM IR versions) in favor of the generic versions based on LLVM intrinsics from `generic.ispc` for the targets avx512*-x32 and avx512*-x64.
This change improves the performance of `08_masked_load_store` by an order of magnitude (approximately ~10x).
> Improve the performance of masked_load and masked_store for AVX-512 targets (32- and 64-wide).

- src/builtins.cpp
- src/ctx.cpp
- src/intrinsics.cpp
- src/llvmutil.cpp
- src/llvmutil.h
- src/module.cpp
- src/opt/GatherCoalescePass.cpp
- src/opt/ImproveMemoryOps.cpp
- src/opt/IntrinsicsOptPass.cpp
- src/opt/ReplaceMaskedMemOps.cpp
- src/opt/XeGatherCoalescePass.cpp
- src/stmt.cpp
- src/type.cpp
This PR switches from typed pointers to more generic pointer types. This corresponds to the latest changes in LLVM trunk.
> Use PointerType::get with LLVMContext over Type

- src/ctx.cpp
- tests/lit-tests/3321.ispc
This fixes #3321.
The issue is a regression after https://github.com/ispc/ispc/commit/64d511b58fd0a78576d88cadcf9eee67ae2be7a9. I'm adding check that `ptrType->GetBaseType()` is `StructType` before accessing `GetElementType(i)`.
> Check for StructType before accessing GetElementType in gather()

- CMakeLists.txt
- benchmarks/cmake/AddBenchmark.cmake
- examples/cpu/cmake/AddISPCExampleLegacy.cmake
- tests/CMakeLists.txt
Fix missing dependencies in ISPC components for builds with ISPC_SLIM_BINARY=ON. This issue could lead to build failures when using Ninja.
> Fix dependencies for subprojects (examples/benchmarks)

- CMakeLists.txt
I came across this issue when I forgot to enable ARM targets in LLVM. This PR fixes #1869.
> CMake: disable ARM target if LLVM doesn't support them

- src/expr.cpp
- tests/lit-tests/2186.ispc
Fixes #2186 .
this PR aligns logic between `IndexExpr::GetLValueType()` and `IndexExpr::GetLValue()`.
The new code checks if `baseExprType` is a pointer first, which matches how `GetLValue` branches its logic
> Fix logic in treating pointers for IndexExpr lvalue

- src/ctx.cpp
After PR #3322, a number of tests started to fail. This PR fixes the issue by ensuring it is not applied to XE targets.
> Disable DIV and MOD for active lanes only for XE targets

- tests/func-tests/fmod-float16-uniform.ispc
- tests/func-tests/fmod-float16-varying.ispc
This PR updates fmod-float16 tests to use the same implementation for `fmod` operation as in stdlib. Looks like LLVM 18 preserves precision better and LLVM 20 performs more aggressive optimizations so the difference between `x* 1/y` and `x*rcp(y)` is quite significant on the platforms without native half support.
> Fix fmod for float16 on platforms without native half support

- src/lex.ll
- src/parse.yy
- tests/lit-tests/3355.ispc
Prioritize TOKEN_IDENTIFIER over TOKEN_TEMPLATE_NAME. In case, when both variable and template have same name it allows to shadow template with local variable.
This PR fixes #3355
> lex.ll: fix token types emitted for identifiers

- src/opt.cpp
- tests/lit-tests/3362.ispc
This PR fixes #3362.
Enabling of SROA pass between ReplaceMaskedMemOpsPass and InstCombine helps with eliminating extra instructions.
It results in 50% improvement of a couple GameDev benchmarks.
> Enable SROA pass after ReplaceMaskedMemOpsPass

- src/intrinsics.cpp
- tests/lit-tests/3360.ispc
The assert `Assert(funcDecl != nullptr);` is overprotective. Just return `nullptr` if intrinisc is not supported, the result of this function is checked further in parser.
Fixes #3360
> Fix assert if intrinsics is not supported

- src/expr.cpp
- src/intrinsics.cpp
- tests/lit-tests/3116.ispc
- tests/lit-tests/3141.ispc
Report unrepresentable LLVM IR types and fix reporting candidates when ISPC is unable to find the proper overload for a function call.
This PR fixes #3116
> Improve error reports for intrinsics

- src/expr.cpp
- src/func.cpp
- src/module.cpp
- src/opt/PeepholePass.cpp
- tests/lit-tests/2844-2.ispc
- tests/lit-tests/2844-7.ispc
- tests/lit-tests/2844-8.ispc
- tests/lit-tests/aligned-attr-type.ispc
- tests/lit-tests/bool-store-vector.ispc
- tests/lit-tests/ispc-opt.ll
This PR fixes error reporting for unsized globals and incomplete type in function arguments. It mostly caused by changes in upstream. It doesn't allow to create unsized global variables on IR level anymore.
> Fix unsized globals and incomplete types error reports

- src/func.cpp
Although it looks like a FP, remove creation of a temporary variable.
> Fix uninit warning

- .github/workflows/release-pipeline.yml
It can point to any repo reference now (SHA or branch name or tag). Define ISPC version and the corresponding docker based on the content of the file `common/version.h`.
> CI: change release pipeline parameter

- CMakeLists.txt
This is needed at least to avoid unnecessary enabling dump methods guarded by `if !defined(NDEBUG) || defined(LLVM_ENABLE_DUMP)` like, e.g., `ScaledNumber<T>::dump()` in `llvm/include/Support/ScaledNumber.h`. Their presence results in a linking error.
When we don't pass `NDEBUG` we need to link with the debug LLVM build. This wasn't a problem until the recent changes in the upstream where they guarded more API methods as DEBUG ones.
This fixes ISPC build with the recent upstream changes https://github.com/llvm/llvm-project/pull/139804
> CMake: pass NDEBUG on all platforms for non-debug

- examples/cpu/point_transform_ctypes/CMakeLists.txt
- examples/cpu/point_transform_nanobind/CMakeLists.txt
This PR fixes location of dll in examples build directory (it should be in the same folder as python script) and adds `--dllexport` flag.
> Fix Python/ISPC examples for WIndows

- src/llvmutil.cpp
- tests/lit-tests/3399.ispc
This PR adds check for `disjoint` attribute in `or` instruction.
`disjoint` attribute was introduced in LLVM 18 and means that for each bit, that bit is zero in at least one of the inputs. This allows the Or to be treated as an Add since no carry can occur from any bit.
This unblocks ImrpoveMemoryOps optimization in some cases (discovered with SSE4 and SSE2 targets).
Fixes #3399
> Add disjoint check to IsOrEquivalentToAdd

- src/expr.cpp
- tests/lit-tests/3388.ispc
This PR fix the crash of #3388 in a naive way:
ISPC crashes because `exprs[0]` is null hence the segmentation fault. If we add a check then this does not cause any segfault on the example. That being said, this is a naive fix because I do not know if having a `nullptr` in `exprs` is actually normal. If not, then another more complex fix is needed.
> Fix the crash of #3388

- src/expr.cpp
- tests/lit-tests/3404.ispc
This PR fixes the issue #3404 about an unhandled atomic type fatal error.
The problem is that `lIsMatchWithTypeWidening` is called with a `callType` argument being of type `AtomicType::TYPE_VOID` so it is not supported by the `switch` resulting in a fatal error. I think this happens because ISPC tries to check if the second `cube` function (taking a `float` in parameter) can take in input the result of the first `cube` call (of type `void`) even possibly using an implicit (safe) conversion. 
Here is the callstack when the fatal error happens for a better context:
```
#4  ispc::FatalError at ispc/src/util.cpp:462
#5  lIsMatchWithTypeWidening at ispc/src/expr.cpp:9092
#6  ispc::FunctionSymbolExpr::computeOverloadCost at ispc/src/expr.cpp:9608
#7  ispc::FunctionSymbolExpr::FindBestMatchCost …
```
> Fix issue #3404 (unhandled atomic type crash)

- src/ast.cpp
- src/ast.h
- src/decl.cpp
- src/expr.cpp
- src/expr.h
- src/func.cpp
- src/module.cpp
- src/parse.yy
- src/stmt.cpp
The primary focus of this PR is adding state tracking for type checking and optimization processes, introducing a unified `TypeCheckAndOptimize` function, and enhancing safety by preventing recursive operations. Additionally, it refactors existing methods to leverage these new mechanisms for better maintainability and robustness.
* Added `StateFlags` to `ASTNode` to track optimization and type-checking states (`OPTIMIZED_FLAG`, `TYPECHECKED_FLAG`, etc.). This includes methods to check, set, start, and finish these states, ensuring safe and non-recursive operations.
* Introduced `TypeCheckAndOptimize` functions for `ASTNode`, `Expr`, and `Stmt`, combining type checking and optimization into a single call. This simplifies code and reduces redundant calls. 
* Replaced direct calls to …
> Enforce type check

- docs/ispc.rst
- src/expr.cpp
- src/expr.h
- src/lex.ll
- src/parse.yy
- tests/func-tests/operators3.ispc
- tests/func-tests/operators4.ispc
- tests/func-tests/operators5.ispc
- tests/func-tests/operators6.ispc
- tests/func-tests/operators7.ispc
- tests/func-tests/operators8.ispc
- tests/lit-tests/func_template_operator_1.ispc
- tests/lit-tests/operators-err.ispc
- tests/lit-tests/operators.ispc
This pull request extends operator overloading capabilities for `struct` types. 
* Extended support for overloading unary (`++, --, -, !, ~`), binary (`*, /, %, +, -, >>, <<, ==, !=, <, >, <=, >=, &, |, ^, &&, ||`), and assignment (`=, +=, -=, *=, /=, %=, <<=, >>=, &=, |=, ^=`) operators for `struct` types. 
* Added a new helper function, `PossiblyResolveStructOperatorOverloads`, to centralize the logic for resolving operator overloads for `struct` types.
* Removed the now-obsolete `MakeBinaryExpr` function, simplifying the codebase by directly constructing `BinaryExpr` instances where needed.
> Extended operators support

- src/header.cpp
Added a null check for the `ftype` parameter in `lEmitNanobindWrapper` to ensure it is a valid function type. If `ftype` is null, an error message is logged and the function returns early, preventing further processing.
> nanobind: fix a potential null-deref

- docs/ispc.rst
- stdlib/include/stdlib.isph
- stdlib/stdlib.ispc
- tests/func-tests/isfinite.ispc
- tests/func-tests/isinf.ispc
This add the two basic `isinf` and `isfinite` math functions requested in #2168. They behave like in C/C++.
> Add the isinf and isfinite standard functions

- src/module.cpp
They are transitioning to using debug records only. Debug info format flag was removed in
https://github.com/llvm/llvm-project/commit/97ac6483aaead89897d9bda8a12f1f4c11fad621
> Repair build for LLVM 21

- src/ast.h
- src/expr.cpp
- src/expr.h
- tests/lit-tests/2291.ispc
- tests/lit-tests/2552.ispc
As the name suggest, this PR fix #2291 . 
Details are provided in the linked issue. It implements the new class `ConstSymbolExpr` meant to replace `ConstExpr` for node representing (optimized) `const` symbols set to compile-time constant. Overall, It behaves like `ConstExpr` except regarding lvalues.
I wonder if the `ConstSymbolExpr::Instantiate` member function is correct. I wrote it based on `SymbolExpr::Instantiate`. I am not sure of what this function is meant to do. It looks like it is not called in practice.
> Fix #2291 about extracting the address of const variables set to compile-time constants

- src/ispc.cpp
Everything is in the name. 
This is a follow up of the discussion about the IceLake issue found during the PR #3426 .
> Use the avx512icl_x16 target on IceLake CPUs instead of avx512skx_x16

- src/expr.cpp
- tests/lit-tests/2321.ispc
This PR fix #2321 as pointed out in the name. 
The newly reported errors for the code in the issue are now the following with this PR:
```ispc
/tmp/test.ispc:23:5: Error: Vector element identifier "w" is invalid for type "uniform float<3>" (out of bounds). 
reduce_col.w = reduce_add(col.w);
^^^^^^^^^^^^
/tmp/test.ispc:23:31: Error: Vector element identifier "w" is invalid for type "varying float<3>" (out of bounds). 
reduce_col.w = reduce_add(col.w);
^^^^^
```
> Fix #2321: reports an error when accessing the component w of a short vector of size 3

- docs/template-perf.txt
- docs/template.txt
Modernize docs templates.
Related change:
https://github.com/ispc/ispc.github.com/pull/79
> Modernize docs templates

- src/expr.cpp
- src/parse.yy
- tests/func-tests/operators5.ispc
- tests/func-tests/operators6.ispc
- tests/lit-tests/member_access_arrays.ispc
- tests/lit-tests/member_access_comprehensive.ispc
- tests/lit-tests/member_access_errors.ispc
- tests/lit-tests/member_access_funcall.ispc
- tests/lit-tests/member_access_nested_structs.ispc
- tests/lit-tests/member_access_regression.ispc
- tests/lit-tests/member_access_uniform_varying.ispc
Support struct access on function call returns (which is especially important when dealing with operators).
Fixes https://github.com/ispc/ispc/issues/3220 and https://github.com/ispc/ispc/issues/2533
> Support struct access on function call returns

- docs/ispc.rst
This PR fixes formatting of code inside bold sections. 
Fixes #3440.
Now it will look like this:
> Docs fix for bold sections

- docs/ispc.rst
Everything is in the name.
The list of keywords was not up to date and also incorrect. For example, `char` was in the list while it is not a reserved keyword (explicitly mentioned earlier in the doc so it was inconsistent and confusing). Moreover, `template` and `typename` were missing in the first list while they was inconsistently added in the second one. For `NULL`, it is the opposite. Additionally, `alloca` was missing in both. There are few other issues like this in these two lists.
Interestingly, while `assert` is mentioned [here](https://github.com/ispc/ispc/blob/31b620ac6a8220333880a1272ccd7e27a4526da6/src/lex.ll#L50) as a reserved token, it does not seems to actually be one : https://ispc.godbolt.org/z/Ebdd9cdMe . This looks like a bug to me.
Thus, I did not add `assert` yet to …
> Fix the list of reserved keywords in the doc

- src/lex.ll
- src/parse.yy
- stdlib/include/core.isph
- tests/lit-tests/3454.ispc
As discussed in #3448, this PR removes alloca from the list of reserved keywords so we can now use it as a variable name.
Note alloca is already covered by existing lit-tests like in `tests/lit-tests/alloca.ispc` but I added a new one to check this is not a reserved anymore and we can still use it just to be on the safe side.
> Remove alloca from reserved keywords

- src/parse.yy
- tests/lit-tests/3471.ispc
> Fix #3471: fix a crash when using the signed keyword

- docs/ispc.rst
- stdlib/include/stdlib.isph
- stdlib/stdlib.ispc
- tests/func-tests/srgb8.ispc
This PR fixes #1964 (add `srgb8_to_float` to ISPC standard library).
Everything is said in the issue and comments in the codes ;) .
Here is the 2 new functions:
```ispc
float srgb8_to_float(int inval)
uniform float srgb8_to_float(uniform int inval)
```
> Fix #1964: add srgb8_to_float to the stdlib

- builtins/generic.ispc
- builtins/target-avx512-utils.ll
- builtins/util.m4
This PR removes permutation definitions from AVX512 builtins. rotate and shift have been unused since versions #3464 and #3441. For broadcasts, the same code is produced. It also changes the generic shift implementation to a similar one in `utils.m4` that avoids branching. It also removes the dependency of `__reduce_equal` from `__rotate`. The call to `__rotate(x, 1)` is changed to an equivalent `__shuffle` call.
> Generic permutations for avx512

- docs/ispc.rst
- src/lex.ll
- tests/lit-tests/2207-1.ispc
- tests/lit-tests/2207-2.ispc
- tests/lit-tests/2207-3.ispc
- tests/lit-tests/2207-4.ispc
- tests/lit-tests/2207-5.ispc
- tests/lit-tests/2207-6.ispc
This PR fixes #2207 (i.e. it makes the integer suffix definition stricter).
> Fix #2207: make integer suffix definition stricter

- src/parse.yy
- tests/lit-tests/707.ispc
This PR fixes #707 (and the duplicate issue #1272).
The modification also impacts template arguments (but not template parameters).
Short vectors can now be syntactically supported but they do not seems to be fully supported by the rest of the ISPC code. Thus, I explicitly disabled them so far. I put some examples in the lit-test code showing what could be easily supported and what breaks (or is ambiguous) if we enable them. I think supporting short vectors in `new` expression can be a good idea though it is certainly a low-priority feature since I do not expect much people to use it. I am not sure it make sense in template parameters (nor if this is already supported in the rest of the code, and otherwise if this is simple to do). What do you think about this?
Anyway, note that this can …
> Fix #707: support signed/unsigned/const in 'new' expressions and template arguments

- scripts/bitcode2cpp.py
- scripts/dump_stdlib_deps.py
After hierarchical linking and the generic builtins implementation were introduced, it became more tricky to trace where these functions actually come from.
This script traverses the functions provided by the user for some target across stdlib/builtin modules to dump their call graph with information about where each particular function is coming from.
```bash
$ ../scripts/dump_stdlib_deps.py shift___vyiuni avx512spr-x4
Analyzing dependencies for function 'shift___vyiuni' on target 'avx512spr-x4'
Note: Hiding pseudo/compiler placeholder functions
Bitcode directory: ./share/ispc
Max depth: 10
--------------------------------------------------------------------------------
Target Hierarchy Chain:
avx512spr-x4 → avx512icl-x4 → avx512skx-x4 → generic-i1x4
Dependency Tree:
└── shift___vyiuni …
```
> scripts: add dump_stdlib_deps.py

- CMakeLists.txt
- cmake/ispcConfig.cmake.in
- docs/ispc.rst
- examples/cpu/CMakeLists.txt
- examples/cpu/simple_lib/CMakeLists.txt
- examples/cpu/simple_lib/simple.cpp
- examples/cpu/simple_lib/simple.ispc
- src/include/ispc/ispc.h
- src/ispc_impl.cpp
- src/main.cpp
This pull request enables ISPC to function as a library. The most important changes include adding support for building ISPC as a shared library, creating a new API for programmatic compilation using the `ispc::ISPCEngine` class, and introducing an example (`simple_lib`) that showcases how to use ISPC in library mode.
* Added new header file `ispc.h` defining the API for initializing, shutting down, and compiling ISPC code via library functions 
* Implemented the ISPC library functionality in `ispc_impl.cpp`, including methods for compilation and linking 
* Updated `main.cpp` to include the new library header and removed redundant methods, delegating functionality to the library implementation.
* Added new build target to build shared and static library
* Added `ispcConfig.cmake.in` to …
> ISPC as a library

- .github/workflows/reusable.ispc.test.yml
The `alloy.py` doesn't return error code in case if there were any test failures. This PR adds a check that `git diff` is not empty which means that `alloy.py` updated fail_db with new failures.
The CI was broken for quite a while and there is a bunch of test failures. 
Full run is here: https://github.com/ispc/ispc/actions/runs/16325104505
> Fix reusable test workflow

- .github/workflows/ispc-ci.yml
- src/args.cpp
- tests/lit-tests/mcmodel_x86_error.ispc
Report an error when mcmodel large and x86 are used. Also exclude this options combination from testing
> Report an error when mcmodel large and x86 are used

- .github/workflows/reusable.ispc.test.yml
Skip avx10 targets on x86 due to SDE problem (same as for avx512).
> ci: skip avx10 targets on x86

- src/args.cpp
- src/ast.cpp
- src/decl.cpp
- src/expr.cpp
- src/func.cpp
- src/header.cpp
- src/ispc_impl.cpp
- src/llvmutil.cpp
- src/opt.cpp
- src/type.cpp
This PR fixes minor Coverity issues related to using `std::move` instead of object copying.
> Use std::move() to avoid unnecessary copying

- src/expr.cpp
- tests/lit-tests/2376.ispc
- tests/lit-tests/3484-1.ispc
- tests/lit-tests/3484-2.ispc
Fixed three separate compiler crashes that occurred when processing invalid or edge-case ISPC code related to short vectors.
1. Use ISPC's `symVectorType->LLVMType(g->ctx)` instead of manually constructing `llvm::FixedVectorType::get()`
2. Null pointer check (src/expr.cpp:4831)
3. Use PointerType::GetVarying() when indexType->IsVaryingType()
4. Early exit if we can't construct short vector from initializer list due to different variability.
> Fix of several crashes related to short vector initialization/indexing

- scripts/run_tests.py
- stdlib/include/short_vec.isph
* `run_tests.py`: Increased the stack size to 8MB for Windows builds to accommodate large stack frames generated by certain tests, especially for `-O0` optimizations on x86.
* `stdlib/include/short_vec.isph`: updated the `select` function to cast `cond` to `UIntMaskType` as workaround for #3491
> Workaround #3491

- CMakeLists.txt
- src/ast.cpp
- src/ctx.cpp
- src/expr.cpp
- src/func.cpp
- src/intrinsics.cpp
- src/isa.h
- src/ispc.h
- src/module.cpp
- src/opt/ReplaceMaskedMemOps.cpp
- src/stmt.cpp
- src/target_registry.cpp
This PR fixes unused function warnings (the most annoying one was about get_x86_isa). Moreover, a few sign-compare warnings were also fixed. This PR enables these two diagnostics for non-Windows builds.
> Fix clang warnings

- src/ctx.cpp
- stdlib/include/short_vec.isph
- tests/func-tests/select-short-vec-func.ispc
- tests/lit-tests/3491.ispc
- tests/lit-tests/3513.ispc
- tests/lit-tests/lit.cfg
This PR fixes #3491 properly. With this fix nightly tests should pass [link](https://github.com/ispc/ispc/actions/runs/16624470651). However in full testing, there are still failed jobs with, e.g, avx1-i32x16 for -O1 for LLVM <= 19 [link](https://github.com/ispc/ispc/actions/runs/16624474802).
This PR changes:
* Gather missed conversion of bool to storage type for targets with i8 mask.
* This also fixes FunctionEmitContext::lSwitchBoolSize_2 to be able to cast bool <-> mask of equal length to each other, i.e., performing either 0x01 -> 0xff or 0xff -> 0x01 conversion.
* maskedStore: convert only bool to bool storage representation. Plain int8 or uint8 do not to be represented or converted like bool types.
* Added debug wrapper functions (`dv` and `dt`) for dumping LLVM values and types in …
> Fix select-short-vec.ispc for targets with i8 mask

- src/expr.cpp
- tests/lit-tests/3474.ispc
- tests/lit-tests/3514.ispc
Change float/double to bool conversion from using FCMP_ONE (ordered and not equal) to FCMP_UNE (unordered and not equal) to handle NaN values correctly.
In C/C++, NaN converts to bool true because it does not compare equal to zero. The previous implementation incorrectly returned false for NaN values.
Fixes #3514
> Fix NaN to bool conversion to match C/C++ behavior

- .github/workflows/ispc-ci.yml
- tests/func-tests/ldexp-float16.ispc
- tests/func-tests/round-float16-uniform.ispc
- tests/func-tests/round-float16-varying.ispc
- CI: ignore for now --opt=fast-math for macos-test-flags
- func-tests: skip round-float16-*.ispc for all targets on Windows
- ldexp-float16 func-test: reduce input range to avoid float16 overflow (happened for x64 targets).
Full test run: https://github.com/ispc/ispc/actions/runs/16835313082
> Fix or ignore some nightly CI issues

- src/expr.cpp
- tests/lit-tests/3549.ispc
Fixes assertion failure in lAddVaryingOffsetsIfNeeded() when compiling expressions like `(func(x))[c]` where func returns a pointer type.
When indexing into the result of a function call that returns a pointer (e.g., `func()[index]`), IndexExpr::GetLValueType() would incorrectly require baseExpr->GetLValueType() to be non-null. However, function calls returning pointers are rvalues, so FunctionCallExpr::GetLValueType() correctly returns null for non-reference return types.
The fix allows IndexExpr to fall back to using the pointer type directly when GetLValueType() returns null but GetType() returns a pointer type. This enables indexing operations on function call results that return pointers, which should create valid lvalues.
> Fix IndexExpr::GetLValueType() for function calls returning pointers

- src/parse.yy
- tests/lit-tests/3563.ispc
This commit fixes a bug introduced by the Type system refactoring in commit fdb994e64 where enum fields were not included in generated C/C++ header files.
The issue was caused by a change in caching behavior during type transformations:
- Old system: EnumType had its own GetAsConstType()/GetAsUniformType() methods that created new copies without caching
- New system: EnumType uses base Type class methods that cache the results
The parsing order in lCreateEnumType() called lFinalizeEnumeratorSymbols() before SetEnumerators(), causing cached const/uniform type copies to be created with empty enumerator lists. When SetEnumerators() was later called, it only updated the original EnumType, not the cached copies used for header generation.
> Fix enum fields missing from generated headers

- src/ctx.cpp
- tests/lit-tests/3491.ispc
- tests/lit-tests/3571.ispc
- tests/lit-tests/bool-store-varying.ispc
Replace trunc i8 to i1 with icmp ne i8, 0 for proper bool conversion. LLVM 19+ removed the InstCombine canonicalization that converted trunc i8 to i1 to icmp ne i8, 0. This caused uniform bool return values to potentially be 255 instead of the expected 1.
The fix updates lSwitchBoolSize_2() in ctx.cpp to generate proper comparison instructions instead of relying on removed LLVM InstCombine canonicalization. This canonicalization for trunc to `i1` in LLVM was removed in https://github.com/llvm/llvm-project/pull/84628 that caused regression in #3571.
> Replace trunc i8 to i1 with icmp ne i8 in bool conversion

- .github/workflows/openmoonray.yml
- .github/workflows/opensource-projects.yml
This pull request updates the build workflow for OpenMoonRay to improve testing coverage. The main changes focus on enabling and running tests during the build process.
**Testing improvements:**
* Updated `PKGBUILD` configuration to enable testing by switching `MOONRAY_BUILD_TESTING` and `BUILD_TESTING` from `OFF` to `ON`.
* Added steps to run tests after building by navigating to the `build` directory and executing `ctest -L unit`.
> CI: enable testing in OpenMoonRay workflow

- .github/workflows/ispc-ci.yml
- examples/cpu/CMakeLists.txt
- examples/cpu/amx/CMakeLists.txt
- examples/cpu/amx/amx_matmul.cpp
- examples/cpu/amx/amx_matmul.ispc
This pull request adds a new Intel AMX-FP16 matrix multiplication example to the CPU examples, including hardware or emulator detection.
* Added `amx` subdirectory to the CPU examples.
* `examples/cpu/amx/CMakeLists.txt`: Implements detection for AMX hardware support via CPUID and falls back to Intel SDE emulation if hardware is not available. Adds a build/run target only when AMX support is detected, and sets up all necessary compile and run configurations.
* `examples/cpu/amx/amx_matmul.ispc`: an ISPC implementation of AMX-FP16 matrix multiplication, including AMX tile configuration, matrix initialization, AMX and naive multiplication kernels, result verification.
* `examples/cpu/amx/amx_matmul.cpp`: C++ code that requests AMX permissions, runs both the AMX and naive implementations, …
> Add amx example

- src/opt/ReplacePseudoMemoryOps.cpp
- tests/lit-tests/3358.ispc
This PR supports structures in analysis allowing to promote masked store to blend store. It's especially beneficial on the targets without HW masked stores (like neon, sse4) where emulating of masked store results in multiple branches.
No regressions were observed. One improvement of 53% is present on one GameDev benchmark.
> Fix 3358: Support structures in lIsSafeToBlend

- docs/ispc.rst
- src/ctx.cpp
- src/ctx.h
- src/stmt.cpp
- tests/lit-tests/assume_uniform_xe.ispc
- tests/lit-tests/ind-var-simplify-xe.ispc
- tests/lit-tests/ind-var-simplify.ispc
- tests/lit-tests/loop_mustprogress.ispc
This PR adds `llvm.mustprogress` metadata to the loops with non-constant conditions as suggested in https://github.com/ispc/ispc/issues/3238. 
We do not add it to loops with constant conditions like `for(;;)` or `while(1)`. It matches C standard behavior.
> Attach loop.mustprogress metadata to loops
